### ISSUE TITLE
PHP 8.2: Поиск выдаёт ошибку, если запрос пустой

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#1000]
На PHP 7.4 эта проблема отсутствует

![зображення](https://github.com/openvk/openvk/assets/22993408/e3da18c5-9147-4986-9f2d-8d4774080ba6)

**Comment by veselcraft** [comment]
ой ржу это тысячный issue ура

**Comment by veselcraft** [comment]
надо будет купить яблочный shorly)

**Comment by tretdm** [comment]
> На PHP 7.4 эта проблема отсутствует
> 
> ![зображення](https://user-images.githubusercontent.com/22993408/278024722-e3da18c5-9147-4986-9f2d-8d4774080ba6.png)

во у меня точно также ахаха

**Comment by tretdm** [comment]
@celestora мне предлагала вместо костыльного `sizeof((array)$data)` два варианта:
либо `$data->count()`, либо `$data->getRowCount()`

Первый 100% не подошёл, а второй - далеко не везде работает, поэтому я часть изменений из пулл-реквеста уже откатил так знатно. Ситуацию осугубило то, что PHP 8.x теперь имеет более строгую систему типов переменных.
![SCR_20231025_162910_firefox](https://github.com/openvk/openvk/assets/76806170/9e384894-7754-4c70-b7ac-2be97dc8e2ed)
![SCR_20231025_165454_firefox](https://github.com/openvk/openvk/assets/76806170/39dd3620-0356-4ced-829f-214e587f6256)

**Comment by veselcraft** [comment]
Да, вот меня тоже бесит что в новой пыхе переменные строгие, и какую то банальщину приходится переделывать

26 окт. 2023 г. 04:56:00 Dmitry Tretyakov ***@***.***>:

**Comment by tretdm** [comment]
Из-за чего часто страдают гентузятники, калькулейтеры и арчеводы. Я не в обиду, конечно, но сам факт, что из этих дистрибутивов PHP 7.4 уже не остаётся.
![SCR_20231026_213910_firefox](https://github.com/openvk/openvk/assets/76806170/3d05c14d-7b2f-4b41-abd2-4714a2109d6d)
![SCR_20231026_214014_firefox](https://github.com/openvk/openvk/assets/76806170/22b11f68-3346-4c55-b982-21aedfc5b760)
![SCR_20231026_214123_firefox](https://github.com/openvk/openvk/assets/76806170/0ee988cb-1cf9-45e0-bea3-74348b9557bc)

**Comment by WerySkok** [comment]
Ну хватит ныть, что старую версию перестали поддерживать. Всё, её больше нет, начните поддерживать, то, что есть уже блин

**Comment by veselcraft** [comment]
> Ну хватит ныть, что старую версию перестали поддерживать. Всё, её больше нет, начните поддерживать, то, что есть уже блин

и правильно

**Comment by veselcraft** [comment]
> @celestora мне предлагала вместо костыльного `sizeof((array)$data)` два варианта: либо `$data->count()`, либо `$data->getRowCount()`

Там походу проблема в шаблоне поиска, а не в самом `sizeof()`
