### ISSUE TITLE
Конкретно на этой фотографии не работают кнопки

### ISSUE THREAD

**Issue by LITE228** [OpenVK/openvk#1009]
Текст сам по себе кликабельный, но при нажатии ничего не происходит и сама кнопка не подсвечивается
![image](https://github.com/openvk/openvk/assets/97251902/ee3f23df-c987-4d26-aad4-0014d3fa6d8a)

**Comment by ayaaop** [comment]
![image](https://github.com/openvk/openvk/assets/58212796/348d43d4-d52a-4187-ab47-fccb47de84e0)
почему эта штука выходит за рамки фотки

**Comment by saursvepur** [comment]
> ![image](https://user-images.githubusercontent.com/58212796/278876441-348d43d4-d52a-4187-ab47-fccb47de84e0.png) почему эта штука выходит за рамки фотки

 в css .ovk-photo-slide-right ставим width на 20%

**Comment by ayaaop** [comment]
зачем вообще нужна эта штука, если в посте прикреплена только одна фотка?
