### ISSUE TITLE
PHP 8.2: Ошибка 500 в разделе "Друзья"

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#1011]
При открытии второй и далее страницы в разделе "Друзья -> Входящие заявки" выпадает ошибка 500.
![image](https://github.com/openvk/openvk/assets/60743585/aeb933c8-73df-40ae-8994-4c9fe2f0f5f3)

**Comment by ghost** [comment]
Ну вообще, это уже пофикшено, сервер не обновлён просто

**Comment by veselcraft** [comment]
@lalka2016 обновил
