### ISSUE TITLE
PHP 8.2: Error 500 в API users.get

### ISSUE THREAD

**Issue by saursvepur** [OpenVK/openvk#1012]
![image](https://github.com/openvk/openvk/assets/55963296/f60c26ba-0e03-45ce-aca8-bab3f181c490)

**Comment by tretdm** [comment]
@veselcraft начнёт удивляться, как он сразу перешел на php 8.2

**Comment by ghost** [comment]
Тут дело в $authuser. Если он нигде не используется, то можно убрать
![изображение](https://github.com/openvk/openvk/assets/99399973/3e03de39-ab6b-4d84-9b40-4937caf5a3c9)

**Comment by tretdm** [comment]
> Тут дело в $authuser. Если он нигде не используется, то можно убрать ![изображение](https://user-images.githubusercontent.com/99399973/278961820-3e03de39-ab6b-4d84-9b40-4937caf5a3c9.png)

а мб он нужен

https://github.com/openvk/openvk/assets/76806170/566f208f-6f53-4a4c-834f-d7808e4bb4b9
