### ISSUE TITLE
Я не могу выложить пост на стену с помощью Opera Mini 4 для j2me на инстанце openvk.xyz

### ISSUE THREAD

**Issue by dibof228** [OpenVK/openvk#1014]
Захотел по приколу зайти в ОВК на своей Нокии 2760, смог войти в ОВК, но когда я написал и захотел выложить пост на свою стену то вылетела ошибка сервера 500

**Comment by ghost** [comment]
Купи норм телефон лол

**Comment by nbt1248** [comment]
Он сломал свой редми

**Comment by iamdelickkk** [comment]
ебать ты мазохист, купи себе хотя бы дешёвый андроид телефон

**Comment by SuperErnD** [comment]
хз надо локально ставить и смотреть чо за ошибка, не будут же дев врубать на проде

**Comment by nikita232f** [comment]
ебать копать

**Comment by nikita232f** [comment]
![IMG_20231103_010911_689.jpg](https://github.com/openvk/openvk/assets/93428510/fc746e3b-4f82-4ff6-bc8f-ad2e624841eb)
