### ISSUE TITLE
Не сохраняется стиль

### ISSUE THREAD

**Issue by pingwin840** [OpenVK/openvk#1016]
Меняю стили, а они не сохраняются.

**Comment by nbt1248** [comment]
ты нажал на кнопку сохранить посреди страницы или в конце?

**Comment by pingwin840** [comment]
> ты нажал на кнопку сохранить посреди страницы или в конце?

да

**Comment by ghost** [comment]
> ты нажал на кнопку сохранить посреди страницы или в конце?

Возможн он имеет ввиду что на телефоне нельзя сменить тему с мобильной

**Comment by pingwin840** [comment]
> > ты нажал на кнопку сохранить посреди страницы или в конце?
> 
> Возможн он имеет ввиду что на телефоне нельзя сменить тему с мобильной

нет

**Comment by nbt1248** [comment]
> > ты нажал на кнопку сохранить посреди страницы или в конце?
> 
> да

так посередине или в конце

**Comment by nbt1248** [comment]
покажу скрином
![Screenshot_2023-11-04-14-28-46-245_com android chrome-edit](https://github.com/openvk/openvk/assets/67861312/64bee776-322f-4b37-94c7-d66fac6de34d)

**Comment by NoPlagiarism** [comment]
~~OpenVK Modern так и выглядит.~~

ДА ПОСТАВЬТЕ УЖЕ СЕБЕ АВАТАРКИ, Я ПУТАЮСЬ МЕЖДУ ВАМИ!

**Comment by pingwin840** [comment]
все работает. я сам тупонул.
