### ISSUE TITLE
[Аудиозаписи] Невозможность создания плейлиста в группе

### ISSUE THREAD

**Issue by dimon495** [OpenVK/openvk#1028]
Кнопка "Создать плейлист" в списке аудиозаписей группы перекидывает на создание плейлиста в аудиозаписях профиля. Гифку с демонстрацией проблемы прилагаю
![ReYsZRBUfb](https://github.com/openvk/openvk/assets/76395065/847261c8-aba3-4240-999c-4bd232f2c0e7)

**Comment by ghost** [comment]
Нажми на другую кнопку "новый плейлист"

**Comment by dimon495** [comment]
> Нажми на другую кнопку "новый плейлист"

пиздец я тупорез, спасибо
