### ISSUE TITLE
Название трека не вмещается

### ISSUE THREAD

**Issue by l3nal3t0va** [OpenVK/openvk#1029]
![image](https://github.com/openvk/openvk/assets/63073463/809b4162-8979-41a7-a98d-1dabdf27a8e4)
тутачки не вместилось название трека, а вместе с ним и значок E

**Comment by nikita232f** [comment]
Песня про похуиста 🤑

**Comment by ghost** [comment]
Теперь вмещается вроде.
![0](https://github.com/user-attachments/assets/967103fb-6275-46d6-bbc4-93a2cb7ac781)
