### ISSUE TITLE
Изменения понятия "гендер" и "пол" на "местоимения"

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#1032]
В OpenVK Classic была забавная возможность не выбирать пол, и тогда сайт обращался к пользователю как "оно/его"

В этом движке уже такого выбора нет, однако ныне приколюха классического ОВК очень может пригодиться людям, идентифицирующих себя как "небинарные". Но и понятие "пол" для этого не особо подходит, **поэтому предлагаю поменять понятие "пол" и "гендер" на "местоимения".** Кое-какие изменения я уже сделал в ветке https://github.com/openvk/openvk/tree/pronouns.

- Оно влияет только на обращения
- Я сам заебусь всякие гендеры добавлять
- Это +/- совместимо с оригинальным API ВКонтакте

P.s. За квирфобию в комментах буду банить

**Comment by ghost** [comment]
А можно добавить напротив (он\его) какой пол, чтоб нешарящим бьіло понятно?

**Comment by veselcraft** [comment]
> А можно добавить напротив (он\его) какой пол, чтоб нешарящим бьіло понятно?

Я думаю "нешарящие" догадаются что это такое

**Comment by WerySkok** [comment]
Это надо было сразу в пр оформлять

**Comment by ghost** [comment]
Немножко сложно

Если реализовать эту фичу - то что делать с #718

**Comment by Artem13327** [comment]
Мне кажется или уже давно выполнено?
