### ISSUE TITLE
[Аудиозаписи] Подтверждение удаления аудиозаписи + фича

### ISSUE THREAD

**Issue by dimon495** [OpenVK/openvk#1035]
Предлагаю сделать попап с подтверждением об удалении песни, а то можно мисскликнуть (как я) и удалить нужную песню. Также предлагаю добавить при наведении на кнопки управления подсказки (что собственно эта кнопка делает), как было в ВК

**Comment by saursvepur** [comment]
**бля, предлагаю сделать список музыки раздела "моя музыка" начиная с последней аудиозаписи а не с первой как сейчас, ведь в ВК также было**
