### ISSUE TITLE
В композер.жсон творится что-то жуткое

### ISSUE THREAD

**Issue by cithis** [OpenVK/openvk#1036]
Всё в dev-master. Плохо, ибо сборка кода в архив тогда невоспроизводимая по определнию. Надо бы вставить туда конкретные версии и по надобности обновлять.

**Comment by WerySkok** [comment]
А лок-файла у композера нет?

**Comment by WerySkok** [comment]
Так, закинул composer.lock в 6954cd9c55f5a2e9e0d3cae33c8ee1179e6c53fb, так что проблему можно считать решённой
