### ISSUE TITLE
[Аудиозаписи] Сортировать список аудиозаписей от новых к старому

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#1037]
**бля, предлагаю сделать список музыки раздела "моя музыка" начиная с последней аудиозаписи а не с первой как сейчас, ведь в ВК также было**

_Originally posted by @saursvepur in https://github.com/openvk/openvk/issues/1035#issuecomment-1809677491_

**Comment by ghost** [comment]
Уже сделано в 1f340e3, серв не обновили просто

**Comment by WerySkok** [comment]
Серв обновлён ес чё
