### ISSUE TITLE
Рефактор с разделением логики и фронтенда OpenVK.

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#104]
Это должно стать 1-м шагом к возможности менять дизайн в OpenVK (не только менять CSS, но и макеты страниц).

Необходимо, чтобы вся пользовательская часть OpenVK (которая пока оформлена в стиле 2007 года) была отделена от логики (бэкенда) и вынесена во взаимозаменяемый компонент.

Примеров CMS с похожим поведением много, но мне привычнее MediaWiki, поэтому я предлагаю ориентироваться на его принцип работы скинов.

**Comment by veselcraft** [comment]
С давним обновлением Chandler можно использовать и свои шаблоны, если цель данной проблемы конечно стояла именно полная кастомизация сайта (не только CSS)

**Comment by celestora** [comment]
Частично фикс в Themepack driver Jesting Jill (api level 0), можно делать скины. Есть проблема с тем, что овк отдаёт не viewmodel, а просто некоторые объекты в шаблонизатор. Вроде бы так можно гибче делать темы, но вроде как-то воняет, но энивей к этой проблеме не относится => закрываю какашк
