### ISSUE TITLE
Нижняя панель действий съезжает при наличии двух фотографий в записи

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#1040]
Такая ошибка показывается как при старом варианте показа постов, так и при новом (микроблог)
![image](https://github.com/openvk/openvk/assets/60743585/3cfa5a18-e58a-4654-9694-f2399ba9e594)

![image](https://github.com/openvk/openvk/assets/60743585/071bd8b9-6149-409b-a19b-275755b0e7b9)

**Comment by ghost** [comment]
Вроде бы исправлено
![image](https://github.com/user-attachments/assets/d1a50ed7-8689-4ddf-96ce-841e2e4be7b1)
