### ISSUE TITLE
Какая-то магия с базой данных

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#1041]
Менял версии бд, и саму бд одна и таже ошибка `Table 'profiles' does not have a primary key` заливал заведомо исправный дамп, не работает. В чём проблема, подозреваю что такое появилось в последних версиях овк?

**Comment by celestora** [comment]
@zavsc Кеш тёр?

**Comment by zavolo** [comment]
> @zavsc Кеш тёр?

неа

**Comment by celestora** [comment]
@zavsc потри

**Comment by zavolo** [comment]
Потёр, теперь другая ошибка `SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'openvk.reports.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by zavolo** [comment]
опекун такой Mysql 8.0.35-0ubuntu0.20.04.1 - (Ubuntu)

**Comment by zavolo** [comment]
теперь другая ошибка `Cannot read an undeclared column 'marital_status_user', did you mean 'marital_status'`

**Comment by zavolo** [comment]
![image](https://github.com/openvk/openvk/assets/90477403/d884c684-f9b4-4221-b370-4e424fe847a9)

**Comment by celestora** [comment]
@zavsc Ура скл файла нет

**Comment by zavolo** [comment]
> @zavsc Ура скл файла нет

мне не полный дамп дали) Всё работает ,спасибо
