### ISSUE TITLE
Error 500 в методе API Photos.GetAlbums

### ISSUE THREAD

**Issue by saursvepur** [OpenVK/openvk#1043]
**По этой причине и не грузит альбомы созданными юзером в приложении**
![image](https://github.com/openvk/openvk/assets/55963296/719596d8-bc95-44e2-acb2-32280240605d)

**Comment by tretdm** [comment]
Стоп, это не тот Owner ID, сейчас скажу, какие параметры вызывают ошибку.

**Comment by tretdm** [comment]
Ну да, это мы с айдишники в приложении накосячили, так что по идеи ошибка должна возвращаться не через Tracer. Пардон.

**Comment by ghost** [comment]
Опять проверка на пользователя не там 🤣🤣
![изображение](https://github.com/openvk/openvk/assets/99399973/f127df73-ceb2-43bf-b8d8-7b51224171c9)

**Comment by saursvepur** [comment]
**Ну ты и Дима)))**
