### ISSUE TITLE
Отклонить заявку (в друзья) или Оставить в подписчиках

### ISSUE THREAD

**Issue by LITE228** [OpenVK/openvk#1046]
![image](https://github.com/openvk/openvk/assets/97251902/91f91561-4e07-4148-b45e-9efa65be5678)
чтобы вот эта циферка не мозолила глаза
![image](https://github.com/openvk/openvk/assets/97251902/eb3b54a0-230a-4a1c-997d-e8d39092b052)

**Comment by celestora** [comment]
Blocked by (is duplicate of?) #429

**Comment by WerySkok** [comment]
Дубликат #589.
