### ISSUE TITLE
Не использовать брендинг "OpenVK 2.0" и "OpenVK 2"

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#105]
Многие знают, что текущая вариация OpenVK подставлялась под названием "OpenVK 2.0", однако данное название было бы странным при создании будущих релизов OpenVK.

**К чему это я?** Вот, допустим, существует [semver](https://semver.org/) и мы возможно будем использовать в будущем как систему для версионирования релизов. И чтобы не использовать что-то вроде "**OpenVK 2.0** _1.1.25_", то необходимо использовать брендинг "OpenVK" на постоянной основе. Так проще, и пользователи не будут путаться в этом.

**Comment by veselcraft** [comment]
К тому же, брендинг "OpenVK 2.0" был из-за того, что в своё время были доступны исходники простого "OpenVK" (который сейчас называется "классиком", но так как мы закрыли её исходные коды, смысл называть текущий проект "2.0" бессмысленно

**Comment by veselcraft** [comment]
Я думаю, мы уже везде поменяли брендинг, убрав 2.0 из названия. Если уже неактуально, то могу закрыть Issue
