### ISSUE TITLE
Нет перевода "@gender"

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#1058]
![изображение](https://github.com/openvk/openvk/assets/40203830/309965b2-1bff-4cee-ba78-6f9a2ed6cff1)
Перевода нет ни в одном из проверенных мной языков

**Comment by grishiit** [comment]
![Scrn_20231203_175620](https://github.com/openvk/openvk/assets/40203830/96ffcd06-da6d-4a0e-b88c-8ad23e965a94)
Белорусский тоже отличился

**Comment by Artem13327** [comment]
Мне кажется или можно закрывать?
