### ISSUE TITLE
Баг після зміни аватарки профілю

### ISSUE THREAD

**Issue by elifdef** [OpenVK/openvk#1068]
ПІсля зміни аватарки профілю, пропала шапка сайту (де головна, групи, пошук, запросити і т.д). Також пропав скрол сайту і стало неможливо гортати сторінку профілю. Якщо міняти масштаб сайту, то всерівно не видно шапки
![зображення](https://github.com/openvk/openvk/assets/115715823/d7524a3d-aec8-4537-8426-56b60cf3a71f)
![зображення](https://github.com/openvk/openvk/assets/115715823/7fefed16-ceeb-47ba-a0dc-71ed2d67c7a3)

**Comment by iamdelickkk** [comment]
![image](https://github.com/openvk/openvk/assets/91693467/00b5db14-ac6a-408a-887c-ba94555a1ead)
