### ISSUE TITLE
ВКонтакте блокирует ссылки на OpenVK

### ISSUE THREAD

**Issue by EgorKuzevanov** [OpenVK/openvk#1070]
Почему ВКонтакте блокирует абсолютно любые ссылки на OpenVK?:
![Безымянный](https://github.com/openvk/openvk/assets/78859951/f0f35892-8311-4495-8a68-7ea1db5feda5)

**Comment by saursvepur** [comment]
.uk/.xyz он не блочит

**Comment by celestora** [comment]
Потому что они долбоёбы

**Comment by Lumaeris** [comment]
Одно из двух: либо домен был внесён ввиду существования одноимённого проекта, адрес которого я не буду публиковать, либо домен был внесён ввиду нарушения авторских прав VK Group (по этой же причине нам отклонили заявку добавления мобильного приложения в RuStore).

**Comment by nbt1248** [comment]
Хз у меня всё нормально
EDIT: пруфы: https://vk.com/wall580688498_11

**Comment by NoPlagiarism** [comment]
***Туториал: Как следует забить хуй на `vk.com/away.php`***

### Метод 1
Не пользоваться ВК

### Метод 2
Использовать userscript вроде [этого](https://greasyfork.org/en/scripts/463408-direct-link)

### Метод 3
Использовать расширение "Skip Redirect", но требует настройки (решайте сами как настраивать): https://github.com/sblask/webextension-skip-redirect

### Метод 4
Вроде как в [VKOpt](https://vkopt.net) и [VKNext](https://vknext.net) был обход away.php

### Метод 5
Удалить ВК

**Comment by nbt1248** [comment]
> _**Туториал: Как следует забить хуй на `vk.com/away.php`**_
> 
> ### Метод 1
> Не пользоваться ВК
> 
> ### Метод 2
> Использовать userscript вроде [этого](https://greasyfork.org/en/scripts/463408-direct-link)
> 
> ### Метод 3
> Использовать расширение "Skip Redirect", но требует настройки (решайте сами как настраивать): https://github.com/sblask/webextension-skip-redirect
> 
> ### Метод 4
> Вроде как в [VKOpt](https://vkopt.net) был обход away.php
> 
> ### Метод 5
> Удалить ВК

Первый и последний методы лучшие

**Comment by celestora** [comment]
закрыто по причине не относится к движку
