### ISSUE TITLE
VKAPI: Тип `lyrics` в методе `Audio.get` отличается от веб-версии

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#1078]
По идее в APIшке переменная `lyrics` должна показывать текст песни, но вместо текста я здесь вижу какое-то число. Вот для сравнения приложу два скриншота.

![SCR_20240102_155223_firefox](https://github.com/openvk/openvk/assets/76806170/74681ba4-ce89-4f3c-a775-422df5cc54c4)

![изображение](https://github.com/openvk/openvk/assets/76806170/b3425658-8de4-45dd-9275-1a8f8a0517c5)

**Comment by iamdelickkk** [comment]
мы поем числами, привыкай

**Comment by tretdm** [comment]
![изображение](https://github.com/openvk/openvk/assets/76806170/654c523e-91d2-4218-a839-803797beffb2)

Мне кажется или просто изначально не было такого, чтобы можно было сразу выводить текст песни? Наверное.
