### ISSUE TITLE
https://ovk.to не работает в браузере Google Chrome 49.0.2623.112 (2016 года выпуска) под Windows XP SP3

### ISSUE THREAD

**Issue by EgorKuzevanov** [OpenVK/openvk#1086]
Из-за бесплатного тарифного плана Cloudflare https://ovk.to не открывается в браузере Google Chrome 49.0.2623.112 (2016 года выпуска) под Windows XP SP3 и выдает ошибку "На сайте ovk.to используется неподдерживаемый протокол".

**Comment by nikita232f** [comment]
обновлял сертификаты?

**Comment by EgorKuzevanov** [comment]
> обновлял сертификаты?

Не помогли ни обновление корневых сертификатов с помощью утилиты Cert Updater v1.6, ни даже параметр командной строки `--ignore-certificate-errors` в свойствах ярлыка Google Chrome 49. По-прежнему выскакивает ошибка "На сайте ovk.to используется неподдерживаемый протокол" из-за ненавистного мной Cloudflare.

**Comment by iamdelickkk** [comment]
о существовании mypal никто не знает

**Comment by nikita232f** [comment]
> > обновлял сертификаты?
> 
> Не помогли ни обновление корневых сертификатов с помощью утилиты Cert Updater v1.6, ни даже параметр командной строки `--ignore-certificate-errors` в свойствах ярлыка Google Chrome 49. По-прежнему выскакивает ошибка "На сайте ovk.to используется неподдерживаемый протокол".

Юзай mypal или supermium 121

**Comment by saursvepur** [comment]
> > обновлял сертификаты?
> 
> Не помогли ни обновление корневых сертификатов с помощью утилиты Cert Updater v1.6, ни даже параметр командной строки `--ignore-certificate-errors` в свойствах ярлыка Google Chrome 49. По-прежнему выскакивает ошибка "На сайте ovk.to используется неподдерживаемый протокол" из-за ненавистного мной Cloudflare.

openvk.xyz в помощь

**Comment by nikita232f** [comment]
> > > обновлял сертификаты?
> > 
> > 
> > Не помогли ни обновление корневых сертификатов с помощью утилиты Cert Updater v1.6, ни даже параметр командной строки `--ignore-certificate-errors` в свойствах ярлыка Google Chrome 49. По-прежнему выскакивает ошибка "На сайте ovk.to используется неподдерживаемый протокол" из-за ненавистного мной Cloudflare.
> 
> openvk.xyz в помощь

да кстати

**Comment by veselcraft** [comment]
привет!

не вижу смысла сейчас пользоваться старым хромогом, рекомендую

* пересесть на mypal 68, менее актуальный, но рабочий: https://github.com/Feodor2/Mypal68/releases
* пересесть на более актуальный хромог 115 версии: https://github.com/weolar/xpchrome/releases

увы ни мы ни кто уже не поддерживает 49-ю версию

**Comment by AAlx0451** [comment]
А Supermium 121 для тебя шутка?

**Comment by AAlx0451** [comment]
> * пересесть на mypal 68, менее актуальный, но рабочий: https://github.com/Feodor2/Mypal68/releases
> * пересесть на более актуальный хромог 115 версии: https://github.com/weolar/xpchrome/releases
Актуальный - громко сказано (mypal)
Плохо работает, даже требовательный Supermium лучше работает (M115)

**Comment by veselcraft** [comment]
> По-прежнему выскакивает ошибка "На сайте ovk.to используется неподдерживаемый протокол" из-за ненавистного мной Cloudflare.

дело не в сертификате, а в стандарте TLS 1.3. старенький хромог в такое не умеет, максимум 1.2. Поэтому обновить браузер стоит

**Comment by veselcraft** [comment]
> * Актуальный - громко сказано (mypal)
>       Плохо работает, даже требовательный Supermium лучше работает (M115)

ну не знаю, шо то работает, шо это

**Comment by AAlx0451** [comment]
> > * Актуальный - громко сказано (mypal)
> >   Плохо работает, даже требовательный Supermium лучше работает (M115)
> 
> ну не знаю, шо то работает, шо это

Ты же в @legacywindows есть, что не посмотришь?

**Comment by EgorKuzevanov** [comment]
> дело не в сертификате, а в стандарте TLS 1.3. старенький хромог в такое не умеет, максимум 1.2. Поэтому обновить браузер стоит

**veselcraft**, если уж на то пошло, то и другие хостящиеся за Cloudflare сайты, включая RuTracker.org, NNM-Club, 4PDA и SourceForge.net, поддерживают только TLS 1.3 и не поддерживают TLS 1.2.
