### ISSUE TITLE
Заливка файлов в OpenVK

### ISSUE THREAD

**Issue by EgorKuzevanov** [OpenVK/openvk#1087]
Предлагаю добавить в OpenVK возможность заливки на личные страницы и в сообщества файлов размером не более 800 МБ (в том числе с описаниями), как на файлообменнике [DowngradeFiles](http://downgradefiles.pdp-11.ru), а также возможность их прикрепления к постам, комментариям, обсуждениям и сообщениям. Также, в отличие от оригинального ВКонтакте, в OpenVK должны быть добавлены возможность заливки исполняемых файлов и (во избежание нанесения вреда OpenVK) их проверка на вирусы с помощью VirusTotal API.

**Comment by tretdm** [comment]
> Также, в отличие от оригинального ВКонтакте, в OpenVK должны быть добавлены возможность заливки исполняемых файлов

чтобы потом пиратки с варезами заливать, да? ага конечно...

давно не жаловались dmca-страйками я так скажу

**Comment by EgorKuzevanov** [comment]
> чтобы потом пиратки с варезами заливать, да? ага конечно...

Я вообще-то хочу заливать в OpenVK софт, совместимый со старыми версиями Windows (Windows 95, Windows 98, Windows ME, Windows NT 4.0, Windows 2000, Windows XP, Windows Server 2003, Windows Vista, Windows 7, Windows 8, Windows 8.1, Windows 10 LTSB 2015/2016). На случай, если сайты https://archive.org, https://web.archive.org, http://old-dos.ru и http://downgradefiles.pdp-11.ru перестанут существовать, либо их в очередной раз за-DDoS-ят или их заблокирует Роскомнадзор.

**Comment by tretdm** [comment]
ну так заведи свой сервер на каком-нибудь хостинге (главное, чтобы было недорого) и заливай все что ты хочешь

**Comment by tretdm** [comment]
в таймвебе самый дешёвый сервак из Новосиба стоит 177 рублей в месяц

**Comment by EgorKuzevanov** [comment]
> ну так заведи свой сервер на каком-нибудь хостинге (главное, чтобы было недорого) и заливай все что ты хочешь

У меня нет денег на платный хостинг. А на бесплатных хостингах по типу uCoz сайты никогда не живут вечно и в случае длительной неактивности удаляются навсегда вместе со всеми залитыми туда файлами.

**Comment by tretdm** [comment]
> > ну так заведи свой сервер на каком-нибудь хостинге (главное, чтобы было недорого) и заливай все что ты хочешь
> 
> У меня нет денег на платный хостинг. А на бесплатных хостингах по типу uCoz сайты никогда не живут вечно и в случае длительной неактивности удаляются безвозвратно вместе со всеми залитыми туда файлами.

ну тогда жаль, вам придётся обращаться не к нам, а к ребятам из [НДР](http://narodweb.ru), и то если их файлообменник будет готов.

**Comment by tretdm** [comment]
и посмотрите этот issue https://github.com/openvk/openvk/issues/193
