### ISSUE TITLE
Подскажите, как пожаловаться на сайт?

### ISSUE THREAD

**Issue by IrinaChebotareva** [OpenVK/openvk#1097]
Некий персонаж слил персональные данные в свое облако типа username.github.io?

**Comment by celestora** [comment]
Мне правда интересно, а почему вы решили по этому поводу написать в репозиторий опенвк?

Но вообще, зайдите на его страничку github.com/username, нажмите репорт и составьте жалобу, чо:
![image](https://github.com/openvk/openvk/assets/34442450/0f049839-d2f4-483a-b4d7-14c24797345c)

**Comment by IrinaChebotareva** [comment]
Благодарю! Просто не знала, куда.

**Comment by veselcraft** [comment]
Думаю вопрос исчерпан, тем более это оффтоп
