### ISSUE TITLE
Вкладка "разработчикам" кидает на старую страницу docs.openvk.uk вместо docs.ovk.to

### ISSUE THREAD

**Issue by nikita232f** [openvk/openvk#1099]
![firefox_6MB3kczRh2](https://github.com/openvk/openvk/assets/93428510/b93acb59-7013-4d3d-8b66-ef9ad35f65f2)
![firefox_oXQDoiHqDO](https://github.com/openvk/openvk/assets/93428510/95f5484e-43cf-41a3-8453-666601c8eb88)

**Comment by NilitaLamb** [comment]
Да он прав cтрочка 148 находится вот такой код (код низу)
$this->redirect("https://docs.openvk.uk/");
Скажите разработчикам что есть проблема которая называется вкладка "разработчикам" кидает на старую страницу docs.openvk.uk вместо docs.ovk.to
как текст должен выглядеть?
вот так (текст низу)
разработчики есть проблема вот как называется проблема (проблема низу)
Вкладка "разработчикам" кидает на старую страницу docs.openvk.uk вместо docs.ovk.to
https://github.com/openvk/openvk/issues/1099
строчка: 148
код: $this->redirect("https://docs.openvk.uk/");
проблема находится в Web/Presenters/AboutPresenter.php
конец текста
помощь от никиты бараша
