### ISSUE TITLE
Simpler date format

### ISSUE THREAD

**Issue by WerySkok** [openvk/openvk#11]
Date stamps here are unexplainably long and not localized. We need to simplify and adapt them. For example, instead of "11 January 2020 в 16:56:16" there should be "11 Jan at 16:56", if this happened this year. If this happened in other year, there should be "29 Dec 2019" instead of "29 December 2019 в 19:19:32" and so on.
I suggest providing detailed timestamp in ``title`` atribute.
# Упростить формат дат
Формат дат здесь необъяснимо длинный и не локализованый. Необходимо упростить и адаптировать их для других языков. Например, вместо «11 January 2020 в 16:56:16» должно быть «11 янв в 16:56», если это произошло в этом году. Если это произошло в другом году, то вместо «29 December 2019 в 19:19:32» должно быть «29 дек 2019» и так далее.
Подробные даты предлагаю указывать в атрибуте ``title``.

**Comment by fkwa** [comment]
Локализация есть, на тест инстансе нет русской локали просто 👍

**Comment by fkwa** [comment]
fixed
