### ISSUE TITLE
новые функции

### ISSUE THREAD

**Issue by NilitaLamb** [OpenVK/openvk#1104]

**Comment by iamdelickkk** [comment]
че?

**Comment by nikita232f** [comment]
![Telegram_MMuzilx0zF](https://github.com/openvk/openvk/assets/93428510/0f065447-4ed3-4bfa-9e78-8f0d982e7f9b)

**Comment by iamdelickkk** [comment]
"видеозвонки" - зачем они? они сложны в реализации, да и тем более существует много сервисов с видеозвонками (skype, discord). Так и тем более, в старом вк не было видеозвонков

**Comment by IgordosDev** [comment]
> Так и тем более, в старом вк не было видеозвонков

Ярослав on the way умничать
https://vk.com/wall-2158488_333260

**Comment by celestora** [comment]
@iamdelickkk Были, их просто убрали потом(

**Comment by iamdelickkk** [comment]
> > Так и тем более, в старом вк не было видеозвонков
> 
> Ярослав on the way умничать https://vk.com/wall-2158488_333260

окей, ошибся. но всё равно мне кажется что функция будет бесполезной + сложной в реализации. я просто не понимаю смысла
