### ISSUE TITLE
[API]ошибка при создание поста

### ISSUE THREAD

**Issue by Ilya5412** [OpenVK/openvk#1106]
при создание поста если передать attachments=null, то сервер вернет ошибку, но соверно создаст пост.

![Снимок экрана 2024-04-09 в 17 04 21](https://github.com/openvk/openvk/assets/103600275/55f1a751-fa0d-4ed1-8daa-3a05882a2875)

**Comment by Ilya5412** [comment]
type:bug

**Comment by NoPlagiarism** [comment]
Я.. Я даже не могу назвать это полноценным дупликатом #1105
