### ISSUE TITLE
Поехавшая вёрстка при двух вложениях

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#1108]
Относится и к постам, и к комментариям. Примеры: <table><tr><td>Пост</td><td>
<img src="https://github.com/openvk/openvk/assets/69392185/2d076207-aacc-474f-a1d4-52ec243e0dbb"></td><td><a href="https://ovk.to/wall6670_576">Ссылка</a></td></tr><tr><td>Комментарий</td><td><img src="https://github.com/openvk/openvk/assets/69392185/34785459-7506-4397-b2de-04d14b81e028"></td><td><a href="https://ovk.to/wall-710_11?p=3#_comment42294">Ссылка</a></td></tr></table>
Возможно такое происходит ещё где более 2-ух вложений, проверить мне не на чем

**Comment by tretdm** [comment]
~~Можете пояснить, на каком браузере вы проверяете?~~

На Firefox аналогичная проблема с вёрсткой.

**Comment by IgordosDev** [comment]
Дубликат https://github.com/OpenVK/openvk/issues/1040
До этого не заметил, закрываю
