### ISSUE TITLE
новые функции

### ISSUE THREAD

**Issue by NilitaLamb** [OpenVK/openvk#1109]
**новые функции**

быстрые сообщения и мои желания
и если тебе написали кто-то сообщение то не обязательно нажимать кнопку F5
в интересы там будет любимые сайты и игры
<img src="https://i.imgur.com/hW9M9QI.png">
а для администраторы "Мои админы" и "Администрирование"
и будет тру видеозвонки

**Comment by Lumaeris** [comment]
Дубликат #1104.
