### ISSUE TITLE
Баги с личной информацией у страницы

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#111]
Когда пытаюсь изменить каким либо образом личную информацию _(интересы, о себе, любимая музыка и т.д.)_, весь текст в ней заменяется на нули и единицы. Для проверки [вот моя страничка](https://openvk.su/md), если нужно будет могу предоставить пруфы в виде скриншотов и видео.

Ещё такую же проблему нашёл [здесь](https://openvk.su/kensoi) (у человека нули в личной информации).

**Comment by rudzik8** [comment]
как я вижу, веселкрафт этот баг уже обозначил. извиняюсь, это походу дубликат, закрываю

**Comment by veselcraft** [comment]
Закрываю проблему из-за копии (#121)
