### ISSUE TITLE
Возможность закреплять посты в группах и на страницах пользователей

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#112]
Эта функция была бы крайне полезна. Возможно её не было в старом VK, но мне как админу группы это бы пригодилось (да и я думаю что другим админам тоже). Я даже сделал небольшой концептик как это может выглядеть:
![Screenshot_2](https://user-images.githubusercontent.com/87843378/133549839-24105b7e-e303-411c-b0db-49ffc9fa510e.png)

**Comment by dsrev** [comment]
https://github.com/openvk/openvk/commit/839594cd70f1ffdb68c4271bcaf10692fc96e215
