### ISSUE TITLE
Трансляции в OpenVK

### ISSUE THREAD

**Issue by maksdq** [OpenVK/openvk#1120]
Предлагаю сделать прямые трансляции в OpenVK. Всё, мне больше нечего сказать....

**Comment by saursvepur** [comment]
ты ёбнутый чтоль? нахуй они нужны?

**Comment by koke228666** [comment]
овк клипы

**Comment by iamdelickkk** [comment]
я не вижу смысла потому что ими никто пользоваться не будет

**Comment by maksdq** [comment]
Короче, нахуй они нужны
