### ISSUE TITLE
Ошибка при установке через docker-compose

### ISSUE THREAD

**Issue by yumnycheesecakes** [OpenVK/openvk#1124]
![image](https://github.com/user-attachments/assets/376a00e7-4b91-474a-968e-4e7f1cebb700)

**Comment by WerySkok** [comment]
Относительно файла `docker-compose.yml` должны находиться файлы `chandler.yml` и `openvk.yml`, их образцы для докера можно найти в той же папке, где и `docker-compose.yml` — `install/automated/docker/`

**Comment by WerySkok** [comment]
Напоминаю, что при копировании `chandler.yml` желательно сменить поле `secret`, сгенерировать новое значение можно при помощи:
```bash
cat /dev/random | tr -dc 'a-z0-9' | fold -w 128 | head -n 1
```

**Comment by WerySkok** [comment]
@TemaisgameNoobas, проблема решена?

**Comment by yumnycheesecakes** [comment]
Я попробую, когда вернусь домой

**Comment by yumnycheesecakes** [comment]
А внешная БД нужна?? Или она идёт в комплекте с docker-compose.yml??

**Comment by yumnycheesecakes** [comment]
> @TemaisgameNoobas, проблема решена?

Да, теперь всё работает.
