### ISSUE TITLE
Конфиг для NGINX

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#113]
Ну тут всё очевидно. Ждём поддержку nginx

**Comment by ghost** [comment]
@WerySkok Скрипт напишу сегодня.

**Comment by ghost** [comment]
Заметил, что .htaccess находится в репозитории libchandler, поэтому мне необходимо написать конфиг не только для OVK.

**Comment by veselcraft** [comment]
@dsrev Мне кажется, что NGINX конфиг нужен только для chandler, серверу достаточно всего лишь все запросы направлять на index.php, тот что в chandler/htdocs

**Comment by ghost** [comment]
Теперь доступен новый [конфиг для nginx](https://github.com/openvk/chandler/blob/master/install/nginx.conf)! Необязательно использовать только Apache.

Теперь немного про сам конфиг:

### Установка
Необходимо переименовать файл конфига (например, `openvk.conf`), переместить в папку `/etc/nginx/sites-available` и сделать симлинк на `/etc/nginx/sites-enabled`. При необходимости проверить конфигурацию с помощью `nginx -t`. Затем просто перезапустить веб-сервер.

### Настройка
`domain.tld` заменяете на ваш домен. Можно использовать поддомены и `localhost`.

`/opt/chandler/htdocs` заменяете на путь установки [libchandler](https://github.com/openvk/chandler/) + `/htdocs` (например, `/var/www/ovk/chandler/htdocs`).

`/path/to/fullchain.pem` и `/path/to/privkey.pem`, соответственно, на ваши SSL сертификат и ключ вашего сайта (необязательно, если не использовать TLS, читайте следующую секцию).

Больше менять ничего не нужно. Самое главное - установить и настроить PHP-FPM.

### TLS
Использование TLS - рекомендуется. Сам конфиг настроен так, чтобы сайт использовал протокол HTTPS по умолчанию, а HTTP автоматически делал редирект на HTTPS.

При желании можно использовать только HTTP, заменив в первом блоке `server`
```
listen 443 ssl http2;
listen [::]:443 ssl http2;
```
на
```
listen 80;
listen [::]:80;
```
, удалив данные строки
```
ssl_certificate /path/to/fullchain.pem;
ssl_certificate_key /path/to/privkey.pem;
```
и удалив второй блок `server`.
