### ISSUE TITLE
Добавление возможности перепривязки E-mail к аккаунту

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#114]
Когда мы регистрируем аккаунт в OpenVK, то введённая нами почта привязывается к аккаунту раз и навсегда. Без возможности её смены на актуальный адрес, вдруг что. 
Чтобы минимизировать "стучания" в поддержку по поводу смены E-mail и восстановления паролей (которых даже мы восстановить не можем, собственно), я требую сделать возможность смены основного E-mail к аккаунту, как минимум для корректности работы восстановления пароля и актуализации данных.

**Comment by shorann** [comment]
@myslivets +

**Comment by rudzik8** [comment]
@myslivets +

**Comment by maksalees** [comment]
Дубликат #63
