### ISSUE TITLE
Счётчик количества записей

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#115]
А где?
![browser_NXlRa49Adv](https://user-images.githubusercontent.com/60743585/133561466-b95cee62-b9f2-499d-8237-f86de4cb7cf6.png)

**Comment by ghost** [comment]
Ну я здесь =)). А где счетчик - хз.

**Comment by rudzik8** [comment]
реально, пропал нафик. на страничках есть а вот в группах нету

**Comment by ghost** [comment]
Исправлено этим коммитом - https://github.com/openvk/openvk/commit/fd555d3d614672313457387af6cd1a6423f3cfee.
