### ISSUE TITLE
An empty, unnecessary item in the community editing menu

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#1152]
The bug is reproduced in /club"community number"/edit
![image](https://github.com/user-attachments/assets/414789a6-0bb0-4892-9e32-a418544956b5)

**Comment by ayaaop** [comment]
не заreproduceился
![Screenshot_20241204_184748_io_github_forkmaintainers_iceraven_HomeActivity](https://github.com/user-attachments/assets/7ac1df87-b82d-480a-ad39-ea2d6a6e84b0)

**Comment by ghost** [comment]
блядь
