### ISSUE TITLE
HTTP Error 503.0 - Service Temporarily Unavailable Unknown database 'db'

### ISSUE THREAD

**Issue by gamma63** [OpenVK/openvk#1162]
Error estabilishing database connection: SQLSTATE[HY000] [1049] Unknown database 'db'
![image](https://github.com/user-attachments/assets/58706cff-3b96-482f-97ea-9104ff73c4af)
что делать?

**Comment by gamma63** [comment]
алсо при попытке создания бд под именем db всё крашит нафиг

**Comment by veselcraft** [comment]
Потому что надо туда импортировать всё, что идёт в директории Install и у chandler, и у OpenVK. Естественно вы ничего не увидите, если создадите пустую базу данных

**Comment by gamma63** [comment]
> Потому что надо туда импортировать всё, что идёт в директории Install и у chandler, и у OpenVK. Естественно вы ничего не увидите, если создадите пустую базу данных

Спасибо за ответ!

**Comment by matvey-mayner** [comment]
появилась ещё одна проблема https://github.com/OpenVK/openvk/issues/1163
