### ISSUE TITLE
Ват деля фук?

### ISSUE THREAD

**Issue by gamma63** [OpenVK/openvk#1163]
![image](https://github.com/user-attachments/assets/f5968e53-7cdc-4397-98c6-ca57e98c24f9)
Подскажите пожалуйста что делать

**Comment by veselcraft** [comment]
Версия PHP? Какая база данных (MariaDB, Percona)?

**Comment by gamma63** [comment]
> Версия PHP? Какая база данных (MariaDB, Percona)?

PHP 8.3, Percona

**Comment by gamma63** [comment]
А ещё контекст:
Это произошло как только я написал пост на стене, без дебага был Server Error 500

**Comment by gamma63** [comment]
> А ещё контекст: Это произошло как только я написал пост на стене, без дебага был Server Error 500

При этом остальная часть соц. сети работала (кроме фида разве что)

**Comment by gamma63** [comment]
> > А ещё контекст: Это произошло как только я написал пост на стене, без дебага был Server Error 500
> 
> При этом остальная часть соц. сети работала (кроме фида разве что)

ну и профиля

**Comment by veselcraft** [comment]
> > Версия PHP? Какая база данных (MariaDB, Percona)?
> 
> PHP 8.3, Percona

Перкону не рекомендую - она выдаёт такие приколы. Лучше используйте MariaDB

С пыхой все нормально

**Comment by gamma63** [comment]
> > > Версия PHP? Какая база данных (MariaDB, Percona)?
> > 
> > PHP 8.3, Percona
> 
> Перкону не рекомендую - она выдаёт такие приколы. Лучше используйте MariaDB
> 
> С пыхой все нормально

Хорошо сейчас попробую MariaDB

**Comment by gamma63** [comment]
![image](https://github.com/user-attachments/assets/41ddbc47-1436-4f01-9ed8-d88deaadc4bb)
Теперь другая проблема :-(
И да selinux у меня выключен

**Comment by gamma63** [comment]
> ![image](https://private-user-images.githubusercontent.com/174414990/391316350-41ddbc47-1436-4f01-9ed8-d88deaadc4bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNDQwMjUsIm5iZiI6MTczMzA0MzcyNSwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzE2MzUwLTQxZGRiYzQ3LTE0MzYtNGYwMS05ZWQ4LWQ4OGRlYWFkYzRiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQwOTAyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDM4YTViYmI5OTY4MmJlZWJhY2IxOGRhM2UwMzA2YTRiYjMwOWU4YTRlYWE4ZDgxMmVmM2ExYjk3NjYzNjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PkSqwpkb4vx4bCZMtNIRs4Drd1FE3hMzMg02UBa7NRE) Теперь другая проблема :-( И да selinux у меня выключен

Пофиксил но теперь другая проблема
![image](https://github.com/user-attachments/assets/45f0fdde-f52d-46e5-bd2e-f103c728658d)
Опять же selinux отключен

**Comment by gamma63** [comment]
> > ![image](https://private-user-images.githubusercontent.com/174414990/391316350-41ddbc47-1436-4f01-9ed8-d88deaadc4bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNDQwMjUsIm5iZiI6MTczMzA0MzcyNSwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzE2MzUwLTQxZGRiYzQ3LTE0MzYtNGYwMS05ZWQ4LWQ4OGRlYWFkYzRiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQwOTAyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDM4YTViYmI5OTY4MmJlZWJhY2IxOGRhM2UwMzA2YTRiYjMwOWU4YTRlYWE4ZDgxMmVmM2ExYjk3NjYzNjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PkSqwpkb4vx4bCZMtNIRs4Drd1FE3hMzMg02UBa7NRE) Теперь другая проблема :-( И да selinux у меня выключен
> 
> Пофиксил но теперь другая проблема ![image](https://private-user-images.githubusercontent.com/174414990/391317397-45f0fdde-f52d-46e5-bd2e-f103c728658d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNDc3MzksIm5iZiI6MTczMzA0NzQzOSwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzE3Mzk3LTQ1ZjBmZGRlLWY1MmQtNDZlNS1iZDJlLWYxMDNjNzI4NjU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMDAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGZmNTU4YTRiZGU2ODJkOTJhYjNjMzhkNGQ4NzU2N2UzMTQ4MzM3YTI3ODBhNjcyNmU2NmIxYzQxNmExMzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ni0RIlxHSwv0lnEjtJ4VIxWVkOOoLTG-hUnSmASH-dw) Опять же selinux отключен

Исправил я ошибку 503 через команду chown -R mysql: * в /opt/chandler

**Comment by gamma63** [comment]
думаю попробую сейчас postgresql

**Comment by gamma63** [comment]
попробую использовать коммит как в ovk.to

**Comment by gamma63** [comment]
![image](https://github.com/user-attachments/assets/478b7d9f-72ad-4e70-8454-5f2f622a0b0e)
Итак вроде бы всё работает, но таже проблема как и раньше (да я использовал mariadb)

**Comment by gamma63** [comment]
> ![image](https://private-user-images.githubusercontent.com/174414990/391329811-478b7d9f-72ad-4e70-8454-5f2f622a0b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQ4MzYsIm5iZiI6MTczMzA1NDUzNiwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzI5ODExLTQ3OGI3ZDlmLTcyYWQtNGU3MC04NDU0LTVmMmY2MjJhMGIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTcwZjY4YmQxOGRiYjA3ZjZmMzMyMzk0MWYyZDFkMzJmNDY5OGM2NWVhNzUyOWE3Y2UzYzVjY2ViYzViNGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CQaQ0B0__mh_adjoem4LInhNeJg2i0Cm3zkhyq4GE6A) Итак вроде бы всё работает, но таже проблема как и раньше (да я использовал mariadb)

![image](https://github.com/user-attachments/assets/f25b30ac-c546-4815-9b9d-3a8a7d0b6342)
с дебагом

**Comment by gamma63** [comment]
> > ![image](https://private-user-images.githubusercontent.com/174414990/391329811-478b7d9f-72ad-4e70-8454-5f2f622a0b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQ4MzYsIm5iZiI6MTczMzA1NDUzNiwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzI5ODExLTQ3OGI3ZDlmLTcyYWQtNGU3MC04NDU0LTVmMmY2MjJhMGIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTcwZjY4YmQxOGRiYjA3ZjZmMzMyMzk0MWYyZDFkMzJmNDY5OGM2NWVhNzUyOWE3Y2UzYzVjY2ViYzViNGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CQaQ0B0__mh_adjoem4LInhNeJg2i0Cm3zkhyq4GE6A) Итак вроде бы всё работает, но таже проблема как и раньше (да я использовал mariadb)
> 
> ![image](https://private-user-images.githubusercontent.com/174414990/391329940-f25b30ac-c546-4815-9b9d-3a8a7d0b6342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTQ5NjgsIm5iZiI6MTczMzA1NDY2OCwicGF0aCI6Ii8xNzQ0MTQ5OTAvMzkxMzI5OTQwLWYyNWIzMGFjLWM1NDYtNDgxNS05YjlkLTNhOGE3ZDBiNjM0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjA0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGNiMmMxMTcwOTg0NzY0MzQwZjNkODUxYmIzY2M1YzlkZTllNzdkOTRkYWJkYzcxZTY5YTkyMzE2MDUzY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RoiXPcVjgukV9HwMRbO9f6yENYeGv3RgA3RUcSrgjFQ) с дебагом

![image](https://github.com/user-attachments/assets/f742e1b8-852e-4614-a134-0162cd1b36d9)
С дебагом + логином

**Comment by saursvepur** [comment]
you fuk

**Comment by gamma63** [comment]
> you fuk

ок

**Comment by gamma63** [comment]
Кажись я понял в чём проблема :P

**Comment by veselcraft** [comment]
> Кажись я понял в чём проблема :P

И как решил?

**Comment by TYMA22389** [comment]
я помню у меня такая же брехня была, тут лотерея, либо у тебя он нормально пашет либо с багами, не парься и переустанови, а фид и посты я уже не помню как чинил(я рыбка)

**Comment by gamma63** [comment]
> я помню у меня такая же брехня была, тут лотерея, либо у тебя он нормально пашет либо с багами, не парься и переустанови, а фид и посты я уже не помню как чинил(я рыбка)

Я уже переустановил с перконой и поставил там специальный режим забыл какой, и всё пашет

**Comment by gamma63** [comment]
> > Кажись я понял в чём проблема :P
> 
> И как решил?

см. моё сообщение выше
