### ISSUE TITLE
Можливість розширювати інформацію та засоби комунікації

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#1165]
Я вважаю, що не слід обмежувати користувачів у виражені їхнього багатогранного внутрішнього світу та засобів зв’язку, і тому пропоную додати розширити інформацію про себе та контакти зв’язку

Для чого?
В теорії користувачі можуть отримувати більше інформації від людини, якщо вона більше висловила про себе.

Якщо людина зазначила, що вона любить грати в S.T.A.L.K.E.R Shadow of Chornobyl, то можна запросити її пограти онлайн або запросити на сервер

Так само із засобами комунікації: можна зазначити акаунт в Steam, Signal, Discord... Або Instagram, щоб його курва шляк би трафив сука дідько

![зображення](https://github.com/user-attachments/assets/56099491-17a6-4e5d-b519-6151307694f8)

**Comment by NoPlagiarism** [comment]
>Я вважаю, що не слід обмежувати користувачів у виражені їхнього багатогранного внутрішнього світу та засобів зв’язку, і тому пропоную додати розширити інформацію про себе та контакти зв’язку

Лайфхак: используем окошко `Про себе`, чтобы оставить основную контактную информацию. Либо списываемся в лс и добываем контакты там. А ещё можно указать ссылку на дс профиль как персональный сайт. А ещё можно оставить закреп. А ещё можно использовать сервисы вроде linktr.ee

Насчёт доп инфы в принципе... Разве не для этого нужно "О себе"?

А вот насчёт доп. контактов - звучит интересно, особенно если реализовать это в предназначенной для этого вкладке

**Comment by ghost** [comment]
>Насчёт доп инфы в принципе... Разве не для этого нужно "О себе"?

Дело стиля. 
Допустим, в "О себе" я напишу краткое описание себя, то есть "23-летний художник из Харькова", а в остальные формы то, что соответствует названию.

**Comment by NoPlagiarism** [comment]
Ну всё равно есть ощущение, что контакты стоит оставить в кладке контакты
