### ISSUE TITLE
Слово "Редактировать" написано с маленькой буквы

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#117]
хотя должно быть написано с большой
эту кнопку видно при открытии своего видео

![Screenshot_1](https://user-images.githubusercontent.com/87843378/133592566-bc2c6b6b-71d4-445f-89b0-c7a9ae0f9703.png)

**Comment by WerySkok** [comment]
пятиминутное дело, ждём, когда люди с правом записи в репозиторий поправят
https://github.com/openvk/openvk/blob/272c2493d8da7be7864035aaf5223197e0544a18/locales/ru.strings#L20

**Comment by shorann** [comment]
@WerySkok

**Comment by rudzik8** [comment]
ждём, действительно

**Comment by dsrev** [comment]
Ладно.
