### ISSUE TITLE
Не меняется параметр "Список админов"

### ISSUE THREAD

**Issue by Leaf621** [OpenVK/openvk#1172]
https://github.com/user-attachments/assets/8fdefcb2-58ca-4df5-92b2-270b0f7ea1f4

При попытки поменять параметр он сбрасывается до "Отображать только создателя группы"

**Comment by ghost** [comment]
![зображення](https://github.com/user-attachments/assets/ca39e2a7-692b-4b41-a245-c82793b7b31c)
Та блядь, цей йобаний баг то є, то немає
