### ISSUE TITLE
Локализация даты рождения

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#118]
Стоит русский язык, Google Chrome

![image](https://user-images.githubusercontent.com/22106304/133751212-397242fe-98d5-4495-b7df-c129a017d5c4.png)

**Comment by veselcraft** [comment]
Либо это приколы нашего инстанса, либо кто то неверно реализовал отображение даты

**Comment by veselcraft** [comment]
> Либо это приколы нашего инстанса, либо кто то неверно реализовал отображение даты

Оказалось, что правильным был второй вариант - @VladimirLapskiy решил не разбираться в реализации других функций и решил не выводить объект `DateTime`

**Comment by mbs0ft** [comment]
:trollface:

**Comment by zavolo** [comment]
@veselcraft Поставьте русскую локаль!!!!

**Comment by vlapskii** [comment]
> > Либо это приколы нашего инстанса, либо кто то неверно реализовал отображение даты
> 
> Оказалось, что правильным был второй вариант - @vladimirlapskiy решил не разбираться в реализации других функций и решил не выводить объект `DateTime`

![image](https://user-images.githubusercontent.com/94683384/146240749-30925d74-8ff0-4f60-b585-9ba43dfe9026.png)
