### ISSUE TITLE
Move apache config files for automated installation

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#12]
Apache's configs are distro-specific, so files `httpd.conf` and `httpd-php.conf` which are configured to FreeBSD only should be moved from `openvk/install/automated/common/` to `openvk/install/automated/freebsd-12/`.

**Comment by wedytd** [comment]
nice

**Comment by veselcraft** [comment]
@WerySkok it is actual? If not, i'll close issue

**Comment by WerySkok** [comment]
С тех пор как туториал есть, уже нет
