### ISSUE TITLE
Новый интерфейс выбора языка

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#120]
По приколу сделал новый интерфейс выбора языка. Прошу на оценку.
Как по мне, флаги нужно переделать и сделать в больших размерах, так будет красивее :з

CSS: 
```
.navigation .link_new {
    display: inline-block;
    padding: 25px 25px 20px 25px;
    text-decoration: none;
    border-top: 1px solid #fff;
    color: #000;
    border-bottom: 0;
    border-left: 0;
    border-right: 0;
    font-size: 11px;
    text-align: left;
    cursor: pointer;
    background: none;
    margin-bottom: 1px;
}

.navigation .link_new:hover {
    background-color: #E4E4E4;
    border-top: 1px solid #CCCCCC;
}
```

HTML:
`
<a href="language?lg={lg}" class="link_new"><center><img src="/assets/packages/static/openvk/img/flags/{lgpic}.gif"></center><br> {lang_name}</a>
`

Скриншот нового интерфейса:

![browser_7YaiAf3i1T](https://user-images.githubusercontent.com/60743585/133756855-dac38159-80a5-49a6-9a69-c8f90043886c.png)

**Comment by celestora** [comment]
Мило. Не хотите сделать pull request?

**Comment by mbs0ft** [comment]
@myslivets а не слишком большое расстояние между кнопками?

**Comment by myslivets** [comment]
> @myslivets а не слишком большое расстояние между кнопками?
Нормально

![browser_1amaVz3Uqn](https://user-images.githubusercontent.com/60743585/133757746-01f317f7-4c34-4a45-9329-5cb64a1abce1.png)

**Comment by mbs0ft** [comment]
@myslivets понял

**Comment by rudzik8** [comment]
@myslivets +1, хотим хотим

**Comment by WerySkok** [comment]
Не хватает ссылки на Crowdin

**Comment by ghost** [comment]
> 
> 
> Не хватает ссылки на Crowdin

Он не настроен должным образом. Когда всё настроят - вставим ссылку на него.

**Comment by veselcraft** [comment]
> Мило. Не хотите сделать pull request?

Бамп

**Comment by ghost** [comment]
> > Не хватает ссылки на Crowdin
> 
> Он не настроен должным образом. Когда всё настроят - вставим ссылку на него.

Где? :Р
