### ISSUE TITLE
При смене интересов, всё заменяется на цифры

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#121]
Решил короче поменять текст о своих интересах, но вот такой прикол: любая смена описания приводит к одному тексту, убрать также нельзя, меняются только значения с 0 на 1. ![roflanEbalo](https://cdn.discordapp.com/emojis/860906000240476160.png?size=32)
![До смены](https://cdn.discordapp.com/attachments/863356751897296896/888382036895731722/chrome_6stCkTA6mt.png)
↳ До смены текста
![После](https://cdn.discordapp.com/attachments/863356751897296896/888382102230425680/chrome_fH5CgYGIRg.png)
↳ После
![image](https://cdn.discordapp.com/attachments/863356751897296896/888383282629206036/chrome_Di3uxbaGva.png)
↳ Если попытаться сохранить значения пустыми

**Comment by mbs0ft** [comment]
@IgordosDev уже знают о проблеме

**Comment by veselcraft** [comment]
dddeeb9d72bbc68ddb9066de3c4746f322f16271
