### ISSUE TITLE
Баг с темой ВКонтакте 2015

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#124]
Если нажать на логотип - на долю секунды появляется логотип из темы 2012 версии. Причём только при одном нажатии.
![image](https://cdn.discordapp.com/attachments/863356751897296896/888489196677898320/144VHa1y7p.gif)
![image](https://cdn.discordapp.com/attachments/863356751897296896/888491827852869703/chrome_xhvsHHQDvK.png)

**Comment by veselcraft** [comment]
Это не наша тема, обращайтесь к https://t.me/defenders08k1

**Comment by WerySkok** [comment]
Разжую: темы не являются частью исходных кодов (а значит и этого репозитория), а упомянутая тема доступна только на основном сайте openvk.su. 
> defenders08k1

Автор данной темы прекратил её поддержку, но я посмотрю, что с этим можно сделать.
