### ISSUE TITLE
Частичный перевод элементов при другом языке кроме русского

### ISSUE THREAD

**Issue by moneyworldstar** [OpenVK/openvk#127]
![image](https://user-images.githubusercontent.com/90852312/133905948-24fa0c0a-9fce-40de-90e6-e2dfd9500c25.png)

**Comment by VladimirLapskiy-zz** [comment]
Ладно

**Comment by veselcraft** [comment]
Прохладно

**Comment by ghost** [comment]
Работаю над этим.

**Comment by ghost** [comment]
Перевод на английский язык был сделан с потерей контекста. К примеру, было бы правильнее перевести фразу «Здесь никто ничего не написал... Пока.» как “Nobody wrote anything here... So far.”

**Comment by ghost** [comment]
На данном скриншоте продемонстрированы баги скрипта, отвечающего за язык.
[![](https://user-images.githubusercontent.com/45205643/138610787-261bb7ae-a524-450f-b064-869c8bd7d871.png)](#)

**Comment by ghost** [comment]
> На данном скриншоте продемонстрированы баги скрипта, отвечающего за язык. [![](https://user-images.githubusercontent.com/45205643/138610787-261bb7ae-a524-450f-b064-869c8bd7d871.png)](#)

Исправлено в https://github.com/openvk/openvk/commit/2b1a147e9fb88186ac8a067e1b963e46ebae6569, если говорить про данную страницу

![image](https://user-images.githubusercontent.com/55238545/144735142-d3c8a34a-7bfc-4bb6-b364-f01a5729d41f.png)

![image](https://user-images.githubusercontent.com/55238545/144735146-1301a497-6bbf-42d3-b4a7-890d9a3970d2.png)

Однако мне всё еще предстоит исправить и добавить многое в локали...

**Comment by veselcraft** [comment]
Актуально? Если есть недопереводы, присылайте адрес и скриншот

**Comment by maksalees** [comment]
> Актуально? Если есть недопереводы, присылайте адрес и скриншот

Их много. Просто тыкни в любой Presenter и увидишь там кучу `flash` и `flashFail` с захардкоденным русским. Ну например в [GroupPresenter](https://github.com/openvk/openvk/blob/master/Web/Presenters/GroupPresenter.php) есть

**Comment by veselcraft** [comment]
Актуально?

**Comment by celestora** [comment]
Актуально

**Comment by veselcraft** [comment]
Понятно
