### ISSUE TITLE
После блокировки удаляются все друзья и группы

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#129]
не дико ли?

**Comment by celestora** [comment]
Нет, это фича такая

**Comment by ghost** [comment]
![IMG_20210914_134115_161.jpg](https://user-images.githubusercontent.com/55238545/133962072-8237c9e9-6bb4-4523-8c23-3c2d65aeff03.jpg)

**Comment by veselcraft** [comment]
![image](https://user-images.githubusercontent.com/22993408/133962491-1eaa1a60-5ede-4fd9-b036-a956800eb5e7.jpeg)
