### ISSUE TITLE
Функция игнорирования страницы

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#133]
Вроде бы сюда можно писать предложения, не знаю куда именно.

В общем просматривая все новости, иногда мне хочется закрыть ленту и уйти заняться другим делом. ![trollge](https://cdn.discordapp.com/emojis/835771503391014923.png?size=32)
Я бы хотел скрыть посты некоторых страниц, чтобы они мне не мешали просматривать обновления.
Вот концепт этого:
![слыш лошпедус, давно не нюхал бебруса?](https://cdn.discordapp.com/attachments/863356751897296896/889520874124877914/veselcraft_nuhai_bebru.png)

**Comment by IgordosDev** [comment]
а зачем я концепт делал, если итак всё понятно

**Comment by ghost** [comment]
По приколу может?

**Comment by IgordosDev** [comment]
Получается

**Comment by IgordosDev** [comment]
прошло 3 года нахуй
