### ISSUE TITLE
Средство модерации: ИИ

### ISSUE THREAD

**Issue by GeorgNation** [OpenVK/openvk#139]
Предлагаю добавить в возможности администрирования функционал искусственного интеллекта, определяющий какой либо объект из образцов и применяя действия. Будет полезно на случай интеграции новых возможностей. Также поможет в поиске запрещённого контента.

**Comment by celestora** [comment]
@GeorgNation Немезида момент)

**Comment by GeorgNation** [comment]
> @GeorgNation Немезида момент)

Полностью согласен!

**Comment by celestora** [comment]
@WerySkok closing as out of scope?

**Comment by celestora** [comment]
инпута от верискока нет но в принципе думаю эта фича нинужна, кф уже умеет сам в поиск ЦП по базам данных с алертами на почту, так что похуй
