### ISSUE TITLE
Средство модерации: аналог noSpam

### ISSUE THREAD

**Issue by GeorgNation** [OpenVK/openvk#140]
Аналог администраторской функции noSpam для поиска контента на сайте по специальному запросу и выполнения действия над ним.

**Comment by GeorgNation** [comment]
@GeorgNation ...

**Comment by celestora** [comment]
что

**Comment by veselcraft** [comment]
@celestora

**Comment by veselcraft** [comment]
![image](https://user-images.githubusercontent.com/22993408/134134258-e7ac1733-5069-4952-98c6-19a3a109e395.png)

**Comment by celestora** [comment]
@veselcraft

**Comment by n1rwana** [comment]
Видимо, речь про это

![image](https://user-images.githubusercontent.com/93197434/188329581-a93d820d-3369-4d96-8544-86f43ad15853.png)

**Comment by zavolo** [comment]
@n1rwana откуда у тебя столько скринов из админки вк

**Comment by veselcraft** [comment]
> @n1rwana откуда у тебя столько скринов из админки вк

Однажды в ВК случилась ржака, из-за которой у всех открылась админка. Вот в этом и секрет

**Comment by n1rwana** [comment]
> @n1rwana откуда у тебя столько скринов из админки вк

https://youtu.be/zf3KT9m3pgE

**Comment by zavolo** [comment]
@veselcraft Ну видос на ютубе я видел, ток она вроде не надолго открылась

**Comment by zavolo** [comment]
@n1rwana Интересно, такого не находил
