### ISSUE TITLE
Возможность удаления страницы

### ISSUE THREAD

**Issue by GeorgNation** [OpenVK/openvk#141]
Если человеку того нужно, то можно будет разрешить удаление страницы.

Работает так:
 - При нажатии на кнопку удалить можно описать причину которая попадет в ленте.
 - Перед началом самого процесса, страница пользователя будет заменена на страницу "Страница закрыта и больше недоступна".
 - После чего, данные страницы перемещаются в архив на временное хранение (в срок на 31 день).
 - После манипуляции, вместо страницы появляется страница "Такой страницы не существует." с кодом ошибки 410 Gone.
 - После того как срок хранения истечет, данные уничтожаются, а страница заменяется на DELETED с кодом 404.
 - Восстановить страницу вручную нельзя, только написав в поддержку.

Такой метод будет отпугивать пользователей покидать данную чудесную социальную сеть.

**Comment by veselcraft** [comment]
@GeorgNation Требую в релиз!

**Comment by GeorgNation** [comment]
> @GeorgNation Требую в релиз!

Я не разработчик ОпенВК и не знаю всех тонкостей. Намутили там что-то с вашими Чандлерами и так далее, и теперь в этом надо копаться.

**Comment by veselcraft** [comment]
@GeorgNation Не, это я знаю, просто поддержал реализацию этой функции. На меня уже существующие задачи висят))

**Comment by GeorgNation** [comment]
@veselcraft Зачем вообще общаться через GitHub напрямую? У вас же бот есть чтобы делать это!

**Comment by veselcraft** [comment]
@GeorgNation Да, только в этот раз я отвечаю через публичный чат ОВК в телеге, а не в беседе разработчиков (там тоже бот висит)

**Comment by GeorgNation** [comment]
@veselcraft @veselcraft Я понял, спасибо за то что дали понять!

**Comment by ghost** [comment]
>     * Восстановить страницу вручную нельзя, только написав в поддержку.
> 
> 
> Такой метод будет отпугивать пользователей покидать данную чудесную социальную сеть.

Это конечно круто, но засирать анкеты техподдержки - не вариант.

>     * После чего, данные страницы перемещаются в архив на временное хранение (в срок на 31 день).

Оригинальный ВК на восстановление аккаунта вообще выдаёт 7 месяцев. Хз какой срок выдавал классический ВК.

**Comment by GeorgNation** [comment]
> >     * Восстановить страницу вручную нельзя, только написав в поддержку.
> > 
> > 
> > Такой метод будет отпугивать пользователей покидать данную чудесную социальную сеть.
> 
> Это конечно круто, но засирать анкеты техподдержки - не вариант.
> 
> >     * После чего, данные страницы перемещаются в архив на временное хранение (в срок на 31 день).
> 
> Оригинальный ВК на восстановление аккаунта вообще выдаёт 7 месяцев. Хз какой срок выдавал классический ВК.

Ну значит 7 месяцев с предоставлением бэкапа после окончания срока.

**Comment by ghost** [comment]
Забавно, но ВК выдаёт ошибку HTTP 302 Found, когда пользователя не существует в принципе.

![image](https://user-images.githubusercontent.com/55238545/153539112-3206a378-b4fc-44c9-add3-081e268eb573.png)

**Comment by ghost** [comment]
Неважно, это вообще был редирект. А так он выводит 200 OK.
