### ISSUE TITLE
Поддержка PHP 8

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#145]
Не срочно, но необходимо в перспективе.

**Comment by ghost** [comment]
Сначала необходимо дождаться, когда все расширения libchandler и OVK обновятся и будут поддерживать PHP 8.

**Comment by semyon492** [comment]
@celestora в lfkeitel/phptotp v1.1.0 уже есть поддержка php8.0

**Comment by Lumaeris** [comment]
У нас есть время до 28 ноября*, чтобы успешно мигрировать на новую мажорную ветку PHP.

*https://www.php.net/supported-versions.php

**Comment by veselcraft** [comment]
кстати овк не работает на пыхе 8.1

**Comment by NoPlagiarism** [comment]
> кстати овк не работает на пыхе 8.1

[И вот напоминалка почему](https://github.com/openvk/openvk/labels/php%208.1%20cringe%20momentos%20number%20tres)

**Comment by stomarver** [comment]
Да бл закройте уже иссу

**Comment by tretdm** [comment]
Уже неактуально, потому что официальные инстанции OpenVK и так работают на PHP 8.2.
