### ISSUE TITLE
Баги и недороботки

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#146]
Я просто опишу некоторые вещи которые по моему мнению не закончены или недоработанны и так, приступим. 
**1. Нету других типов для группы: закрытый, по приглашению
2. Также нельзя ответить на комментарии или поделится этим комментарием
3. Нельзя прикрепить фотографию в личных сообщениях или в комментариях
4. Нельзя публиковать видео в комментариях, постах сообщества, личных сообщениях и т.д
5. Нет системы уведомления
6. Нельзя удалить комментарии в личных сообщениях**

**Comment by thejesterguyiguess** [comment]
короче это чисто я привел примеры

**Comment by thejesterguyiguess** [comment]
надеюсь пофиксят в будующем

**Comment by veselcraft** [comment]
Ух бля... Сделай для каждого пункта отдельный issue, то что ты сделал - неудобно для Kanban, но наличие проблем не отрицаем

**Comment by rudzik8** [comment]
2. что это вообще такое ты написал
3. уже давно лежит на гитхабе
4. для этого есть вкладка "подписчики"
6. ДА ПОТОМУ ЧТО ТУТ НЕТУ АУДИО

и да, с веселкрафтом полностью согласен.

**Comment by WerySkok** [comment]
@veselcraft, GitHub поддерживает галочки, отслеживающие прогресс выполнения, если что.

**Comment by ghost** [comment]
Здесь есть некоторые дубликаты.

В следующий раз проверяй, пожалуйста, на наличие тобою найденных багов на https://github.com/openvk/openvk/issues и https://github.com/openvk/openvk/projects/1 , ПОЖАЛУЙСТА. В случае создания дубликатов соответствующие issue будут закрываться.

**Comment by thejesterguyiguess** [comment]
> 2 пункт - что это вообще такое ты написал
> 3 пункт - уже давно лежит на гитхабе
> 4 пункт - для этого есть вкладка "подписчики"
> 6 пункт - ДА ПОТОМУ ЧТО ТУТ НЕТУ АУДИО
> 
> и да, с веселкрафтом полностью согласен.

я обновил список, если что извиняюсь за тупость

**Comment by thejesterguyiguess** [comment]
> 2 пункт - что это вообще такое ты написал
> 3 пункт - уже давно лежит на гитхабе
> 4 пункт - для этого есть вкладка "подписчики"
> 6 пункт - ДА ПОТОМУ ЧТО ТУТ НЕТУ АУДИО
> 
> и да, с веселкрафтом полностью согласен.

и еще я сказал это мое мнение

**Comment by ghost** [comment]
Опять же - делай issue для каждого отдельного бага/предложения.

**Comment by thejesterguyiguess** [comment]
> Опять же - делай issue для каждого отдельного бага/предложения.

ладно если я сейчас буду писать отдельный иссу каждые 5 минут это не будет считаться спамом или флудом?

**Comment by thejesterguyiguess** [comment]
> Опять же - делай issue для каждого отдельного бага/предложения.

ну а так я удаляю этот иссу

**Comment by ghost** [comment]
> 
> 
> > Опять же - делай issue для каждого отдельного бага/предложения.
> 
> ладно если я сейчас буду писать отдельный иссу каждые 5 минут это не будет считаться спамом или флудом?

Можешь просто скопировать и вставить то, что ты уже здесь написал. При этом не забывай про мою просьбу - https://github.com/openvk/openvk/issues/146#issuecomment-924752429
