### ISSUE TITLE
Отсутствующие функции для комментариев

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#148]
Поделится и ответить, а ну и еще добавление медиа

**Comment by rudzik8** [comment]
хотелось бы тогда вложения и в сообщениях, и в тикетах (хотя бы фото).
функция "поделиться" звучит спорно (как по мне), не думаю что она важна
ответы на комментарии тоже очень даже неплохая идея

вот только это опять issue с подпунктами. так делать очень нежелательно

**Comment by thejesterguyiguess** [comment]
> функция "поделиться" для комменатриев звучит спорно (как по мне), не думаю что она важна
> хотелось бы тогда вложения и в сообщениях, и в тикетах (хотя бы фото)
> ответы на комментарии тоже очень даже неплохая идея
> 
> вот только это опять issue с подпунктами. так делать очень нежелательно

просто я смотрел старые фото вк 2008 года, где там есть кнопка поделится, ну и хотелось бы чтобы все функции из старого вк был на этом сайте

**Comment by thejesterguyiguess** [comment]
> функция "поделиться" для комменатриев звучит спорно (как по мне), не думаю что она важна
> хотелось бы тогда вложения и в сообщениях, и в тикетах (хотя бы фото)
> ответы на комментарии тоже очень даже неплохая идея
> 
> вот только это опять issue с подпунктами. так делать очень нежелательно

почему бы и нет

**Comment by rudzik8** [comment]
> почему бы и нет

на что конкретно вы ответили?

> просто я смотрел старые фото вк 2008 года, где там есть кнопка поделится, ну и хотелось бы чтобы все функции из старого вк был на этом сайте
вот только "поделиться" для фото и "поделиться" для комментариев это разные вещи

**Comment by thejesterguyiguess** [comment]
> > почему бы и нет
> 
> на что конкретно вы ответили?
> 
> > просто я смотрел старые фото вк 2008 года, где там есть кнопка поделится, ну и хотелось бы чтобы все функции из старого вк был на этом сайте
> 
> вот только "поделиться" для фото и "поделиться" для комментариев это разные вещи

поделится для комментарии

**Comment by rudzik8** [comment]
> поделится для комментарии

для меня лично очень спорная фича
