### ISSUE TITLE
Нет информации в некоторых разделах

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#15]
Не заполнены разделы Поддержать, вкладка Голоса в настройках
Не работают ссылки внизу страницы: Блог, Разработчикам 

![Screenshot 2020-12-15 at 19 19 16](https://user-images.githubusercontent.com/22106304/102249141-b2633100-3f0a-11eb-8272-a29cc5902f86.png)
![Screenshot 2020-12-15 at 19 18 06](https://user-images.githubusercontent.com/22106304/102249142-b2fbc780-3f0a-11eb-969f-e3fc63cac34d.png)
![Screenshot 2020-12-15 at 19 19 29](https://user-images.githubusercontent.com/22106304/102249120-ad9e7d00-3f0a-11eb-86b3-e5eb92ead267.png)

**Comment by veselcraft** [comment]
Это относится не к движку ОВК, а скорее к инстансу. Запросы по поводу незаполненной информации кидайте в техпод самого инстанса: https://openvk.su/support?act=new
