### ISSUE TITLE
Публикация видео в комментариях, личных сообщениях и т.д

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#150]

**Comment by rudzik8** [comment]
я думаю "Вложения в комментариях, постах сообщества, личных сообщениях и т.д" будет более корректным названием

**Comment by WerySkok** [comment]
Видео в постах покрыто в #56, по идее должно работать и в комментах, но там нужен фикс. Потом переименую только для личных сообщений

**Comment by veselcraft** [comment]
В комментариях работает 100%
