### ISSUE TITLE
Всплывающие уведомления

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#151]

**Comment by celestora** [comment]
@fg-ij Суп с чебупелями

**Comment by fg-ij** [comment]
> @fg-ij Суп с чебупелями

что

**Comment by rudzik8** [comment]
система уведомлений в овк уже есть

**Comment by celestora** [comment]
> > @fg-ij Суп с чебупелями
> 
> что

О какой именно сис-е идёт речь? У нас уже есть long polling в стиле ВК, уведомления в разделе "Мои ответы".

**Comment by ghost** [comment]
> 
> 
> система уведомлений в овк уже есть

Видимо здесь имеется в виду "Всплывающие уведомления".

**Comment by thejesterguyiguess** [comment]
> > система уведомлений в овк уже есть
> 
> Видимо здесь имеется в виду "Всплывающие уведомления".

да

**Comment by ghost** [comment]
Так и пиши. Система уведомлений у нас и так существует.

**Comment by rudzik8** [comment]
+1
можно ещё к ним прикрутить звук, например [такой](https://drive.google.com/file/d/1-Us-v-E5tbt9GNAZCxTkmQFnGG5mJ9ib/view?usp=sharing) (лицензия CC0, специально сохранил чтобы потом предложить)

**Comment by veselcraft** [comment]
Было добавлено в коммите https://github.com/openvk/openvk/commit/ffb8c6d5dfa44e0e1d0530f171bbc68e677e08ee
