### ISSUE TITLE
Аудиозаписи

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#152]
![Screenshot_9](https://user-images.githubusercontent.com/63295722/134324782-2c24fbea-2c16-4c17-bafd-2e15fcc8bfe7.png)

**Comment by rudzik8** [comment]
дубликат, уже есть [тут](https://github.com/openvk/openvk/projects/1)

**Comment by ghost** [comment]
> 
> 
> дубликат, уже есть [тут](https://github.com/openvk/openvk/projects/1)

В принципе да, но я это могу добавить в проект вместо существующей заметки.

**Comment by veselcraft** [comment]
дубль #512 

закрываю, ибо тут ничего по инфе нету, а пулл реквест с ранней реализацией музыки уже существует
