### ISSUE TITLE
Добавить счетчик

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#154]
![Screenshot_11](https://user-images.githubusercontent.com/63295722/134324905-7359abb4-01c1-45b2-be14-dfafe32d1508.png)
![Screenshot_12](https://user-images.githubusercontent.com/63295722/134324935-1a289735-1623-4ae6-a8b9-b3177f44130d.png)
![Screenshot_14](https://user-images.githubusercontent.com/63295722/134325058-04290ed1-a128-4840-9ce2-2ff76857e953.png)

**Comment by veselcraft** [comment]
Для сообщений счетчик уже есть, а для фото и видео зачем?

**Comment by thejesterguyiguess** [comment]
> Для сообщений счетчик уже есть, а для фото и видео зачем?

я просто предложил

**Comment by veselcraft** [comment]
Предложение то это понятно, но какой смысл у счетчика у фото- и видеозаписей?
