### ISSUE TITLE
Закладки

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#155]
![Screenshot_15](https://user-images.githubusercontent.com/63295722/134325111-630df63e-c15e-4086-b8bf-0a5b3b90cfc3.png)

**Comment by thejesterguyiguess** [comment]
"Закладки", функция позволяющая пользователю сохранять посты сообщества или фотографию, музыку(аудизаписи) и т.д

**Comment by celestora** [comment]
@fg-ij Пожалуйста, оформляйте issues корректно. Не пишите просто "добавьте Х", мы и так прекрасно знаем, каких фич нет. Если вам хочется помочь, пожалуйста, опишите принцип работы фичи и всё такое.

**Comment by thejesterguyiguess** [comment]
> @fg-ij Пожалуйста, оформляйте issues корректно. Не пишите просто "добавьте Х", мы и так прекрасно знаем, каких фич нет. Если вам хочется помочь, пожалуйста, опишите принцип работы фичи и всё такое.

я просто написал "закладки", я больше не пишу "добавить"

**Comment by celestora** [comment]
Вы же понимаете, что это не поменяло сути, да?..

**Comment by thejesterguyiguess** [comment]
> Вы же понимаете, что это не поменяло сути, да?..

ладно я напишу что делают "закладки", но наверное каждый знает что это такое

**Comment by veselcraft** [comment]
дубль #65
