### ISSUE TITLE
Раздел подарки

### ISSUE THREAD

**Issue by itsover56** [OpenVK/openvk#156]
Возможность дарить другим пользователям изображения "подарки" стоимостью во внутренних платёжных единицах 3 голоса. Подарки отображаются в разделе под фотографией профиля пользователя. Могут быть подарены анонимно
![Screenshot_16](https://user-images.githubusercontent.com/63295722/134327079-d955be4d-f1fb-4ce4-afa6-7e97c6f21954.png)
.

**Comment by thejesterguyiguess** [comment]
бесполезная функция, но не знаю может кому нибудь зайдет? Хотя наверное это вызовет только кринж у большинства

**Comment by ghost** [comment]
> 
> 
> бесполезная функция, но не знаю может кому нибудь зайдет? Хотя наверное это вызовет только кринж

Бесполезный, как и ваш комментарий. Пишите по делу, пожалуйста. Подобные комментарии будут помечаться как офф-топ.
