### ISSUE TITLE
Лайк на репост не ставит лайк на оригинальный пост

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#159]
Ну всё уже понятно из названия, в VK ставя лайк на репост - ставится лайк и на оригинальный пост, в OVK такого нет, но стоит реализовать.

**Comment by ghost** [comment]
Добавляю в проект вместо существующей заметки.

**Comment by veselcraft** [comment]
я думаю эта фича достойна реализации в близжайшее время

**Comment by celestora** [comment]
А что если цепочка репостов слишком большая?

**Comment by veselcraft** [comment]
Ну, очевидно, нагрузка большая будет

**Comment by IgordosDev** [comment]
Это тема для отдельного создания ошибки, но можно сделать репост
оригинального поста вместо репоста. То есть репост репоста делает репост
оригинального поста, вместо создания цепочки. Вот. Так реализовано в
оригинальном VK бтв.

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/136953388-eab84cf0-223d-4d50-a29c-84f765df6f7e.png)
