### ISSUE TITLE
Ответ на комментарии

### ISSUE THREAD

**Issue by Likmoo** [OpenVK/openvk#164]

**Comment by celestora** [comment]
Дубликат #148? Закрывать?

**Comment by veselcraft** [comment]
Нет

**Comment by ghost** [comment]
Спорно, на самом деле. Тот issue оформлен не так, как надо.

**Comment by veselcraft** [comment]
Ну и хорошо что тот Issue неправильно оформлен, этот оставим

**Comment by celestora** [comment]
А что подразумевается под ответами?

**Comment by ghost** [comment]
То, что ты уже сделала в https://github.com/openvk/openvk/commit/129d415877941f9d37136b7a9dee77d66d007b75.

**Comment by celestora** [comment]
> То, что ты уже сделала в [129d415](https://github.com/openvk/openvk/commit/129d415877941f9d37136b7a9dee77d66d007b75).

Тогда зачем вова хотел оставить

**Comment by dzhakit** [comment]
@celestora чтоб ты спросил
