### ISSUE TITLE
Не работает смена темы

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#166]
Кто поломал?

**Comment by ghost** [comment]
Не знаю

**Comment by rudzik8** [comment]
> Кто поломал?

бабайка 

![троллфейс](https://memoteka.com/images/thumb/d/d1/Troll1.jpeg/300px-Troll1.jpeg)

**Comment by rudzik8** [comment]
странно, у меня работает смена тем. не все темы работают, но половина из официального инстанса точно работает.

**Comment by veselcraft** [comment]
У меня тоже, однако. И некоторые темы также не работают

**Comment by shizotoaster** [comment]
Плюсую, у меня темы тоже отвалились. И, похоже, что все
![image](https://user-images.githubusercontent.com/51480483/135993012-3194431b-a703-4595-9157-d7dd49b5f3a1.png)

**Comment by veselcraft** [comment]
Вопрос сейчас актуален? Если нет, то закрываю issue

**Comment by WerySkok** [comment]
Советую оставить, пока овк не заработает

**Comment by likhner** [comment]
Работает
