### ISSUE TITLE
Текст в репост

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#167]
То есть:
![2021-10-07_15-20](https://user-images.githubusercontent.com/69392185/136366675-fed61c8d-d0ef-402d-b1c8-a6e6af0c2770.png)
К репосту в VK можно делать всё то, что можно делать при обычном посте, в OVK ты просто репостишь и всё тут. :confused:
Это проблема, хочется репостить и добавлять хотя бы свой комментарий в пост.

**Comment by IgordosDev** [comment]
а зачем закрывать ишуй если можно допилить например пикер медиа к репосту

**Comment by WerySkok** [comment]
@IgordosDev Это уже новая задача
