### ISSUE TITLE
Image Optimization

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#17]
Due to recent events (DDoS) main OpenVK instance has started being really slow, especially if there's no cache. So what about generating miniatures for photos so site would load faster?

**Comment by ghost** [comment]
I think optimization should have been done when we first started writing the code. Optimization should be at the time the user uploads the picture, and at different resolutions: 50px, 100px, 200px, 400px, and maximum picture size (like VK does). If we do optimization on the fly (when the user enters the page), there will be a delay, which is not good.

**Comment by WerySkok** [comment]
Я об этом просил ещё на этапе ЗБТ, но вопрос упорно игнорировался. Приходиться поднимать его вновь.

**Comment by ghost** [comment]
Зависело не от меня, всё таки.

**Comment by celestora** [comment]
Дубликат #54

**Comment by WerySkok** [comment]
> Дубликат #54

То не бубликат, а отдельная проблема.
Что касается данного ишшуя, проблему @celestora решила.

**Comment by celestora** [comment]
@WerySkok
