### ISSUE TITLE
Адаптация к часовому поясу

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#170]
При показе "человеческой" даты не учитывается часовой пояс юзера и даже сервера

**Comment by myslivets** [comment]
![image](https://user-images.githubusercontent.com/60743585/137686941-db0742c6-d593-4c5c-b417-e15b70cbbd40.png)

**Comment by veselcraft** [comment]
Думаю, в настройки стоит добавить указание часового пояса (к сожалению, пока-что без утчёта летнего времени (ну нам по п*********гу мы в р**************й ф***********************и живём)

**Comment by WerySkok** [comment]
Часовой пояс по идее легко через жс обнаруживается

**Comment by veselcraft** [comment]
разве не через заголовки браузера? хотя да, через жс можно прикол реализовать
