### ISSUE TITLE
Перенести подарки вправо, как ВКонтакте 2008 года

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#175]
![изображение](https://user-images.githubusercontent.com/22993408/136622692-88f60aab-f463-4802-9498-095c4c2cda34.png)

**Comment by veselcraft** [comment]
ИМХО, справа часть уж не очень богата пунктами, так что лучше всё-таки перенести направо

**Comment by l-lacker** [comment]
надеюсь в конфиге будет иметься возможность регулировать положение (справа или слева)
