### ISSUE TITLE
Перенос строки в статусе профиля.

### ISSUE THREAD

**Issue by VladimirLapskiy-zz** [OpenVK/openvk#176]
![image](https://user-images.githubusercontent.com/86822737/136654037-1d802048-9a9d-403f-b9d5-5dd9116dba44.png)

**Comment by ghost** [comment]
Несмотря на то, что я выкатил фикс, это почему-то игнорируется некоторыми символами:

![image](https://user-images.githubusercontent.com/55238545/136658196-e2448a72-1b36-402a-bdaf-5321f6798272.png)

**Comment by VladimirLapskiy-zz** [comment]
@dsrev Не знаю, как ты фиксил но я просто добавил `overflow: hidden;`.
![image](https://user-images.githubusercontent.com/86822737/136673584-32e3779d-2d4e-4893-8a45-7ce881fb96ad.png)

**Comment by ghost** [comment]
Ок. Я просто применил перенос строк ко всему, а про `overflow` совсем забыл.
