### ISSUE TITLE
Опросы

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#182]

**Comment by maksalees** [comment]
Я определенно не успею сделать это к выходу PT3 (извините), так что переношу на PT4

**Comment by veselcraft** [comment]
@maksalees есть новости по поводу опросов?

**Comment by maksalees** [comment]
> @maksalees есть новости по поводу опросов?

Новостей нет, но делаю

**Comment by celestora** [comment]
> @maksalees есть новости по поводу опросов?

Сегодня на канале «Объектив» — новости по поводу опросов
