### ISSUE TITLE
Отмена голосов

### ISSUE THREAD

**Issue by WerySkok** [openvk/openvk#183]
Сомнительная фича, учитывая, что OpenVK задумывался как некоммерческий проект, к тому же для этого нужно провести юридические процедуры, которые в нашем случае не проведены.

**Comment by TAB-q** [comment]
Голоса выдаются за донаты, ты о чем? Донаты может получать без облагания налогами любое лицо

**Comment by WerySkok** [comment]
Голоса на сайте тратятся на подарки и рейтинг, следовательно, оказываются услуги и это уже не является пожертвованиями.

**Comment by TAB-q** [comment]
УСЛУГИ ОКАЗЫВАЮТСЯ НЕ ЗА РУБЛИ. Если бы учавствовала офф. Валюта - тогда бы все было так

**Comment by WerySkok** [comment]
> УСЛУГИ ОКАЗЫВАЮТСЯ НЕ ЗА РУБЛИ. Если бы учавствовала офф. Валюта - тогда бы все было так

Голоса продаются за рубли, значит услуги продаются за рубли.

**Comment by veselcraft** [comment]
Предлагаю сделать отключение голосов в конфиге сайта вместе с подарками, на всякий случай

**Comment by HSDChannel** [comment]
@WerySkok вопрос, зачем?

**Comment by WerySkok** [comment]
> @WerySkok вопрос, зачем?

Чтобы сохранить OpenVK некоммерческим, очевидно же.

Я понимаю, что цель проекта — имитация ВК, и некоторые здесь хотят видеть и те функции, которые на исходном сайте платные. Но по опыту стикеров в телеграме мы знаем, что их необязательно делать тоже платными. Например, можно сделать так, чтобы можно высылать по 1 подарку в день, вычислять рейтинг в зависимости от активности страницы или вообще в зависимости от неё выдавать голоса (главное, чтобы не за деньги).

**Comment by dzhakit** [comment]
@WerySkok test
