### ISSUE TITLE
Регистрация по номеру телефона/email с кодом подтверждения.

### ISSUE THREAD

**Issue by dzhakit** [OpenVK/openvk#185]
Доброго времени суток, предлагаю добавить регистрацию с подтверждением почты/номера, это поможет опять же предотвращать спам, поможет подтвердить пользователя. Насколько мне известно на мегафон код не приходит, сделать предупреждение что на Мегафон код не приходит и что можно номер указать просто как восстановление в случае чего, соответственно сделать подтверждение по почте.

**Comment by veselcraft** [comment]
В коде сейчас используется:
1. Email для восстановления пароля
2. Zadarma для отправки кодов по номеру телефона

Задарма, к сожалению, платный, а постоянного капитала у нас пока нет, поэтому обойдёмся без подтверждения по телефону. Но подтверждение по Email, конечно же, вскоре запилим и будет обязательным для нашего основного инстанса
