### ISSUE TITLE
Закрепление групп в левое меню

### ISSUE THREAD

**Issue by dzhakit** [OpenVK/openvk#186]
![Screenshot](https://user-images.githubusercontent.com/50661626/136992189-fb4adea0-03cd-4d3b-8b4d-04a6ddb94888.png)

Доброго времени суток, предлагаю добавить закрепление групп в левой панеле для удобства перехода в группы.

**Comment by veselcraft** [comment]
Абсолютно солидарен. Обязательно запилим!)
