### ISSUE TITLE
Индикатор ответа на тикет пользователя

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#187]
Добавить тут цифру при наличие ответа в техпод. 1 когда есть 0 когда нету
![image](https://user-images.githubusercontent.com/90477403/136992801-2e369fb9-05d5-489b-a36f-cd1cdda433cd.png)

**Comment by zavolo** [comment]
> Добавить тут цифру при наличие ответа в техпод. 1 когда есть 0 когда нету ![image](https://user-images.githubusercontent.com/90477403/136992801-2e369fb9-05d5-489b-a36f-cd1cdda433cd.png)
(не там отметил)
![image](https://user-images.githubusercontent.com/90477403/136993097-8d4e561f-c037-4cab-ab42-fbc786675338.png)

**Comment by dzhakit** [comment]
@zavsc Гениально
