### ISSUE TITLE
Метка scam

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#188]
Как в телеграме

**Comment by veselcraft** [comment]
Спорно, ведь мы не lolzteam и не площадка для scumеров

Или это для лулзов добавлено?

**Comment by likhner** [comment]
Скам по-хорошему нужно банить, а не хвалить меткой

**Comment by veselcraft** [comment]
@celestora актуально? не отказался от идеи? иначе проблема закрывается

**Comment by WerySkok** [comment]
> @celestora актуально? не отказался от идеи? иначе проблема закрывается

Технически уже реализовано в 9e86389b6277884d180a9e881aa0c1b4d5d9d731. Однако было бы неплохо, если это плашка выводилась бы где-то ещё...

**Comment by veselcraft** [comment]
> 
> 
> > @celestora актуально? не отказался от идеи? иначе проблема закрывается
> 
> Технически уже реализовано в [9e86389](https://github.com/openvk/openvk/commit/9e86389b6277884d180a9e881aa0c1b4d5d9d731). Однако было бы неплохо, если это плашка выводилась бы где-то ещё...

Ну да, на страницу юзера она высвечивается. Ты имеешь в виду именно помечать каким-либо знаком в комментариях или в постах, например?
![изображение](https://user-images.githubusercontent.com/22993408/140621118-20e72557-3640-43a1-8493-38c2b1959a63.png)

**Comment by celestora** [comment]
> @celestora актуально?

Да, ещё актуально, на днях запилю

**Comment by WerySkok** [comment]
Именно это. Также ещё в поиске, сообщениях и других местах...
