### ISSUE TITLE
Ленивая загрузка для изображений

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#192]
Чтобы лишний раз не тратить трафик у CDN или мобильного интернета.

Нужно просто добавить `<img loading="lazy" …>`

https://web.dev/browser-level-image-lazy-loading/

**Comment by Lumaeris** [comment]
С введением #17 возникает вопрос - а нужно ли? Сейчас отображается картинка с размером максимум +- 130 KiB ("normal", проверялось в "Моих Новостях"), а не какие-нибудь 8-12 MiB (которые я заливал в одну группу по приколу :trollface:).

**Comment by likhner** [comment]
Всё же считаю, что это не будет лишним. Ибо всё равно нет смысла грузить лишний раз картинки которые пользователь даже не увидит.

Можно также вынести это в отдельную настройку при желании.

**Comment by Artem13327** [comment]
Полезная вещь. Лишним не будет

**Comment by Artem13327** [comment]
Закройте, типо выполнено
