### ISSUE TITLE
Автообновление страницы при выборе темы.

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#194]
Тема применится если обновить страницу , но хотелось бы чтобы OVK делал это сам
https://user-images.githubusercontent.com/90477403/137012331-b8283b81-563f-488d-8683-eeb49be9e96e.mp4

**Comment by veselcraft** [comment]
Исправлено в https://github.com/openvk/openvk/commit/1dff89972e59632365ff1175e05ba3886af2fdea
