### ISSUE TITLE
Отслеживать удаление фото и удалять их с CDN

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#195]
Если человек загрузил фото и потом его удалил — оно не удаляется с CDN.

**Comment by celestora** [comment]
CDN не часть OpenVK, поэтому настройками кэширования стоит управлять непосредственно оттуда. А так, начиная с 240ce51705909f326c56c1d872c4c9970233537f, OpenVK удаляет файлы при удалении медиа пользователем, если эта фича активирована в конфиге (на основном инстансе активирована).

**Comment by GeorgNation** [comment]
> CDN не часть OpenVK, поэтому настройками кэширования стоит управлять непосредственно оттуда. А так, начиная с [240ce51](https://github.com/openvk/openvk/commit/240ce51705909f326c56c1d872c4c9970233537f), OpenVK удаляет файлы при удалении медиа пользователем, если эта фича активирована в конфиге (на основном инстансе активирована).

Надо вместо этого TTL выставлять, чтобы была возможность в случае чего восстановить удаленный контент.

**Comment by GeorgNation** [comment]
@GeorgNation Индиске чааааа,
Индиске чааааа.
