### ISSUE TITLE
Не создаётся профиль после регистрации

### ISSUE THREAD

**Issue by veselcraft** [openvk/openvk#198]
Зато нормально отработал ChandlerUsers

![изображение](https://user-images.githubusercontent.com/22993408/137066685-047b8d86-9c2c-45a4-87c4-1e535ba43c27.png)

**Comment by veselcraft** [comment]
Я так понял, это связано с коммитом https://github.com/openvk/openvk/commit/dcdca4504566a9242a784188ad583393b9a9f388, который ранее сделал @VladimirLapskiy. Не указываешь ДР - профиль не создаётся

**Comment by VladimirLapskiy-zz** [comment]
> Я так понял, это связано с коммитом [dcdca45](https://github.com/openvk/openvk/commit/dcdca4504566a9242a784188ad583393b9a9f388), который ранее сделал @VladimirLapskiy. Не указываешь ДР - профиль не создаётся

Там в случае чего выводится ошибка, так что нет.

`  if (!strtotime($this->postParam("birthday")) < time())
                $this->flashFail("err", "Неверная дата рождения", "Дату рождения, которую вы ввели, не является корректным.")`

**Comment by veselcraft** [comment]
Оказалось, что проверка на правильность дня рождения проверяется уже после создания ChandlerUser, а не до неё

**Comment by veselcraft** [comment]
Исправлено в https://github.com/openvk/openvk/commit/403ed65bd10d942b754c73a3791225ccb78289de

_В следующий раз прошу @VladimirLapskiy указывать в описании комммтов "Fixes #198", чтобы проблема  сразу закрылась_
