### ISSUE TITLE
Не входит в профиль (мой инстанс)

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#199]
Поставил на чистый сервер debian 11 потом накатил ovk и ошибка при входе , хотя учётка админа есть.
![image](https://user-images.githubusercontent.com/90477403/137104428-c7bd887c-25de-4f8f-8daa-2de976acde96.png)

**Comment by veselcraft** [comment]
Судя по всему, у вас беды с БД. Переустановите OVK

**Comment by Defenders08** [comment]
@veselcraft Лол

**Comment by zavolo** [comment]
> Судя по всему, у вас беды с БД. Переустановите OVK

бд импортировалась , а вот yarn install прошёл только с ключом --ignore-engine

![image](https://user-images.githubusercontent.com/90477403/137106228-e1cdbf7a-22d4-4530-bb50-49c7d989c778.png)

**Comment by veselcraft** [comment]
Вот именно, что с ошибками, так что переустанавливайте

**Comment by zavolo** [comment]
> Вот именно, что с ошибками, так что переустанавливайте
нет , бд как раз таки нормально импортировалась

**Comment by veselcraft** [comment]
> > Вот именно, что с ошибками, так что переустанавливайте
> 
> нет , бд как раз таки нормально импортировалась
> 
> 

![image](https://user-images.githubusercontent.com/22993408/137106607-b05d7375-fa79-4fd6-99c2-6024ac36a302.jpeg)

**Comment by zavolo** [comment]
> > > Вот именно, что с ошибками, так что переустанавливайте
> > 
> > 
> > нет , бд как раз таки нормально импортировалась
> 
> ![image](https://user-images.githubusercontent.com/22993408/137106607-b05d7375-fa79-4fd6-99c2-6024ac36a302.jpeg)

опечатался
![image](https://user-images.githubusercontent.com/90477403/137106899-2bf1af8f-cef5-4fcb-9090-1d6721059ff6.png)

**Comment by celestora** [comment]
Покажите строку профиля админа и другие фреймы трассировки (User.php особенно интересует)

**Comment by zavolo** [comment]
> Покажите строку профиля админа и другие фреймы трассировки (User.php особенно интересует)
[User.php.txt](https://github.com/openvk/openvk/files/7336870/User.php.txt)
(уберите расширение txt)

profiles - 
![image](https://user-images.githubusercontent.com/90477403/137108070-5f070934-d468-4c80-a490-20623208bf75.png)

ChandlerUsers -
![image](https://user-images.githubusercontent.com/90477403/137108175-18f6ec59-cf8b-4803-8124-d67c9238e240.png)

**Comment by celestora** [comment]
Я про трассировку стека и фрейм из User.php, а не про файл. Файл-то у меня есть)

**Comment by Defenders08** [comment]
@celestora Вриска я хочу тебе отсосать

**Comment by zavolo** [comment]
> Я про трассировку стека и фрейм из User.php, а не про файл. Файл-то у меня есть)
логи? Не понимаю)

**Comment by zavolo** [comment]
В админку заходит
![image](https://user-images.githubusercontent.com/90477403/137109809-0aa96d07-d2ce-4017-b79c-cdba81bd2861.png)

**Comment by veselcraft** [comment]
Трассировки дождёмся? Если нет, то придётся закрыть
