### ISSUE TITLE
Скрытие информации о создателе группы.

### ISSUE THREAD

**Issue by dzhakit** [OpenVK/openvk#201]
Доброго времени суток, предлагаю добавить скрытие информации о создателе группы, для тех желает сохранять анонимность и не хочет показывать себя создателем той или иной группы.

**Comment by maksalees** [comment]
Полной аннонимности можно достичь благодаря коммитам [b15b964](https://github.com/openvk/openvk/commit/b15b9643a0706d3a1dd1267ec9718040f86c1f23), [5556c88](https://github.com/openvk/openvk/commit/5556c88e4402b3ec93f48307d750973928022578) и [c83947a](https://github.com/openvk/openvk/commit/c83947ab0969693751aed8a66a8c72adb8257f08). Для этого просто скройте список администраторов и скройте себя в списке подписчиков. Пока что чтобы картинки публиковались анонимно, на инстансе должна быть включена анонимная публикация
