### ISSUE TITLE
Кнопка "ответить" не работает в комментариях

### ISSUE THREAD

**Issue by themohooks** [openvk/openvk#207]
При нажатии на кнопку, ничего не происходит.
Возможно прикол самой страницы: https://openvk.su/photo25_26?from=album90
![R8Rorr8ovb](https://user-images.githubusercontent.com/81331307/137179764-5be78807-7f90-4004-9996-ddcc5dcfc622.gif)

**Comment by themohooks** [comment]
fix гифки

**Comment by celestora** [comment]
Актуальна ли проблема в версии Altair Preview (cb80385-nightly)?

**Comment by veselcraft** [comment]
> Актуальна ли проблема в версии Altair Preview (cb80385-nightly)?

В моем случае, в WebKit браузере (Firefox iOS) всё работает нормально

**Comment by themohooks** [comment]
Chrome 94.0.4606.81 Stable
Windows 10 21H1, баг исправлен
