### ISSUE TITLE
Маленькая ширина окна с граффити

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#209]
Всё на скриншоте

![изображение](https://user-images.githubusercontent.com/22993408/137194290-be011115-c44b-4169-9b4a-2ecbe869de13.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/55238545/137254707-4d7bbcc4-d331-4771-ae7d-80c4886741a0.png)

🗿

**Comment by ghost** [comment]
Выяснилось, что маленькое окно появляется только тогда, когда пользователь выбирает стороннюю тему.

![image](https://user-images.githubusercontent.com/55238545/137256509-33a96b87-50b2-48da-abd5-817ec8d75119.png)

**Comment by rudzik8** [comment]
считаю важным сделать так чтобы окно с граффити на всех мониторах, темах и браузерах имело одинаковый размер. очень важным

**Comment by ghost** [comment]
Оно и так будет везде одинаково. Тут уже зависит от автора темы.

**Comment by rudzik8** [comment]
> Оно и так будет везде одинаково. Тут уже зависит от автора темы.
будет, но пока что вообще нет
![image](https://user-images.githubusercontent.com/87843378/137572223-27f28ab1-ea05-4cf9-b63e-a02c5d854169.png)

**Comment by ghost** [comment]
А, ты про это. Ну здесь да, надо что-то делать

**Comment by mbs0ft** [comment]
Предлагаю добавить снизу меню растяжения окна, как было в оригинальном ВК:
![image](https://user-images.githubusercontent.com/22106304/138314945-b5f3d02b-75fa-46af-b336-5a996523ac31.png)

**Comment by maksalees** [comment]
Похоже это уже исправлено. Закрываю.
