### ISSUE TITLE
Приложение для айфона

### ISSUE THREAD

**Issue by CyberNya1** [openvk/openvk#213]
Будет приложение openvk для айфона?

**Comment by WerySkok** [comment]
Скорее нет, чем да. Не очень верится, что мы пройдём модерацию там. Впрочем, у сайта планируется мобильная версия

**Comment by CyberNya1** [comment]
> Скорее нет, чем да. Не очень верится, что мы пройдём модерацию там

можно через jailbreak, только нужен ipa файл и filza

**Comment by veselcraft** [comment]
@NikitaSokov2 Костыли, + спрос будет не такой большой

**Comment by CyberNya1** [comment]
> @ NikitaSokov2 Костыли, + спрос будет не такой большой

ну и ладно
