### ISSUE TITLE
Прикрепление уже существующих медиафайлов (фото, видео) к постам

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#215]
Лучше это сделать для предотвращения засорения хранилища веб-сервера одинаковыми медиафайлами, если по какой-то причине пользователю необходимо распространить один и тот же медиафайл.

**Comment by NoPlagiarism** [comment]
Resolved?..

**Comment by WerySkok** [comment]
Нет, пока ещё нельзя прикрепить фото

**Comment by ghost** [comment]
Закрыто a859fa1
