### ISSUE TITLE
"Табло", Яндекс.Браузер?

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#217]
Давайте мы не будем как Твиттер...:
![image](https://user-images.githubusercontent.com/60743585/137260334-fd9c1c68-89a4-469f-a442-8d47c272f637.png)

..и сделаем свой логотип для ~~хлебища~~ "Табло" Яндекс.Браузера
Почему и зачем это надо? Потому что.

**Comment by ghost** [comment]
Для этого надо бы хотя бы обновить полную версию логотипа...

**Comment by ghost** [comment]
> 
> 
> Для этого надо бы хотя бы обновить полную версию логотипа...

Готово.

ОДНАКО, я не могу сделать этот приколдес, просто потому что Яндекс удалили со своей документации статью про "Табло" Я.Браузера :trollface:.

**Comment by myslivets** [comment]
Genius :trollface:

**Comment by SigmaTel71** [comment]
> ОДНАКО, я не могу сделать этот приколдес, просто потому что Яндекс удалили со своей документации статью про "Табло" Я.Браузера :trollface:.

А потому что нестандартное табло теперь только зарегистрированным юрлицам прописывается. Физическим лицам не дают больше.

**Comment by veselcraft** [comment]
Отлично, закрываем проблему

**Comment by ghost** [comment]
> > ОДНАКО, я не могу сделать этот приколдес, просто потому что Яндекс удалили со своей документации статью про "Табло" Я.Браузера :trollface:.
> 
> А потому что нестандартное табло теперь только зарегистрированным юрлицам прописывается. Физическим лицам не дают больше.

Не знаю, откуда ты это взял, но спасибо за инфу.
