### ISSUE TITLE
Некоторые изменения в помощи,

### ISSUE THREAD

**Issue by dzhakit** [openvk/openvk#220]
Доброго времени суток, предлагаю изменить "новое обращение" на "Новый тикет", а "Список обращений" на "Список ваших тикетов"!

**Comment by themohooks** [comment]
неканон же будет

**Comment by dzhakit** [comment]
@MaksimMohooks в каком смысле?

**Comment by ghost** [comment]
Солидарен с @MaksimMohooks. Пусть даже нашу официальную инстанцию используют в основном подростки, у нас был хотя бы один человек, которому было за 30 лет. Он бы не знал, что такое _тикет_, и, скорее всего, держался бы от этого куда подальше. Лучше оставить всё, как есть.

**Comment by HSDChannel** [comment]
@dsrev согласен с вами
