### ISSUE TITLE
Админка.

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#222]
Добавить в админке юзера пункт Группа: Администратор , Helpdesk , юзер ( Чтобы лишний раз не заходить в бд, было в овк classic ) 
*Убрать не работающие пункты ( Настройки (?) )
![image](https://user-images.githubusercontent.com/90477403/137321110-c579f1ad-f64c-4e44-a4cb-12c01eee10fc.png)

![image](https://user-images.githubusercontent.com/90477403/137320692-83049697-aee2-4375-b7d9-67fdcab2154b.png)

**Comment by ghost** [comment]
Частичный дубликат #135. Про отключённые пункты - они здесь для информации, чтоб в лишний раз не заходить смотреть базу.
