### ISSUE TITLE
Бесполезная кнопка "Дальше" в списке видеозаписей

### ISSUE THREAD

**Issue by l-lacker** [OpenVK/openvk#228]
Если у пользователя загружено 7 видео — у него появляется кнопка "Дальше", позволяющая просмотреть следующие 7 видео. Но она бесполезна, так как следующая страница пустая. Если у пользователя ровно 7 видео, эту кнопку можно убрать, а если 8 и более — тогда добавить.
https://user-images.githubusercontent.com/37620897/137363539-feafd494-f831-4782-8102-b78cee58f0ca.mp4

**Comment by l-lacker** [comment]
Интересное наблюдение к ишшую: скорее всего, система отображения кнопки работает как нужно, просто в общее количество загруженных видео добавляются все видео, загруженные на стену. Естественно, в разделе "Видеозаписи" их нет, и удалить скорее всего тоже никак не выйдет. Можно считать как весьма серьёзный баг.

**Comment by celestora** [comment]
Исправлено в 1c341874a0661a53d60fbc65d46b72eb71efefff?
