### ISSUE TITLE
"Войти как" на своём инстансе

### ISSUE THREAD

**Issue by zavolo** [openvk/openvk#230]
![image](https://user-images.githubusercontent.com/90477403/137363972-8724fc21-0912-457f-b67d-4815929da98b.png)
В коде это есть , а вот у админа нет :(
![image](https://user-images.githubusercontent.com/90477403/137364056-48a0011d-21ac-45fe-a1bc-84ed7b02d1a3.png)

**Comment by l-lacker** [comment]
В коде оно действительно есть и должно работать, просто нужно выдать себе на это права.

**Comment by zavolo** [comment]
> В коде оно действительно есть и должно работать, просто нужно выдать себе на это права.

Но как это сделать

**Comment by zavolo** [comment]
Users.xml
![image](https://user-images.githubusercontent.com/90477403/137364497-072475e3-c3ba-4808-be86-aa209b2234eb.png)

**Comment by WerySkok** [comment]
В таблице ``ChandlerACLGroupsPermissions`` нужно добавить запись, как на иллюстрации (последняя строка, игнорируйте первую, context должен быть равен 0)
![image](https://user-images.githubusercontent.com/15957616/137365391-5ae1a50c-53b4-494d-9abe-b4ef6fd8ddf6.png)
Где ``group`` - GUID желаемой группы, назначаемой пользователю.

Так как это не очевидно, ишшуй не закрываю, пока в админке всё не будет сделано понятно.

**Comment by zavolo** [comment]
> В таблице `ChandlerACLGroupsPermissions` нужно добавить запись, как на иллюстрации (последняя строка, игнорируйте первую, context должен быть равен 0) ![image](https://user-images.githubusercontent.com/15957616/137365391-5ae1a50c-53b4-494d-9abe-b4ef6fd8ddf6.png) Где `group` - GUID желаемой группы, назначаемой группы.
> 
> Так как это не очевидно, ишшуй не закрываю, пока в админке всё не будет сделано понятно.

получилось
![image](https://user-images.githubusercontent.com/90477403/137366144-4be625ad-b122-475c-aedc-859e56c1fade.png)
