### ISSUE TITLE
В видеозаписи можно загрузить любой медиаконтент

### ISSUE THREAD

**Issue by celestora** [openvk/openvk#234]

**Comment by C0la149** [comment]
Не надо фиксить!!!!! Мы из за этой фичи музыку слушаем в OpenVK

**Comment by ghost** [comment]
Нет, надо. Дождитесь лучше поддержки аудиозаписей.

**Comment by C0la149** [comment]
Мы сдохнем пока дождёмся этой поддержки

**Comment by celestora** [comment]
@MineStroyMC щито поделать десу
