### ISSUE TITLE
Допилить видео

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#238]
Наверное я не должен лезть в это дело, но не слишком ли затратно в плане хранилища реализовывать видео и к каждому посту отдельное видео?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/69392185/137526366-613b5cef-a003-4de4-9ed9-dd1c482e4a74.gif)
Считаю стоит реализовать прикрепление к посту/комментарию/куда угодно уже существующего фото/видео. Если не из старого ВК, то хоть как-нибудь.
![image](https://user-images.githubusercontent.com/69392185/137524828-4a5b6029-efc4-4d37-9a53-6c945a7089a3.png)

**Comment by veselcraft** [comment]
скинь мне в телегу то видео с теилзом ржачное

**Comment by IgordosDev** [comment]
@veselcraft

**Comment by celestora** [comment]
Результаты кодека libvorbis детерминистичны, поэтому если входной файл один, то в хранилище он не повторяется. Но да, хорошо было бы подпилить)

**Comment by IgordosDev** [comment]
Ок, если не это, то я заметил сломанный счётчик видео на странице.
![image](https://user-images.githubusercontent.com/69392185/137583728-7fd611d3-1c11-4bb3-8747-3826d7e7c73e.png)
Здесь показывается 6 видео, но у меня их всего 2.
![image](https://user-images.githubusercontent.com/69392185/137583744-2e7ef2e3-46f5-4330-af5c-408694d615b2.png)
Я добавлял какие-то видео до этого, но удалял их. В счётчике они остались.

**Comment by veselcraft** [comment]
Це тому що видалені відео з якихось причин вважається лічильником, але вони не показуються в списку

**Comment by IgordosDev** [comment]
Ну так исправь, я тоже самое сказал

**Comment by veselcraft** [comment]
> Ок, если не это, то я заметил сломанный счётчик видео на странице.

Исправлено в https://github.com/openvk/openvk/commit/7e4896a0d31a48787db59a4f97aea03ea5a7d54d

**Comment by veselcraft** [comment]
Так мы пикер видео еще не сделали

**Comment by IgordosDev** [comment]
В пикере будет прикрепление видео с ютуба?

**Comment by NoPlagiarism** [comment]
> Так мы пикер видео еще не сделали

Может переименовать issue?

**Comment by Lumaeris** [comment]
Не, т.к. уже существует #215. Пожалуй закрою данное issue.
