### ISSUE TITLE
Наплыв пользователей в основном инстансе.

### ISSUE THREAD

**Issue by GeorgNation** [OpenVK/openvk#242]
В максимальный приоритет.

**Comment by ghost** [comment]
И как это связано с самим проектом? Закрываю.

**Comment by GeorgNation** [comment]
Я просто предупредил что основной инстанс начал тупить.

**Comment by TAB-q** [comment]
Это проблема не овк как скрипта, а проблема хоста

**Comment by ghost** [comment]
> 
> 
> Я просто предупредил что основной инстанс начал тупить.

Для этого есть дискуссии. НА МИНУТОЧКУ.

https://github.com/openvk/openvk/discussions

Ну или в чат пиши.
