### ISSUE TITLE
Кнопка "пригласить" в шапку сайта

### ISSUE THREAD

**Issue by myslivets** [openvk/openvk#244]
Сделайте доступ к пригласительной ссылке проще - поместите кнопку "пригласить" в шапку сайта.
Это, как по мне, намного проще, чем оставлять каждый раз openvk.su/invite

**Comment by zavolo** [comment]
дубликат? https://github.com/openvk/openvk/issues/196

**Comment by ghost** [comment]
Duplicate of #196
