### ISSUE TITLE
Создать звук для уведомлений (или использовать существующее)

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#245]

**Comment by mbs0ft** [comment]
https://github.com/openvk/openvk/discussions/55#discussioncomment-284459

**Comment by veselcraft** [comment]
Ну что, решились со звуком?

**Comment by celestora** [comment]
@veselcraft Да, на основном инстансе уведомления уже несколько дней отключены

**Comment by veselcraft** [comment]
ВСМЫСЛЕ

**Comment by myslivets** [comment]
:trl:

**Comment by myslivets** [comment]
:trollface:

**Comment by ghost** [comment]
> 
> 
> Ну что, решились со звуком?

Идей для звука нет. (ну и тем более новый DAW изучаю =)))

**Comment by maksalees** [comment]
Создан в коммите [d16b5fd](https://github.com/openvk/openvk/commit/d16b5fdf339ebead36165392086586255e5d5b64)

**Comment by ghost** [comment]
> ... (ну и тем более новый DAW изучаю =)))

*Вроде какой-то скилл есть. Осталось оригинал трек запилить =))*
