### ISSUE TITLE
окно граффити не адаптируется под dpi

### ISSUE THREAD

**Issue by moneyworldstar** [openvk/openvk#248]
![image](https://user-images.githubusercontent.com/90852312/137932876-a8220a5b-c561-4744-a296-da098a90ca6e.png)

**Comment by celestora** [comment]
Пожалуйста, уточните, какую тему вы используете и ваш браузер

**Comment by moneyworldstar** [comment]
Браузер (ж)Opera GX, тема В Контакте 2007

**Comment by ghost** [comment]
Дубликат #209
