### ISSUE TITLE
Смайлы-колобки в OpenVK

### ISSUE THREAD

**Issue by FadyFunker** [openvk/openvk#249]
Я предлагаю добавить в OVK старые смайлы-колобков, т.к в обычном ВК их хер используешь, а в ОВК будет каеф)

**Comment by mbs0ft** [comment]
@FadyFunker не вижу смысла, проще уже старые смайлы из вк закинуть

**Comment by veselcraft** [comment]
Колобков и в оригинальном ВК не было, так шо закрыто
