### ISSUE TITLE
Ненужная кнопка.

### ISSUE THREAD

**Issue by dzhakit** [OpenVK/openvk#251]
Доброго времени суток, предлагаю удалить кнопку "ред." рядом с "моя страница", как в OVK Classic, так как есть кнопка "Редактировать страницу" под аватаркой.

![image](https://user-images.githubusercontent.com/50661626/138227124-9dd3c321-8701-4d8e-8f5b-c2504324b0f9.png)

**Comment by veselcraft** [comment]
Зачем два лишних действия, если можно выполнить одно для редактирования страницы?

_А еще каждый раз приветствоваться не обязательно, достаточно описать проблему или предложение_

**Comment by celestora** [comment]
А я предлагаю удалить OpenVK, так как есть VK.

**Comment by Butonix** [comment]
> А я предлагаю удалить OpenVK, так как есть VK.

Тогда может удалить yandex и mail? Есть же Гугл
