### ISSUE TITLE
Нормальные BOX-окна

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#253]
Предлагаю изменить дизайн box-окон, сделав им нормальную высоту и убрав фоновое потемнение

![image](https://user-images.githubusercontent.com/60743585/138322254-b216a6c1-ea3a-4645-94dd-0c3eb2deabb6.png)

**Comment by veselcraft** [comment]
ну... выглядит как будто программист что-то недоделал))

**Comment by veselcraft** [comment]
Закрываю, т.к. не был сделан PR, да и дизайн так себе
