### ISSUE TITLE
Значок телефона при онлайне с мобильных устройств

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#254]
Предлагаю сделать отображение иконки телефона когда на сат заходят с мобильных устройств.
Можно вполне реализовать через определение user-агента: если он является Android или iOS/iPadOS, то иконка будет отображена.

**Comment by SigmaTel71** [comment]
\*некропостинг моде*
Потенциально реализуемо с выходом мобильного клиента OpenVK, но это не точно и вообще ОБС да вангование.

**Comment by veselcraft** [comment]
Актуально, учитывая поддержку нашего апи в VK4ME

**Comment by themohooks** [comment]
Иссуй был сделан спустя полтора года
