### ISSUE TITLE
Добавить возможность постинга медиа через API

### ISSUE THREAD

**Issue by Sux0Phone** [OpenVK/openvk#255]
Метод wallPost поддерживает только текст, но не картинки и видео. Реквест фактически в тайтле.

Зачем нужно? Если будет эта фича, напишу бота-отложку для Telegram и выложу в опенсорс. По факту я и другие админы постят контент потоком, что напрягает. Родной отложки нет, да и сейчас, на мой взгляд, она не приоритет, можно решить софтом со стороны. Пожалуйста, дайте возможность этот софт написать.

**Comment by arthckr** [comment]
priority:highest? Анекдот дня.
@veselcraft @dsrev @celestora @maksalees

**Comment by maksalees** [comment]
> priority:highest? Анекдот дня. @veselcraft @dsrev @celestora @maksalees

![](https://c.tenor.com/9Nuo3IhY50IAAAAC/ralsei-undertale.gif)

**Comment by arthckr** [comment]
@maksalees Да не смешно это. Разработчики пометили как "наивысший приоритет" и сами же игнорируют.

**Comment by maksalees** [comment]
Коммит [5d62934](https://github.com/openvk/openvk/commit/5d6293405390420af4616325b83aa0e8b22e4673) добавляет прикрепление медиа к посту, которое работает но несовмистимо с API ВКонтакте. Для совместимой реализации я создал #414. Это я закрываю
