### ISSUE TITLE
Сделать описание на главной странице сайта на разных языках

### ISSUE THREAD

**Issue by itsyuni** [OpenVK/openvk#261]
Сейчас поменяв на другой язык (к примеру на английский), описание сайта все равно на русском.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/24845145/139722364-f1f3a1a6-713f-49b4-aa71-33e120794ab1.png">

**Comment by veselcraft** [comment]
а помните когда протеус назвал фару пидором?

**Comment by itsyuni** [comment]
> а помните когда протеус назвал фару пидором?

Вов, иди отоспись

**Comment by veselcraft** [comment]
Исправлено в https://github.com/openvk/openvk/commit/c8eb6c3f3f5935090d66e04f27b931533974154a
