### ISSUE TITLE
Feature Request: Dislike

### ISSUE THREAD

**Issue by smolnp** [OpenVK/openvk#27]
I would like to be able to put dislikes. For example, for:
![Screenshot_20210105_125502](https://user-images.githubusercontent.com/26217756/103632391-48600980-4f55-11eb-96c0-bc9f73b71270.png)

**Comment by smolnp** [comment]
Or a profanity filter for blogs. Or any filter so that similar content is not displayed when you click the bottom "Blog" button.

**Comment by veselcraft** [comment]
This func wasn’t  seen in original VK, but we can do this feature as external (that can be enabled trough config)

**Comment by veselcraft** [comment]
Not in demand, closed
