### ISSUE TITLE
Невозможно попасть в сообщения

### ISSUE THREAD

**Issue by PixelAlex** [OpenVK/openvk#271]
При попытке открыть сообщения(https://openvk.su/im) вылезает ошибка:
![image](https://user-images.githubusercontent.com/65106193/140505568-534cdb63-62ab-4460-aae2-13e7bcf07930.png)

Решил посмотреть, почему getSendTime() вызывается на null. По апи вывел историю всех переписок, и увидел в одной из переписки это:
![image](https://user-images.githubusercontent.com/65106193/140505752-0e7f240d-2e54-43bb-8164-634c92058dec.png)
Я не думаю, что null в last_message это норма. Возможно из-за этого все и ломается. Но вопрос: почему там null и как это произошло?

**Comment by celestora** [comment]
Проблема не кодовой базы, а ошибок с БД, возникших по причине человеческого фактора на стороне администрации инстанса ovksu, обращайтесь в поддержку к ним.

**Comment by veselcraft** [comment]
@celestora так те лёха писал но ты проигнорил
