### ISSUE TITLE
Откатить 2b6f4a9896359c60993b655b0485c4b546fc7301

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#275]
Коммит 2b6f4a9896359c60993b655b0485c4b546fc7301 увеличил длину строчки текста в постах на 60%, из-за чего посты теперь смотрятся просто отвратительно:
![image](https://user-images.githubusercontent.com/34442450/140612342-fa3c157d-2b26-49df-9bc5-97ef0a5ac0ce.png)

Предлагаю отменить это изменение и пересмотреть варианты решения проблемы #268:
1. Добавить как опцию в настройках
2. Включать только на длинных постах
3. Всё сразу

**Comment by veselcraft** [comment]
3

**Comment by WerySkok** [comment]
3

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/140624301-3a632022-aad9-46c9-b538-573c2eade749.png)

**Comment by ghost** [comment]
Может лучше вместо `160%` поставить `140%` или `130%`? Так будет меньше бросаться в глаза.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/55238545/140636042-aace464a-93b7-4e79-b0d9-7dda03b0054a.png)

~~Или 10% :trollface:~~

**Comment by celestora** [comment]
> Может лучше вместо `160%` поставить `140%` или `130%`? Так будет меньше бросаться в глаза.

Действительно, так и сделаю.
