### ISSUE TITLE
Ability to ping users by page adresses

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#28]
It's in the title. How it works right now: https://openvk.su/wall4_58.

**Comment by veselcraft** [comment]
Я конечно дико извиняюсь за комментарий 10-месячной давности, но ты имел в виду шоб прям уведомлением приходило о том что "Юзверь упомянул вас в посте том-то"?

**Comment by veselcraft** [comment]
бл*н моё сообщение никто не заметил

**Comment by WerySkok** [comment]
Я имел ввиду то, чтоб shorturl тоже распознавались и трансформировались в id, но твоё предложение отсылать уведомления тоже хорошо
