### ISSUE TITLE
CSRF уязвимости в /logout и смене языка

### ISSUE THREAD

**Issue by levkopo** [OpenVK/openvk#281]
С помощью тега img можно вызвать системные ссылки при открытии заметки.
Например вызвать https://openvk.su/logout или сменить язык сайта.
Пример такой уязвимости: https://openvk.su/note5384_19

**Comment by celestora** [comment]
TL;DR: меняю название бага и серъёзность

Это не XSS-уязвимость в заметках, так как по спецификации HTTP GET-запросы не должны быть использованы для модификации данных или смены состояния. Так что заметки как раз правильно работают, неправильно работают /logout и /language, которые без hash почему-то.
