### ISSUE TITLE
Поддержка PWA

### ISSUE THREAD

**Issue by HSDChannel** [OpenVK/openvk#288]

**Comment by IgordosDev** [comment]
Простите за оффтоп, а что это? 🤔

**Comment by ayaaop** [comment]
@IgordosDev Progressive Web Apps

**Comment by Nediorg** [comment]
Ну бред какой то. Кто-кто, а опенвк как приложение не идёт никак...

**Comment by themohooks** [comment]
> Ну бред какой то. Кто-кто, а опенвк как приложение не идёт никак...

мастер быстро отвечать на иссуи
