### ISSUE TITLE
Строчки о разделах в информации

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#289]
> ![image](https://user-images.githubusercontent.com/69392185/141692355-29787747-38ef-468a-a4ea-a57bedd57bcd.png)

Зачем нужны строчки разделов информации, если она вообще не указана? Почему не убрать это?
> ![image](https://user-images.githubusercontent.com/69392185/141692384-422ab14b-f781-499e-ba75-0cc3f518f36e.png)

И здесь также, не указана контактная информация, но строчка о разделе есть.

**Comment by celestora** [comment]
Такое поведение было в OpenVK Classic

**Comment by veselcraft** [comment]
> 
> 
> Такое поведение было в OpenVK Classic

и что

**Comment by WerySkok** [comment]
> Такое поведение было в OpenVK Classic

@celestora ну не позорься, а. Это очевидный баг.

**Comment by zavsc** [comment]
> @celestora ну не позорься, а. Это очевидный баг.
Мда в овк2 есть баги 2-3 летний давности

**Comment by zavolo** [comment]
> > Такое поведение было в OpenVK Classic
> 
> @celestora ну не позорься, а. Это очевидный баг.

Мда в овк2 есть баги 2-3 летний давности

**Comment by veselcraft** [comment]
> 
> 
> > > Такое поведение было в OpenVK Classic
> > 
> > 
> > @celestora ну не позорься, а. Это очевидный баг.
> 
> Мда в овк2 есть баги 2-3 летний давности

Мда в овк2 есть баги 2-3 летний давности

**Comment by celestora** [comment]
@veselcraft Не знаю, это к тебе вопрос, почему в овкк так было. В спорных моментах всё делалось по образцу овкк\
