### ISSUE TITLE
Игры в ОВК

### ISSUE THREAD

**Issue by alexflitcher1** [OpenVK/openvk#291]
Здравствуйте, уважаемые разработчики OpenVK, мне, как пользователю вашего, не побоюсь этого слова, гениальному проекту очень хотелось бы видеть то, без чего не мог существовать ВКонтакте 2014-2017 годов, а именно, пользовательских игр. Я считаю, что такой функционал может расширить и улучшить в положительную сторону околоОВКшный контент.

Итак, напишу более подробно, что я(и уверен другие пользователи) хотел бы видеть:
    1. Загрузка исходного кода(JavaScript) на сервера соц. сети
    2. Загрузка игры с другого сайта(во ВКонтакте это реализовано через тэг `iframe` )

Надеюсь, такой функционал будет реализован в ближайшее время.

Спасибо, уважаемые разработчики OpenVK

**Comment by veselcraft** [comment]
Обдумаем этот вопрос с командой

*З.ы. каждый раз приветствоваться не обязательно - здесь это вообще не нужно))*
