### ISSUE TITLE
Замена формата Textile на Markdown в KnowledgeBase

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#293]
Правила, политика конфиденциальности и некоторые другие страницы уже настраиваются и располагаются в папке data/knowledgebase, но их главная проблема в том, что они используют малопопулярный формат Textile, в связи с чем неудобны для форматирования. Надо заменить парсер Textile на Markdown и адаптировать существующие файлы с примерами.

**Comment by veselcraft** [comment]
согласен вриска писькогрызка использует какой то всратый формат бл*н

**Comment by celestora** [comment]
@WerySkok А мне вот кажется, что текстиль более удобный язык, чем марквнизу. То, что он малопопулярный компенсируется тем, что он крутой и быстро учится 🍄👍🏻.

**Comment by WerySkok** [comment]
Всё используют Markdown, не городи костыли.

**Comment by celestora** [comment]
@WerySkok Textpattern не использует, гх поддерживает текстиль. Более того, не понимаю, с каких пор опенвк это "всё".

**Comment by veselcraft** [comment]
> 
> 
> @WerySkok А мне вот кажется, что текстиль более удобный язык, чем марквнизу. То, что он малопопулярный компенсируется тем, что он крутой и быстро учится 🍄👍🏻.

А если у человека, работающего над проектом, тупо нет времени или возможности подучить этот ваш Textile? Да, подсмотреть в документацию можно, но время на редактирование увеличивается

**Comment by ghost** [comment]
Макс сделал коммит (7508030909c66c75fc02f9767f9be75eb855d1cf), который "фиксит" парсинг для страницы /about, НО ломают все страницы, включая /privacy и "Голоса" в настройках. Даже не знаю, это беда парсера или чьих-то кривых рук?

**Comment by ghost** [comment]
К чёрту это, заменяю.

**Comment by maksalees** [comment]
> Макс сделал коммит ([7508030](https://github.com/openvk/openvk/commit/7508030909c66c75fc02f9767f9be75eb855d1cf)), который "фиксит" парсинг для страницы /about, НО ломают все страницы, включая /privacy и "Голоса" в настройках. Даже не знаю, это беда парсера или чьих-то кривых рук?

Проблема была в том что эти страницы были написаны для сломанного парсера. С исправленным парсером они сломались. Такой же вывод даёт и официальный сайт текстиля. Моя вина что не проверил работу с другими страницами, но у меня не кривые руки)

**Comment by ghost** [comment]
Про последнее было всё таки лишнее
