### ISSUE TITLE
Прикрепление фотографий в саппортке\helpdesk

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#295]
Не хватает прикрепление фоток в helpdesk и саппортке
![image](https://user-images.githubusercontent.com/90477403/142262823-cf7bc6ba-844b-43a7-aa75-9edd032f0856.png)

**Comment by maksalees** [comment]
Дубликат #218

**Comment by arthckr** [comment]
лол а зачем ты это опубликовал когда ты и так уже написал?)))

**Comment by maksalees** [comment]
> лол а зачем ты это опубликовал когда ты и так уже написал?)))

Как вылечиться от деменции
