### ISSUE TITLE
Увеличение фотокарточек

### ISSUE THREAD

**Issue by okqq** [OpenVK/openvk#305]
Хотелось, чтобы при нажатии на картинку она открывалась и там была статистика картинки (лайки,репосты,комменты) и сама картинка чуть в увеличенном размере. Заранее спасибо.

**Comment by veselcraft** [comment]
а теперь подробнее

**Comment by okqq** [comment]
Когда нажимаешь на фотку, она открывается в том же размере, в котором ее выложили и часто бывает, что плохо различим текст или сама фотка. И хотелось, чтобы при нажатии на фотку она открывалась немного в большем размере. Надеюсь вы поймёте) (перефразировал)

**Comment by veselcraft** [comment]
а в чем проблема нажать на "открыть оригинал"?

**Comment by okqq** [comment]
Проблемы нет, но всё же так удобней
