### ISSUE TITLE
Вставка изображений из буфера обмена в посты не работает

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#314]
...хотя должна, очевидно
возможно недавний коммит это каким то образом сломал, но я точно помню что это работало где-то часа два назад

P.S. прикрепление изображений с помощью обычных файлов работает

**Comment by kirpoartur** [comment]
@rudzik8 разве такая функция вообще была?

**Comment by veselcraft** [comment]
> @rudzik8 разве такая функция вообще была?

Была

**Comment by heeeyohu** [comment]
@rudzik8 Ещё в вк была ( и есть) возможность прикрепить фотку с помощью ссылки

**Comment by celestora** [comment]
Related to #315?
А причина вот здесь: https://github.com/openvk/openvk/blob/325c4d23a1cfbff4729db8fa44a56051b785a624/Web/Presenters/templates/components/textArea.xml#L5

**Comment by celestora** [comment]
@veselcraft не могли бы вы объяснить, что делает рандомизация айди, я просто спал и не следил за овк :D

**Comment by veselcraft** [comment]
@celestora Для ЖС проколов 😁😁😁😁

**Comment by rudzik8** [comment]
![image](https://user-images.githubusercontent.com/87843378/144437212-0cde3bec-e62e-4cb8-8e92-86b14ea70b64.png)
так всё таки закрыто или нет?

**Comment by maksalees** [comment]
Забыл упомянуть иссуй. Закрыто
