### ISSUE TITLE
Ответы на комментарии в микроблоге не работают

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#315]
ссылка "Ответить" кликается, но ничего не делает
![image](https://user-images.githubusercontent.com/87843378/143768333-1010ff15-3cb8-484f-a632-3fbfdedfd16a.png)

**Comment by maksalees** [comment]
Исправлено в [497e55b](https://github.com/openvk/openvk/commit/497e55b1a759e98ee55c863274325339b0b56174)
