### ISSUE TITLE
Шаблон уведомления лайка на коммент пропал

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#322]
Я не знаю как это произошло но его просто нету в репозитории. Напишите, что ли?

p.s. код действия 0x00, отношение 6 к 18.

**Comment by maksalees** [comment]
Его никогда и не было, а уведомление про лайк на комментарий я добавил случайно в коммите [5c9d3c0](https://github.com/openvk/openvk/commit/5c9d3c085ebdc788f9e03793171b65e742c71863) (даже если добавить шаблон, оно не будет нормально работать). Думаю лучше изменить этот иссуй просто на добавление уведомления про лайке комментария, так как нормальной реализации этого действительно не хватает

**Comment by celestora** [comment]
Лол
