### ISSUE TITLE
?lg=en doesn't stay after switching language

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#324]
On the phone, when using Privacy Browser, I want to switch the language from Russia to English. So I go to the language page after few seconds of searching. After choosing English, everything is in English. Great! But when I change page, `?lg=en` disappears from the URL and the page will be in Russia again.

This issue does not exists in Firefox on Linux. There, English is the chosen language when I go to the website.

**Comment by veselcraft** [comment]
That's the issue of "Privacy Browser", bc it does not store cookies correctly

Everything is fine on LibreWolf, Firefox (Both Desktop OS'es and Mobile)

**Comment by ghost** [comment]
OpenVK uses Cookies and JavaScript. Privacy Browser turns them off by default for the sake of "privacy", so you have to enable JS (globe icon next to the URL) and Cookies (Menu > Cookies) to use the website properly.
