### ISSUE TITLE
Конверктация голосов в рейтинг самому себе или другим пользователям

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#345]
![photo_2021-12-14_16-59-44](https://user-images.githubusercontent.com/22993408/146013941-6c6cf507-770e-4083-8e01-4f2a57bb81c8.jpg)

**Comment by hetrixq** [comment]
@veselcraft .УРА

**Comment by celestora** [comment]
А можно голоса переводить другому?

**Comment by veselcraft** [comment]
@celestora да

**Comment by veselcraft** [comment]
Передача была сделана в коммите https://github.com/openvk/openvk/commit/3b54c4b878dac26ae7557cef76f84ca7cc70650e, но преобразование - пока нет

**Comment by maksalees** [comment]
> Передача была сделана в коммите [3b54c4b](https://github.com/openvk/openvk/commit/3b54c4b878dac26ae7557cef76f84ca7cc70650e), но преобразование - пока нет

Теперь этот issue подразумевает конвертацию голосов в рейтинг только самому себе?

**Comment by veselcraft** [comment]
а блин я дурак

**Comment by maksalees** [comment]
Предлагаю делать конвертацию только самому себе, так как уже можно передавать голоса

**Comment by veselcraft** [comment]
Не согласен, пусть можно будет и рейтинг другому пользователю передавать

**Comment by maksalees** [comment]
> Не согласен, пусть можно будет и рейтинг другому пользователю передавать

А вдруг пользователю не интересен рейтинг и он хочет получить голоса, а друг дал ему рейтинг? Если будет только один вариант - друг просто даст голоса, а пользователь уже сам решит на что их ему тратить :trollface:

**Comment by veselcraft** [comment]
> > Не согласен, пусть можно будет и рейтинг другому пользователю передавать
> 
> А вдруг пользователю не интересен рейтинг и он хочет получить голоса, а друг дал ему рейтинг? Если будет только один вариант - друг просто даст голоса, а пользователь уже сам решит на что их ему тратить :trollface:

Да пусть передача рейтинга будет, ёмаё. Тем более такое было в классическом ВК
