### ISSUE TITLE
Отсутствуют стили в /wall

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#35]

**Comment by celestora** [comment]
Они там должны быть? Ржу)
/wall так-то internal-only presenter и вызывается только из шаблонов User/View и Club/View

**Comment by veselcraft** [comment]
> /wall так-то internal-only presenter и вызывается только из шаблонов User/View и Club/View

1. Они прописаны в `routes.xml`
2. почему бы не использовать `components/wall.xml`

**Comment by veselcraft** [comment]
Пофикшено полностью
