### ISSUE TITLE
Редизайн диалогов

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#351]
Сделать чат более похожим на ВК/убрать перезагрузки для просмотра нового сообщения
Пример чата 2016 годом ниже:
![image](https://user-images.githubusercontent.com/46892579/146580491-3e90ac7c-d5fe-448b-9872-e2edbf30133c.png)

**Comment by Nediorg** [comment]
@Nediorg

**Comment by veselcraft** [comment]
Что за заэволированные названия проблем? Почему бы не писать ясно и четко?

**Comment by veselcraft** [comment]
Сделано в https://github.com/openvk/openvk/commit/db3789bef8dce2426f2dbb970ca3c24c9c9f8432
