### ISSUE TITLE
"Статус (+10%)"?

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#355]
На самом деле, заполнение статуса не даёт +10% к рейтингу

![image](https://user-images.githubusercontent.com/60743585/146631632-60ea36a9-b8de-4528-aa14-1bca399cbe6d.png)

А слегка больше

![image](https://user-images.githubusercontent.com/60743585/146631643-54bc598b-1e29-4d07-9d3d-fb614f51d3a4.png)

**Comment by veselcraft** [comment]
лол

**Comment by hetrixq** [comment]
@veselcraft Профит, который мы заслужили

**Comment by MatroCholo** [comment]
@MatroCholo
