### ISSUE TITLE
Добавить типы для тем в обсуждениях

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#356]
открытый должен будет стоять по дефолту (то есть любой может ответить на тему), а в закрытом ответить сможет только админ сообщества. типы (в моём понимании) должны быть доступны только админам чтобы они могли создавать закрытые темы специально для своих групп. в вк, как я понял подобное уже реализовано (хоть и явно не так), но всё же
![image](https://user-images.githubusercontent.com/87843378/146636590-c97c4bec-6a01-492f-95d5-4a9ae7131fb6.png)

**Comment by maksalees** [comment]
> в вк, как я понял подобное уже реализовано
Сейчас в OpenVK это реализовано в точности как в ВК. Тему можно закрыть из меню редактирования, в закрытую тему писать не сможет никто (даже администратор группы)

**Comment by maksalees** [comment]
Закрывать?

**Comment by rudzik8** [comment]
> > в вк, как я понял подобное уже реализовано
> 
> Сейчас в OpenVK это реализовано в точности как в ВК. Тему можно закрыть из меню редактирования, в закрытую тему писать не сможет никто (даже администратор группы)

1. как её можно закрыть из меню редактирования?
2. я имел в виду от имени группы, эмм
я немного другое имел в виду под словом "закрытый" как бы

**Comment by MatroCholo** [comment]
@rudzik8 1) кнопка же есть, закрыть

**Comment by veselcraft** [comment]
1. вот так
![image](https://user-images.githubusercontent.com/22993408/146645411-5bb74099-0cb0-43e4-b448-08874acaa5fa.png)

**Comment by veselcraft** [comment]
1) вот так 
![image](https://user-images.githubusercontent.com/22993408/146645430-79e2251a-0c5a-42c0-baf6-9fc6d3dd4167.png)

**Comment by rudzik8** [comment]
> 1. вот так
>    ![image](https://user-images.githubusercontent.com/22993408/146645411-5bb74099-0cb0-43e4-b448-08874acaa5fa.png)

прикол)
но тогда в обсуждении никто не сможет писать, и даже админы. так что я просто не так это всё описал
я имел в виду добавить возможность делать так, чтобы в теме могли писать только админы от имени группы и всё

**Comment by maksalees** [comment]
> > 1. вот так
> >    ![image](https://user-images.githubusercontent.com/22993408/146645411-5bb74099-0cb0-43e4-b448-08874acaa5fa.png)
> 
> прикол) но тогда в обсуждении никто не сможет писать, и даже админы. так что я просто не так это всё описал я имел в виду добавить возможность делать так, чтобы в теме могли писать только админы от имени группы и всё

Такого нет в ориг ВК :trollface:

**Comment by veselcraft** [comment]
Можно ещё темы переоткрывать :trollface:
