### ISSUE TITLE
Занятся диалогами

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#357]
Здраствуйте, уважаемые разработчики OpenVK

Хочу чтобы вы занялись улучшением диалогов, например сделали добавление фотографий к ним, ответы и т.п. ибо это выглядит ужасно
Надеюсь, вы займетесь диалогами в ближайшее время.

Спасибо, уважаемые разработчики OpenVK

**Comment by veselcraft** [comment]
Во первых - дубликат #189
Во вторых - приветствоваться не обязательно, а названия тикетов в будущем прошу делать ясными, а не завуалированные "ЗАНЯТЬСЯ ДИАЛОГАМИ"

**Comment by TAB-q** [comment]
тся
