### ISSUE TITLE
Точка с запятой (;) ломает любую ссылку

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#359]
из-за этого ссылки на топики в форумах не работают и отсылают либо на раздел, либо на страницу 404
было бы **чудесно** если бы она не считалась инородным символом и не ломала ссылки
примеры:
![image](https://user-images.githubusercontent.com/87843378/146643150-1d5fbb3f-55c6-486a-b878-a2b547e10317.png)
![image](https://user-images.githubusercontent.com/87843378/146643167-4730f28b-c324-4d24-b753-f0cb9c7b14a7.png)

**Comment by Playez** [comment]
@rudzik8 Жалко

**Comment by Playez** [comment]
@Playez ЭЭ
