### ISSUE TITLE
Недостатки настроек приватности

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#36]
На данный момент не работают следующие настройки приватности:

1. Кому в интернете видно мою страницу (при значениях `Только мне` и `Друзьям`)
1. Кому видно мои фотографии (в том числе альбомов)
2. Кому видно мои видеозаписи
3. Кому видно мои заметки

Так же не авторизованным пользователям доступен поиск людей. При учёте, если человек закрыл свою страницу и/или скрыл основную информацию, то всё это видно в поиске. 

Ещё, когда пользователь запрещает видеть его страницу всем, кроме пользователей OVK (следовательно, отказываясь от всех индексаций и архивирования), то Вам необходимо установить дополнительный мета-тэг:

`<meta name="robots" content="noindex, noarchive">`

В таком случае так же нужно убирать тэги openGraph и прочие схемы на пользователя.

**Comment by veselcraft** [comment]
> Так же не авторизованным пользователям доступен поиск людей. При учёте, если человек закрыл свою страницу и/или скрыл основную информацию, то всё это видно в поиске.

В аргумент скажу то, что (Во ВКонтакте образца 2008 года) когда пользователь попадает на закрытую страницу, его перекидывает в поиск с предложением добавить в друзья, а также отображаемой главной информацией - Имя, фото, и т.д.

> Ещё, когда пользователь запрещает видеть его страницу всем, кроме пользователей OVK (следовательно, отказываясь от всех индексаций и архивирования), то Вам необходимо установить дополнительный мета-тэг

> В таком случае так же нужно убирать тэги openGraph и прочие схемы на пользователя.

Поддерживаю, учтём!
