### ISSUE TITLE
Сделать переключение между новостями и страницей пользователя при нажатии на логотип сайта

### ISSUE THREAD

**Issue by id57** [OpenVK/openvk#361]
https://github.com/openvk/openvk/issues/361#issuecomment-998512729

**Comment by rudzik8** [comment]
по сути ты предлагаешь перенести главную страницу с профиля пользователя на его новости?

**Comment by id57** [comment]
> по сути ты предлагаешь перенести главную страницу с профиля пользователя на его новости?

Нет. Я предлагаю чтобы логотип перебрасывал на новости

**Comment by hetrixq** [comment]
@rudzik8 Хз, уже две кнопки это делают - "Главная" и "OpenVK". Надо бы что то предпринять

**Comment by hetrixq** [comment]
@id57 *кнопка OpenVK = главная страница*

**Comment by rudzik8** [comment]
> > по сути ты предлагаешь перенести главную страницу с профиля пользователя на его новости?
> 
> Нет. Я предлагаю чтобы логотип перебрасывал на новости

логотип перебрасывает на главную страницу как бы
а главная страница сейчас это и есть openvk.su/id0 (т.е. пользователя)

**Comment by id57** [comment]
> @id57 *кнопка OpenVK = главная страница*

Я говорю чтобы **Кнопка OpenVK = Новости**

**Comment by WerySkok** [comment]
Скорее всего, стоит в настройках добавить переключалку, где можно будет выбрать, куда пользователя будет перекидывать нажатие на логотип в хедере. По умолчанию оставим id0, конечно же.

**Comment by id57** [comment]
> Скорее всего, стоит в настройках добавить переключалку, где можно будет выбрать, куда пользователя будет перекидывать нажатие на логотип в хедере. По умолчанию оставим id0, конечно же.

Окей

**Comment by ghost** [comment]
Закрывать issue нужно только в том случае, если реализация была готова (или идея была банально отклонена).

**Comment by id57** [comment]
> Закрывать issue нужно только в том случае, если реализация была готова (или идея была банально отклонена).

А понятно (просто я не знал)

**Comment by maksalees** [comment]
Думаю нужно делать переключатель действия не только логотипа а всей главной страницы (логотип, кнопка "главная" и переход на /)
