### ISSUE TITLE
Фильтр "Не показывать NSFW" во вкладке "Мои новости"

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#368]
Столкнулся сегодня со стеной хентая в ОВК, а хотелось бы с мемами и интересными штуками. В целом, было бы неплохо иметь возможность фильтровать свои новости

**Comment by veselcraft** [comment]
![image](https://user-images.githubusercontent.com/22993408/147468650-53abc73d-48b4-4e2b-85d6-44d221df0edc.png)

Мои настройки > Внешний вид

**Comment by maksalees** [comment]
Уже реализовано

**Comment by ghost** [comment]
Данная функция уже существует в настройках во вкладке "Внешний вид" - https://openvk.su/settings?act=interface

Если вы нашли посты NSFW, которые не были помечены - советую писать в тех.поддержку OpenVK.

**Comment by grishiit** [comment]
Извиняюсь тогда что зря потратил ваше время
