### ISSUE TITLE
Возможность скрыть пользователя/группу из глобальной ленты

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#372]
Есть несколько групп, которые я никогда не читаю, но они появляются в ленте и служат для меня визуальным мусором. Есть конечно похожее issue #226 , но, например, полностью блокировать друга только для того, чтобы скрыть его из ленты, немного неудобно и глупо.

**Comment by rudzik8** [comment]
дубликат #133
разве нет?

**Comment by ghost** [comment]
Да

**Comment by maksalees** [comment]
Примечание: скрыть весь хентай можно в настройках

**Comment by grishiit** [comment]
да скрыл я уже, скрыл :D
