### ISSUE TITLE
Показ комментариев без открытия поста.

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#375]
Не мастер обьяснений, но я крч покажу
1. как НЕ должно быть
![image](https://user-images.githubusercontent.com/46892579/147680138-fbf53b9f-7cd5-4694-af0c-ff5029adc045.png)
2. как ДОЛЖНО быть 
![image](https://user-images.githubusercontent.com/46892579/147680278-93fa5769-9751-4d76-a450-d44bce2b2bae.png) - быстрый доступ к комментариям без перезагруки страницы

**Comment by HSDChannel** [comment]
![image](https://user-images.githubusercontent.com/72506029/147681063-470c350c-9842-40d6-a704-8740a2eaeba1.png)
включай микроблог
