### ISSUE TITLE
[Основной инстанс] Сайт падает в 504 при выборе языка

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#379]
![image](https://user-images.githubusercontent.com/81331307/147781140-614fc175-a093-40e6-90d6-28945d8d352a.png)
Язык выбираю дореволюционный, остальная часть сайта работает.

**Comment by veselcraft** [comment]
Часто запросы идут мейби

**Comment by themohooks** [comment]
> Часто запросы идут мейби

если от всех - не думаю, запись и обновление в базу данных работает
если от меня - вряд-ли, я зашёл на сайт, затем по ссылке внизу на смену языка

**Comment by themohooks** [comment]
всё пришло в норму

**Comment by maksalees** [comment]
Иногда такое бывает у меня. Проблема все таки существует

**Comment by celestora** [comment]
Также такое выбивает при попытке отрепостить с комментарием

**Comment by celestora** [comment]
Проблема оказалась не с OpenVK, а с неправильно настроенным классификатором ддос атак :D

**Comment by themohooks** [comment]
ор
переоткрую иссуй если повторится подобное
