### ISSUE TITLE
Баги в сообщениях

### ISSUE THREAD

**Issue by rekcilwodniw** [OpenVK/openvk#383]
Аватарки с соотношением сторон, отличным от 1:1 растягиваются/сжимаются капец страшно:
![bildo](https://user-images.githubusercontent.com/74169020/147841796-9113a9c2-917c-4fbc-a484-d57b40812261.png)

2022 года не существует впринципе:
![bildo](https://user-images.githubusercontent.com/74169020/147841800-866fd9e8-3429-496c-b0c8-eafdecd31c1b.png)

**Comment by Playez** [comment]
@rekcilwodniw Жалко

**Comment by veselcraft** [comment]
С редизайном это пофикшено, см. https://github.com/openvk/openvk/commit/db3789bef8dce2426f2dbb970ca3c24c9c9f8432
