### ISSUE TITLE
Сделать поиск постов по хэштегу более удобным

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#384]
Надеюсь на этот раз я всё проверил и такого issue нет.
Если это уже опять давным-давно есть, я сто раз извиняюсь.

Сейчас поиск даёт возможность искать только группы и людей.
Функционал поиска не позволяет искать посты по хэштегам, но сами они работают исправно.

**В Mastodon это сделано так:**
![vivaldi_jjQI2bB2jQ](https://user-images.githubusercontent.com/40203830/147856450-046e1ad2-238e-4db2-854d-91c0d291baf2.png)

**В OpenVK это может выглядеть так:**
![vivaldi_ZYVdNHmcPQ](https://user-images.githubusercontent.com/40203830/147856618-953b21c7-672e-42b4-893b-c67ad806ccc9.png)

**Comment by maksalees** [comment]
Искать посты по хештегу возможно если нажать на хэштег в посте. Также это возможно если перейти по адресу `https://openvk.su/feed/hashtag/хэштег`. Определенно стоит для этого сделать более удобный UI.

**Comment by hetrixq** [comment]
@maksalees Лол, не знал
