### ISSUE TITLE
Расписать политику конфиденциальности

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#39]
Пока `/privacy` пустует.

**Comment by mbs0ft** [comment]
https://github.com/openvk/openvk/issues/15

**Comment by mbs0ft** [comment]
https://github.com/openvk/openvk/issues/15

**Comment by WerySkok** [comment]
Хотя бы примерная политика конфиденциальности нужна, потому что движок работает +- одинаково и собирает те же самые данные.

**Comment by ghost** [comment]
Расписано.
