### ISSUE TITLE
QR-код для 2FA не отображается

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#393]
![](https://user-images.githubusercontent.com/60031799/148109406-969a452f-319c-454f-8b2f-e5d7656e346b.png)

**Comment by maksalees** [comment]
Исправлено в [efcaa87](https://github.com/openvk/openvk/commit/efcaa874fb497cffc849ab43a7a83280eea8148c). Забыл в коммите сразу номер иссуя написать)

**Comment by hetrixq** [comment]
@maksalees Жиза
