### ISSUE TITLE
Использовать URI ссылку телеграма вместо t.me

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#395]
Можно допустить тот факт, что где-то может быть заблокирован t.me, поэтому предлагаю вместо него использовать URI ссылку (`tg://resolve?domain=`) в профиле пользователя.

К тому же сам по себе t.me не несёт никакой полезной информации на своей странице.

**Comment by maksalees** [comment]
А если у кого-то нет приложения Telegram?

**Comment by maksalees** [comment]
t.me показывает краткую информацию про аккаунт

**Comment by likhner** [comment]
> А если у кого-то нет приложения Telegram?

В таком случае, что ему даст t.me? Ник он знает уже из профиля OVK, как и имя собеседника. Ну может быть «Don't have Telegram yet? Try it now!» или фото профиля в телеграме это то, что ему нужно.

**Comment by maksalees** [comment]
> > А если у кого-то нет приложения Telegram?
> 
> В таком случае, что ему даст t.me? Ник он знает уже из профиля OVK, как и имя собеседника. Ну может быть «Don't have Telegram yet? Try it now!» или фото профиля в телеграме это то, что ему нужно.

Да, это то что ему нужно

**Comment by celestora** [comment]
> В таком случае, что ему даст t.me?

Возможность нажать на ссылку и сразу открыть Telegram или подробности о профиле, если Telegram отсутствует.


> Можно допустить тот факт, что где-то может быть заблокирован t.me

В любом случае, людей, у которых заблокирован телеграм, гораздо меньше чем тех, у кого его нету или он поставлен как Portable. Думаю что-то в данном случае делать изменение предложенное немного против большинства.
Конечно, можно допустить тот факт, что OpenVK будет развёрнут для соцсети с аудиторей из Санкт-АнтиТелеграмБурга (извините, не знаю где тг заблокан), в таком случае предлагаю ввести новую опцию конфигурации, которая будет менять ссылку t.me на teleg.run, tttt.me etc.

**Comment by likhner** [comment]
> Возможность нажать на ссылку и сразу открыть Telegram или подробности о профиле, если Telegram отсутствует.

Опять же повторюсь. Информацию о собеседнике человек и так уже знает из профиля OVK.

> В любом случае, людей, у которых заблокирован телеграм, гораздо меньше чем тех, у кого его нету или он поставлен

Тем более, тем у кого есть телеграм t.me тоже бесполезен. t.me в любом случае автоматически переводит на URI-ссылку.

> в таком случае предлагаю ввести новую опцию конфигурации, которая будет менять ссылку t.me на teleg.run, tttt.me etc.

Хорошая идея.
