### ISSUE TITLE
Починка сообщений

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#398]
Здраствуйте, уважаемые разработчики OpenVK!
Сообщения не работают уже как 2 неделю выдавая ошибку 502, пора бы и починить ибо проблема актуальна уже вторую неделю

**Comment by veselcraft** [comment]
Скриншот? Зачем каждый раз приветствоваться?

**Comment by bza69299** [comment]
![image](https://user-images.githubusercontent.com/69803074/148349114-49ec2d0b-4a54-4210-ae27-9db52a2fbac1.png)

**Comment by mbs0ft** [comment]
> Сообщения не работают уже как 2 неделю выдавая ошибку 502

Все работает, вроде (не считая того, что растягивается длинная аватарка)

![image](https://user-images.githubusercontent.com/22106304/148375228-c853b9f4-fa46-40f6-a741-7301e6ad2ef0.png)
