### ISSUE TITLE
Пустой альбом и заметка

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#40]
Возможно создать альбом фото и заметку без заголовка. Так же заметки вовсе удалять нельзя.

**Comment by veselcraft** [comment]
https://github.com/openvk/openvk/commit/b08c33e092ddebedc8e251683b9461a939a426cb

**Comment by veselcraft** [comment]
https://github.com/openvk/openvk/commit/b4943685859a9e4d116b0e3717989ca928718482
