### ISSUE TITLE
Срочная починка  NSFW-контента

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#400]
Если зайти во вкладку "мои новости", то NSFW-контент будет показыватся без всяких разрешений, скрин кидать не буду так как на гитхабе порнуха не приемлима

**Comment by bza69299** [comment]
*приемлива*

**Comment by veselcraft** [comment]
В настройках выставляли запрет на отображение NSFW?

**Comment by bza69299** [comment]
да

**Comment by bza69299** [comment]
вроде бы
