### ISSUE TITLE
Отдельный мобильный поддомен (m.openvk.su)

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#401]
Разделение на 2 типа сайта - десктоп (openvk.su) и мобильный (m.openvk.su)
Постоянная смена темы на каждом устройстве раздражает

**Comment by ghost** [comment]
Это никак не связано с самим движком. Закрываю.

**Comment by WerySkok** [comment]
Касаемо самого предложения, я против этого. Я понимаю, что так же работает и оригинальный ВК, но это плохо отражается на UX.
