### ISSUE TITLE
Автоматический выбор темы в зависимости от устройства (мобильная / десктоп)

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#402]
То есть - если я например зайду с компьютера, то основной будет тема для десктопа
А если с смартфона, плашнета, то сайт сам поставит подходящую версию.
![image](https://user-images.githubusercontent.com/46892579/148651096-9c55f993-0240-4d5a-b20d-0247b153d068.png)

**Comment by WerySkok** [comment]
Я думаю, это должна быть следующая вещь после включения мобильной темы в основной исходный код.
