### ISSUE TITLE
Сделать выбор темы для десктопа и мобильной версии раздельными

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#403]

**Comment by ghost** [comment]
Ничего не понял.

**Comment by grishiit** [comment]
щас изменю

**Comment by grishiit** [comment]
ебаные миссклики

**Comment by veselcraft** [comment]
@Ilyaandro ору

**Comment by myslivets** [comment]
Было бы классно вообще сделать каталог тем (для мобильной и ПК-версий) и каждый будет выбирать ту, которая ему нравится :)

**Comment by Nediorg** [comment]
@myslivets Оооооо, это вообще класссно!

**Comment by grishiit** [comment]
Так а если тем для мобилок несколько? Как пользователю их менять, без изменения десктоп версии сайта?

Почему бы не сделать так:
![image](https://user-images.githubusercontent.com/40203830/149717915-71859b88-283f-401a-8035-be069ae99236.png)

**Comment by veselcraft** [comment]
@Ilyaandro См. #424

**Comment by grishiit** [comment]
Вопросов не имею больше
