### ISSUE TITLE
Редактирование левого меню

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#406]
![image](https://user-images.githubusercontent.com/46892579/148708601-97db0678-37ea-4b9e-97d0-4b07678c644e.png)
![image](https://user-images.githubusercontent.com/46892579/148708619-e9338e38-4a10-4a57-aea5-3543d64b7074.png)
Или хотябы переместить вкладки на их места

**Comment by bza69299** [comment]
они раньше такими и были, зачем?

**Comment by ayaaop** [comment]
откопал скриншот
![не изображение](https://user-images.githubusercontent.com/58212796/148937038-0a53693f-5524-40a6-a78e-ed61aef78264.png)
оказывается раньше в вк нельзя было сразу убрать ссылки из левого меню с помощью шестеренки

**Comment by Defenders08** [comment]
@ayaaop Ну да как бы

**Comment by Nediorg** [comment]
> откопал скриншот ![не изображение](https://user-images.githubusercontent.com/58212796/148937038-0a53693f-5524-40a6-a78e-ed61aef78264.png) оказывается раньше в вк нельзя было сразу убрать ссылки из левого меню с помощью шестеренки

я про то, чтоб можно было их перемащать

**Comment by Defenders08** [comment]
@Nediorg Ну да

**Comment by veselcraft** [comment]
есть уже

![image](https://user-images.githubusercontent.com/22993408/183940945-3e5569dd-acdd-4e7d-bf64-ed09607d4f08.png)
