### ISSUE TITLE
Смена кодека на более совместимый

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#41]
Желательно разработать собственный видеоплеер или положиться на уже существующий опенсорсный, а не полагаться на браузерные, потому что они разнятся по функционалу.

**Comment by celestora** [comment]
Но видео проигрывают, да?

**Comment by mbs0ft** [comment]
> Но видео проигрывают, да?

только что с сафари загрузил тестовое видео, не воиспроизводит. искал видео, с сафари на macOS тоже не работает
 ![image](https://user-images.githubusercontent.com/22106304/104111522-747be180-52eb-11eb-8ce8-b6eed51f52a9.png)

**Comment by likhner** [comment]
> только что с сафари загрузил тестовое видео, не воиспроизводит. искал видео, с сафари на macOS тоже не работает

Safari [не поддерживает](https://caniuse.com/ogv) видео формата Ogg/Ogv. Дело не в плеере.

![](https://user-images.githubusercontent.com/60031799/104118527-7ddc6c80-5332-11eb-9bb0-12c0e1e8e468.png)

**Comment by mbs0ft** [comment]
> 
> Safari [не поддерживает](https://caniuse.com/ogv) видео формата Ogg/Ogv. Дело не в плеере.
> 
> 
> 

понял, благодарю за объяснение

**Comment by veselcraft** [comment]
Предлагаю просто сменить кодек на AVC/MP4A

**Comment by celestora** [comment]
Я думаю, что в сафари поддерживается MP3+H.264

пн, 11 янв. 2021 г., 09:35 Vladimir Barinov <notifications@github.com>:

**Comment by ghost** [comment]
Поддерживает.
https://caniuse.com/mpeg4
https://caniuse.com/mp3 / https://caniuse.com/aac

**Comment by C0la149** [comment]
Такая же проблема. 
![Screenshot_20210929_085646_com yandex browser](https://user-images.githubusercontent.com/64633686/135211308-e5f06300-e915-4424-a039-997cc14b4ce6.jpg)
![Screenshot_20210929_090152_com android chrome](https://user-images.githubusercontent.com/64633686/135211814-e971597e-b416-4915-a051-9fa1155a2fd8.jpg)
![Screenshot_20210929_090755_com huawei browser](https://user-images.githubusercontent.com/64633686/135212450-749c8145-167e-48b6-9bdc-fbd7e04c0969.jpg)

Проблема наблюдается с Yandex Browser 21.6.3 также с Google Chrome 92.0.4515.131 и с Браузера Huawei 11.1.1.310
Android 10
Honor 8x
EMUI 10

**Comment by veselcraft** [comment]
Необходима смена кодека на более совместимый

**Comment by vlapskii** [comment]
Ребята, когда смените? Мне на сафари не возможно сидеть, да и пользователям на iPhone думаю тоже.

**Comment by MatroCholo** [comment]
@vladimirlapskiy Ябловоды сасац

**Comment by rudzik8** [comment]
> @vladimirlapskiy Ябловоды сасац

по вкусам не судят
к тому же как это относится к решению ишуя? оффтоп

**Comment by rudzik8** [comment]
тоже оффтоп ._.

**Comment by dsrev** [comment]
_Оффтоп оффтопом, а DeviantArt зачем?_

**Comment by vladimirlapskiy** [comment]
> Оффтоп оффтопом, а DeviantArt зачем?

Аниме рисуночки посматриваю, сохраняю, оцениваю.

**Comment by MatroCholo** [comment]
@vladimirlapskiy Протри экран, весь в пятнах от разводов

**Comment by Defenders08** [comment]
@vladimirlapskiy А я покакал

**Comment by veselcraft** [comment]
Так что же мы будем делать с несовместимым кодеком? Меня волнует то, что он так и не был сменён, после бурной дискуссии здесь, хотя жалуются на это все НЕпкшные юзеры, как и обладатели мобильных смартфонов на шOS и пользователи Safari.

**Comment by Lumaeris** [comment]
_Вместо создания issue я просто перенесу прикол сюда_

Предлагаю переписать скрипт конвертирования видео под вариативность между Theora и VP8, запихав выбор кодека как переменную в какой либо конфиг. С значением по умолчанию на VP8 для большей совместимости, т.к Theora не везде работает.

Это не исправит _данное issue_ для основного экземпляра, однако исправит просмотр видео у всех будущих.

VP8 поддерживается в Safari на который жалуются.

```
Additionally, Safari 12.1 supports the VP8 video codec, in addition to H.264. VP8 support in Safari 12.1 ships on macOS 10.14.4, and it is also available for macOS 10.13.6 and 10.12.6. And it is available in the latest iOS 12.2 release.
```

А также VP8 работает в Android WebView-браузерах.

_осуждаю h264_

Как я понимаю конвертировать все видео на текущем экземпляре не вариант, однако проблему нужно исправить для всех экземпляров что появятся в будущем.

![](https://codeberg.org/OpenVK/openvk/attachments/bb5f4437-b8c2-4904-828c-02c57908cbd2)

_Оригинал: [#13 на Codeberg](https://codeberg.org/OpenVK/openvk/issues/13)_

**Comment by celestora** [comment]
> VP8 поддерживается в Safari на который жалуются.

Есть ли более надёжный источник? Я вижу то, что VP8 и VP9 поддерживаются в сасари, но только в WebRTC, не в <video>, но могу ошибаться.

**Comment by celestora** [comment]
&lt;video&gt;. Как минимум таковы дела с Safari <14 и Safari для iOS

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/185598015-b5700dfc-b4ab-4e43-a9d9-f7d9188c9fe8.png)
![image](https://user-images.githubusercontent.com/34442450/185598074-57f3f049-00c5-4b73-8d27-cafeea3746c2.png)

**Comment by Lumaeris** [comment]
[a](https://github.com/openvk/openvk/issues/41#issuecomment-1220505436), извиняюсь. В любом случае, _тупые яблочные проприерасты_ сами виноваты. Если идти по пути большей совместимости сохраняя свободный кодек то переход на VP8 охватывает большее количество браузеров на ведроиде.

В целом в конфиг можно добавить и выбор между Theora, VP8 и H264. Тем самым оставляя выбор свободности кодека владельцу будущего экземпляра. ~~Фритардам~~ Сторонникам свободных программ Theora & VP8(с пометкой что второй рекомендован для большей совместимости, по крайней мере на Android'e) а ~~тупым проприерастам любителям патентов~~ _другим_ H264.

_[Оригинал](https://codeberg.org/OpenVK/openvk/issues/13#issuecomment-606176)_

**Comment by dogganovich68** [comment]
Ребят, так что нужно сделать-то, чтобы видео заработало на мобилках?)

**Comment by WerySkok** [comment]
Так а почему тикет начинался с плеера а теперь про кодек?

**Comment by celestora** [comment]
> Так а почему тикет начинался с плеера а теперь про кодек?

Потому что софтварно в браузере реализовать кодек, сделав новый плеер нельзя. Нужно кодировать в ином формате. Завтра мб будет fix !! 1

**Comment by celestora** [comment]
Кодек изменён на совместимый

**Comment by tretdm** [comment]
@Lumaeris @celestora вы хоть вообще думали как нативно на старых версиях Android полностью поддерживать MP4? Потому что я вижу, что MP3onMP4 поддерживается только с десятого андроида.

![SCR_20230804_220748_firefox](https://github.com/openvk/openvk/assets/76806170/5b23a2b8-032e-47fc-b8ef-1b98f20d372e)

**Comment by tretdm** [comment]
> https://github.com/openvk/openvk/issues/41#issuecomment-1220505436, извиняюсь. В любом случае, тупые яблочные проприерасты сами виноваты.

Не ну, Google тоже виноват, что запаздывает с решением о добавлении MP3onMP4.

**Comment by tretdm** [comment]
Короче, я предлагаю сделать ещё одну схему кодирования на примере этого issue https://github.com/openvk/openvk/issues/877 и похуй, что неэкономно, зато готовые библиотеки FFmpeg (там поддержка HTTPS еще хуже, приходится мучаться с OpenSSL) при разработке приложений для старых ведроидов станут ненужными.
