### ISSUE TITLE
Совместимая с API ВКонтакте реализация прикрепления медиа к посту

### ISSUE THREAD

**Issue by maksalees** [OpenVK/openvk#414]
Коммит [5d62934](https://github.com/openvk/openvk/commit/5d6293405390420af4616325b83aa0e8b22e4673) добавляет прикрепление медиа к посту через API, но эта реализация не совместима с API оригинального ВКонтакте. Нужно сделать совместимую реализацию

**Comment by ghost** [comment]
Закройте ишуй
