### ISSUE TITLE
Галочка "Соглашаюсь с правилами сайта и политикой конфиденциальности" при регистрации

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#415]
мне кажется стоит такое добавить чтобы пользователи сразу же при регистрации знали о правилах и политике конфиденциальности и потом не спорили с администрацией типа "мы не знали что они существуют". очень популярная практика на многих сайтах

![image](https://user-images.githubusercontent.com/87843378/149651917-d8ce3e55-92d5-4c0d-b771-1f08f4bb5aa9.png)
пометка к концепту: слова "правилами сайта" должны быть ссылкой на /terms, а "политикой конфиденциальности" на /privacy

**Comment by dsrev** [comment]
В таком случае тогда стоит упомянуть политику конфиденциальности (/privacy), хоть это никто не читает в принципе :trollface:.

**Comment by rudzik8** [comment]
> В таком случае тогда стоит упомянуть политику конфиденциальности (/privacy), хоть это никто не читает в принципе :trollface:.

обновил
