### ISSUE TITLE
Скрывание даты регистрации

### ISSUE THREAD

**Issue by id31** [OpenVK/openvk#416]

**Comment by rudzik8** [comment]
зачем?

**Comment by maksalees** [comment]
> зачем?

Как я понял, чтобы мошенникам и пранкерам было удобнее скрывать свои новореги

**Comment by id31** [comment]
> зачем?

┐(´ー｀)┌

**Comment by TAB-q** [comment]
> > зачем?
> 
> Как я понял, чтобы мошенникам и пранкерам было удобнее скрывать свои новореги

Таким как Кузякин :trollface:

**Comment by id31** [comment]
> зачем?

Согласен... Фиговая идейка, нафига я это придумал **┐(´ー｀)┌**

**Comment by id31** [comment]
> > > зачем?
> > 
> > Как я понял, чтобы мошенникам и пранкерам было удобнее скрывать свои новореги
> 
> Таким как Кузякин :trollface: 

:trollface: :trollface: :trollface:

**Comment by celestora** [comment]
> Согласен... Фиговая идейка, нафига я это придумал ┐(´ー｀)┌

Тогда, закрываем?

**Comment by Defenders08** [comment]
@celestora Установка опенвк на frebsd

**Comment by Defenders08** [comment]
@Defenders08 *freebsd

**Comment by WerySkok** [comment]
> Тогда, закрываем?
Закрываем.
