### ISSUE TITLE
Скрывание семейного положение и политических взглядов

### ISSUE THREAD

**Issue by id31** [OpenVK/openvk#417]
Эта штука пригодится для тех у кого нет никакого семейного положения и политических взглядов, потому что ему пофиг на всё это

**Comment by rudzik8** [comment]
![image](https://user-images.githubusercontent.com/87843378/149658175-31dd0456-754e-40e7-87f1-a7d36b86d6b0.png)
![image](https://user-images.githubusercontent.com/87843378/149658182-3003c327-2a2f-476f-80fc-7c3f8f08f362.png)
в чём проблемы чел

**Comment by id31** [comment]
> ![image](https://user-images.githubusercontent.com/87843378/149658175-31dd0456-754e-40e7-87f1-a7d36b86d6b0.png)
> ![image](https://user-images.githubusercontent.com/87843378/149658182-3003c327-2a2f-476f-80fc-7c3f8f08f362.png)
> в чём проблемы чел

Просто мне не нравится как он выглядит, если скрыть было можно тогда было зашибись

**Comment by rudzik8** [comment]
> > ![image](https://user-images.githubusercontent.com/87843378/149658175-31dd0456-754e-40e7-87f1-a7d36b86d6b0.png)
> > ![image](https://user-images.githubusercontent.com/87843378/149658182-3003c327-2a2f-476f-80fc-7c3f8f08f362.png)
> > в чём проблемы чел
> 
> Просто мне не нравится как он выглядит, если скрыть было можно тогда было зашибись

на... зачем???
