### ISSUE TITLE
Прикрепление медиаконтента к посту по ID

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#418]
Очень иронично, что у нас отросла несовместимая и можно даже сказать очень странная реализация прикрепления вещей к посту, но при этом прикрепить по CSV массиву айдишников как в ВК до сих пор нельзя :D
Правда, перед тем, как этим заниматься, стоит разобраться с #266 и улучшить контроль доступа за медиаконтентом пользователя, чтобы API не был дырявым как сапоги.

**Comment by maksalees** [comment]
Частично дубликат #414

**Comment by celestora** [comment]
Скорее, подзадача. К сожалению, в GitHub нет эпиков, только Milestone(
