### ISSUE TITLE
Телефон

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#42]
1) Переместить поле телефона из `/edit` в настройки аккаунта и вообще отключить его показ для всех т.к. оно не работает для большинства пользователей.
2) Прекратить требовать "Телефон" для рейтинга.
3) Добавить поле для указания телефона, не связанное с смс-аутентификацией, в `/edit?act=contacts`

**Comment by veselcraft** [comment]
Надо просто отключить поле для номера телефона, если данные для работы Zadarma не введены

**Comment by veselcraft** [comment]
https://github.com/openvk/openvk/commit/ad2e5ec8cceb099b8af0cda6a08a7c5ea1b5e330

Забыл в коммите номер ишуя написать

**Comment by veselcraft** [comment]
Актуально? Если нет, то закрываю
