### ISSUE TITLE
Переделка логики загрузки контента в Textarea

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#427]
В современных цивилизованных сетях, по типу ВКонтакте, Мастодон, Твиттера, и даже Smithereen, есть такая смешная штука, под названием "загрузка аттачментов через AJAX".

## ~~Нахуй,..~~ Зачем это вообще нужно?
Для ускорения отправки поста. Пока картинка грузится, пользователь успеет ещё написать текста. Таким образом ещё и экономится время.

## Как это работает?
Юзер вставляет пикчу/видос ~~с голыми бабами из геншина~~ к посту, и скрипт автоматом загружает его на сервер с помощью внутренних API. А потом, когда дело дойдёт до постинга, в Form передаётся массив данных с ~~вкусными приколами~~ ссылками или хэшем картинок, айди видео, ~~музыки~~ и тому подобному.

**Comment by veselcraft** [comment]
В `form` формы отправки поста будут `meta`-теги с `name` = `a:{номер}:{тип прикрепления}` и `value` = `{hash загруженной картинки/видео, айди типа [айди юзверя]_[айди фотки/видео] с добавлением решётки в начало, или json данные}`

**Comment by veselcraft** [comment]
Чуть-чуть изменил meta-тег

**Comment by veselcraft** [comment]
> В `form` формы отправки поста будут `meta`-теги с `name` = `a:{номер}:{тип прикрепления}` и `value` = `{hash загруженной картинки/видео, айди типа [айди юзверя]_[айди фотки/видео] с добавлением решётки в начало, или json данные}`

короче в пизду так изощряться, проще движку сразу хавать несколько файлов. в пулле #800 реализация уже есть

**Comment by celestora** [comment]
:)
