### ISSUE TITLE
иконка «нравится»

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#43]
небольшой баг, на постах показывается нормальная иконка, в комментариях показывается встроенное эмодзи 

![image](https://user-images.githubusercontent.com/22106304/104111530-9aa18180-52eb-11eb-9849-0d8c8393bdf3.jpeg)

![image](https://user-images.githubusercontent.com/22106304/104111531-9d03db80-52eb-11eb-9957-fee5a8c88c1b.jpeg)

**Comment by veselcraft** [comment]
https://github.com/openvk/openvk/commit/40c24a69af7c967b6855dc64406ce5d5897496e1
