### ISSUE TITLE
RPC-вызовы (?) возвращают код 400 при попытке проверить уведомления

### ISSUE THREAD

**Issue by SigmaTel71** [openvk/openvk#431]
Спустя несколько минут после загрузки страницы отваливается RPC с ошибкой 400. Как следствие, не работают уведомления о входящих сообщениях.

Vivaldi 5.0.2497.32 (Stable channel) (64-bit), Windows 8.1. Вообще не зависит от браузера и вида подключения к интернет.

![image](https://user-images.githubusercontent.com/17989678/150320568-71fdb765-2985-4fdb-8318-8bd038b34de4.png)
![image](https://user-images.githubusercontent.com/17989678/150320693-9065849b-4027-4657-b6cc-cbf59195a81f.png)

**Comment by celestora** [comment]
400 - код ответа по-умолчанию для таких ситуаций. Просто у вас нет входящих уведомлений, потому что на основном инстансе Kafka не подключили :D

**Comment by WerySkok** [comment]
@celestora по кафке нужны инструкции, напиши для docs.openvk.su

**Comment by SigmaTel71** [comment]
> Просто у вас нет входящих уведомлений, потому что на основном инстансе Kafka не подключили :D

Замечательно.
Тестировал переписку в личке, и даже когда были входящие сообщения, вылетали ошибки 400. Штош, ждём брокер, если будет.
