### ISSUE TITLE
Не показывать NSFW-контент в глобальной ленте по умолчанию

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#433]
NSFW-группам часто предъявляют то, чтобы они скрыли свои посты из глобальной ленты, вот только в таком случае притока подписчиков у них никакого.
в моём понимании компромиссом было бы сделать так

**Comment by MatroCholo** [comment]
@rudzik8 А че сделать то?

**Comment by MatroCholo** [comment]
@MatroCholo Я тупой, извините

**Comment by celestora** [comment]
Ещё актуально?

**Comment by veselcraft** [comment]
естественно

**Comment by celestora** [comment]
https://github.com/openvk/openvk/blob/4d6af6d28e0b3d0a769fa4c96c171d3c6a2a952f/install/init-static-db.sql#L258

А это разве не обеспечивает скрытие NSFW из глобальной ленты по-умолчанию?

**Comment by dsrev** [comment]
Обеспечивает. На моей локалке и на openvk.su по дефолту стоит 0, только что проверил. Без понятия зачем тогда этот issue нужен

**Comment by veselcraft** [comment]
Не актуально, закрываю
