### ISSUE TITLE
PHP Notice: Trying to get property 'identity' of non-object in .../available/openvk/Web/Presenters/OpenVKPresenter.php:255

### ISSUE THREAD

**Issue by DartPower** [OpenVK/openvk#434]
```
PHP Notice: Trying to get property 'identity' of non-object in .../available/openvk/Web/Presenters/OpenVKPresenter.php:255
```

Что это может быть? 
Белая страница с index без контента (пикч и тд)
Я, похоже неправильно устанавливаю. 
Debian 11 Bullseye

**Comment by DartPower** [comment]
Обязательно Chandler конкретно в /opt/ ставить? Просто могу поругаться немного на инструкцию... 
не понятно в каком порядке и как правильно ставить...

**Comment by ghost** [comment]
> Обязательно Chandler конкретно в /opt/ ставить?

Нет, `/var/www` тоже подойдёт.

**Comment by ghost** [comment]
Так и хочется спросить - были ли импортированы SQL дампы, предоставленные Chandler? Их надо было импортировать в первую очередь.

**Comment by ghost** [comment]
Закрываю по причине out of scope
