### ISSUE TITLE
аватарка 18+

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#435]
смотря новые группы, только зарегистрированных людей можно увидеть у них аватарки с не очень приятным содержаниям для всех, пометка аватарка 18+ должна исправить такие канфузы. если вам лень можете дополнить правила

**Comment by veselcraft** [comment]
https://user-images.githubusercontent.com/22993408/150836459-a8fb35e7-a7de-4323-bdd0-e84477f02cb6.mp4

**Comment by bza69299** [comment]
если тебе лень то просто добавь в правила что незя такие авы ставить

**Comment by hetrixq** [comment]
@veselcraft :D

**Comment by hetrixq** [comment]
@bza69299 Так можно, почему нельзя

**Comment by celestora** [comment]
Есть ли итог по этому?
Не похоже, что кому-то нравится эта идея да и заблюривание аватарок это конечно сильно, учитывая что ава это чисто для идентификации собеседника. Хотелось бы закрыть, но тогда @WerySkok будет angery :(

**Comment by WerySkok** [comment]
Так себе идея, можно закрыть
