### ISSUE TITLE
Окно с ошибкой "Не удалось поделиться записью" невозможно закрыть

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#436]
![изображение](https://user-images.githubusercontent.com/58212796/151229106-3c913f63-ac28-4378-bc11-9d02ec2be06b.png)

Кнопки с крестиком нету, и нажатие на любое место это окно не закрывает. Почему?

**Comment by veselcraft** [comment]
Какую запись вы пытаетесь репостнуть? При каких конфигурациях темы эта ошибка возникает?

**Comment by ayaaop** [comment]
Пытался сделать репост записи, которой уже не существует. Тема по умолчанию, никаких кофигураций вроде нет

**Comment by veselcraft** [comment]
Теперь сам с этим столкнулся. Иногда репостит, иногда выводит ошибку

**Comment by celestora** [comment]
> Теперь сам с этим столкнулся. Иногда репостит, иногда выводит ошибку

Он про то, что при ошибке кнопок в диалоге нет, ошибки с репостом это #379
