### ISSUE TITLE
Сделать возможность создания тем юзерами без одобрения админами

### ISSUE THREAD

**Issue by Floduat** [OpenVK/openvk#442]
Сделать мини магазин тем для овк что бы юзерам можно было загружать темы без проверки либо с минимальной в овк.
Пояснение как это должно работать:
Должна быть отдельная страничка с темами которые может загрузить любой к себе в настройки оформления, разработчикам тем надо получить аккаунт создателя тем (можно сделать бэйдж) и загрузить что надо для темы
(если надо еще подробнее скажите в коменты)

**Comment by HueRtx** [comment]
@HueRtx @saddyteirusu

**Comment by WerySkok** [comment]
не легче просто использовать Stylus?

**Comment by Defenders08** [comment]
@WerySkok Так стилус это онли сыы

**Comment by Defenders08** [comment]
@Defenders08 *css

**Comment by Floduat** [comment]
@WerySkok это вне овк, и скорее всего расширение какое-то, не всем такое понравится

**Comment by WerySkok** [comment]
Короче, wontfix. Слишком много рисков безопасности
