### ISSUE TITLE
Расхождение цветовой палитры в окне «Поделиться»

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#447]
Стиль «ВКонтакте 2015», не совпадает заголовок окна и цвет панели навигации. Особенность или баг?
![image](https://user-images.githubusercontent.com/17989678/152030416-37d3602d-280d-441e-8ae9-1c600f43361b.png)

**Comment by hetrixq** [comment]
@SigmaTel71 Это нормально, автор темы должен исправить/доработать

**Comment by celestora** [comment]
Закрываю по причине "out of scope"
