### ISSUE TITLE
Галочка

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#45]
Safari, iOS 13.6
наблюдаю, галочка показывается как квадрат, это на стене, в комментариях 

![image](https://user-images.githubusercontent.com/22106304/104155320-9c546d80-53ef-11eb-9b60-1597b2c62021.jpeg)

в шапке все нормально 
![image](https://user-images.githubusercontent.com/22106304/104155355-b1310100-53ef-11eb-9a1e-caabc88833c3.jpeg)

**Comment by veselcraft** [comment]
Это проблема темы, вопросы к @Defenders08

**Comment by mbs0ft** [comment]
Хотя в FF все ок, это только в сафари
![Screenshot 2021-01-12 at 13 25 55](https://user-images.githubusercontent.com/22106304/104308811-e6198280-54d9-11eb-96a2-ee5c9378429f.png)
![Screenshot 2021-01-12 at 13 25 53](https://user-images.githubusercontent.com/22106304/104308817-e6b21900-54d9-11eb-9fc7-fdf2d1b8236c.png)

**Comment by likhner** [comment]
> Хотя в FF все ок, это только в сафари

Галочка на страницах не зависит от темы.

Будучи в `/feed` действительно отсутствуют два файла от этой темы.
`/themepack/vk2012/0.0.1.0/stylesheet/xmas.css`
`/themepack/vk2012/0.0.1.0/resource/check2.png`
