### ISSUE TITLE
Семейное положение не соответсвует женскому роду.

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#458]
"Не жената" вместо "Не замужем", "Женат" вместо "Замужем", "Влюблен" вместо "Влюблена", "Помолвлен" вместо "Помолвлена".

> изначально опубликовано [здесь](https://codeberg.org/OpenVK/openvk/issues/1) [cd3y](https://codeberg.org/cd3y)

**Comment by SigmaTel71** [comment]
Говорят, этот issue надо закрыть.

**Comment by ghost** [comment]
Найти не мог. Спасибо

**Comment by ghost** [comment]
Проблема не решена на страницах поиска и списка друзей.

![image](https://user-images.githubusercontent.com/55238545/171023203-0b94fc55-d51f-4c8a-805f-48d95c998ce1.png)

![image](https://user-images.githubusercontent.com/55238545/171023219-4ca7ce20-2feb-4504-824f-777edb3ea846.png)

_Оригинал - https://codeberg.org/OpenVK/openvk/issues/1#issuecomment-460436_
