### ISSUE TITLE
В уведомлениях "<a href=" вместо имени упомянутого пользователя.

### ISSUE THREAD

**Issue by HSDChannel** [OpenVK/openvk#464]
![image](https://user-images.githubusercontent.com/72506029/152965393-dab9e57a-688e-4866-bbfd-fc5208604c8a.png)
![image](https://user-images.githubusercontent.com/72506029/152965416-08b38d1c-d380-47a8-b05b-fba13c6b4318.png)

> изначально опубликовано здесь - https://codeberg.org/OpenVK/openvk/issues/5

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/206909749-bc6b1b85-10f3-4c5f-ba1b-a37a7e329d5e.png)
фиксед
