### ISSUE TITLE
Не переведены строчки

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#470]
![image](https://user-images.githubusercontent.com/22106304/153450508-9787c020-d92f-425d-b773-c96d9dcefb34.png)

**Comment by maksalees** [comment]
Дубликат #127

**Comment by mbs0ft** [comment]
ну так арбайтен елки иголки

**Comment by maksalees** [comment]
> ну так арбайтен елки иголки

Арбайтаем. Просто таких непереведенных строк в OpenVK очень много
