### ISSUE TITLE
500 Server Error при создании учетной записи с фамилией из 2 слов

### ISSUE THREAD

**Issue by Endedman** [OpenVK/openvk#475]
![image](https://user-images.githubusercontent.com/88163210/153543545-bf178bc9-89fa-4386-b106-db289bd04009.png)

**Comment by celestora** [comment]
Исправлено в 6966cbb8c54cef917613be4eb34003e0ecef6a7c

**Comment by Endedman** [comment]
@celestora т е я могу заходить под Endedman Anonimus Snusoed?)

**Comment by celestora** [comment]
Нет, но ошибки 500 не будет, будет плашка ошибка невалид имя :D
