### ISSUE TITLE
[Основной инстанс] Загрузка видео не удалась

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#477]
![image](https://user-images.githubusercontent.com/81331307/153640926-d5b1ad9f-fc07-4f00-879a-90f4a14921c4.png)
Адрес файла видео: https://takagi.su/hentai/0c/0c9d4da1db2737ef5d0e0c6a06cd7053917ae1ae84ca6c72bac57ef549446fabd3b7a0e35d76c9da3506862f94766cc19d3517982b425fb1f666dc0e46dfe4de.ogv
Само видео: https://birux.xyz/cdn/IMG_2359.MP4

**Comment by veselcraft** [comment]
По ссылке видео открылось совершенно нормально. Видимо, вы обработки не дождались.

**Comment by themohooks** [comment]
> По ссылке видео открылось совершенно нормально. Видимо, вы обработки не дождались.

мб
