### ISSUE TITLE
Починить темную тему

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#480]
У вас сломалась темная тема ВКонтакте 2015
![image](https://user-images.githubusercontent.com/69803074/154127564-f9797ae5-186c-4ee1-9643-56856cb46dc3.png)

**Comment by veselcraft** [comment]
Это проблемы темы, просьба обращаться сюда https://codeberg.org/HSDChannel/vk2015dark/issues

**Comment by Defenders08** [comment]
@veselcraft А почему мою тему спиздили, а дать фтп чтобы я сам мог починить темы не дают

**Comment by veselcraft** [comment]
> @veselcraft А почему мою тему спиздили, а дать фтп чтобы я сам мог починить темы не дают

Ты очень поздно среагировал. За тебя всё @HSDChannel чинил

**Comment by Defenders08** [comment]
@veselcraft Я с лета прошу дать фтп……..
