### ISSUE TITLE
VK Night: нет фона в панели навигации

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#481]
Self-explanatory. От браузера или устройства не зависит.
![image](https://user-images.githubusercontent.com/17989678/154374005-0bb8bd2e-b4d6-415e-b26c-fe17fe8c8373.png)

**Comment by Defenders08** [comment]
@SigmaTel71 Вроде и не должно быть

**Comment by veselcraft** [comment]
Это проблемы темы, просьба обращаться сюда https://codeberg.org/HSDChannel/vk2015dark/issues

**Comment by SigmaTel71** [comment]
> просьба обращаться сюда

А-ха-ха.
![image](https://user-images.githubusercontent.com/17989678/154421290-4983233f-fa67-4f6c-b394-13ea3288e9b0.png)
