### ISSUE TITLE
Изменение списка фотоальбомов в профиле, как в 2015

### ISSUE THREAD

**Issue by thejenja** [OpenVK/openvk#488]
Сейчас оно имеет вид из 2012 года. Как насчёт обновить её в некоторых темах или сделать настройку во "Внешнем виде".
Пример из ВК 2015 года внизу:

![Безымянный](https://user-images.githubusercontent.com/65224669/154936847-71948fdb-a004-487b-b804-c74f18b56c95.png)

**Comment by celestora** [comment]
Над таким вроде работал @Defenders08 в ~~проприетарном~~ форке Postfeed. Обращайтесь по поводу тем к создателям тем (исключение: OVK Modern, так как кто-то принял решение включить её в core-поставку зачем-то и по какой-то причине)

**Comment by Defenders08** [comment]
@celestora 1. Постфид не был пропитанным, просто не успели доделать и открыть исходники
2. ДАЙТЕ ФТП

**Comment by celestora** [comment]
@Defenders08 ты создал тикет в овк?
