### ISSUE TITLE
Функция жалобы

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#49]
Не работает кнопка "пожаловаться"

![Screenshot 2021-01-12 at 13 19 49](https://user-images.githubusercontent.com/22106304/104308260-0c8aee00-54d9-11eb-969b-a7505dcadbc0.png)

https://user-images.githubusercontent.com/22106304/104308267-0eed4800-54d9-11eb-94e2-1edeb2f1f916.mov

**Comment by ghost** [comment]
Этой функции попросту нет

**Comment by wedytd** [comment]
нету шаблона , или функции как сказал dsrev выше

**Comment by veselcraft** [comment]
Как это будет выглядеть на стороне пользователя:
1. Пользователь 1 нажимает на кнопку "Пожаловаться" под постом, фотографией или видео пользователя 2, набирает комментарий к жалобе, а потом подтверждает её
2. Модератор рассмотривает жалобу, и выполняет одни из следующих действий:
- Делает предупреждение пользователю 2, не удаляя запись
- Удаляет запись и оповещает пользователя 2 о нарушении правил
- Банит пользователя 2
- Банит пользователя 1 за многочисленные невалидные жалобы :trollface: 
3. Пользователь 1 получает уведомление о том, что жалоба рассмотрена (если нет, то ничего в ответ не отправляется, либо [на будущее] о том, что в контенте нарушения не найдены)

Интерфейс у модератора будет построен по принципу Тиндера: На специальной странице показывается контент, на который пожаловались, и кнопка действий, как карать пользователя

**Comment by veselcraft** [comment]
что нам (или @dsrev :trollface:) надо доделать:
- убрать дубликаты репортов в списке, поставив на их место счетчик повторов (т.е. сколько раз жаловались)
- ???
- кнопки назад и далее в самом репорте, чтоб перемещаться по списку репортов, либо сделать автоматическое переключение после действия на другой репорт

**Comment by ayaaop** [comment]
Будет ли возможность пожаловаться на комментарий/заметку/изображение/видео?

**Comment by ayaaop** [comment]
а стоп соре я недочитал

**Comment by rudzik8** [comment]
> Будет ли

не будет, так как ветку забросили :trollface:

**Comment by rencornationers** [comment]
> > Будет ли
> 
> не будет, так как ветку забросили :trollface:

Плохо что забросили. Только что обнаружил спам по страницам от анонима призывающий переходить в 18+ канал в тг. Функцию нужно реализовывать, ибо вещь важная.

**Comment by rencornationers** [comment]
Хотя-бы костылём перекидывать в поддержку ей богу, ну хотя-бы что-нибудь

**Comment by n1rwana** [comment]
Завтра займусь

**Comment by rencornationers** [comment]
@n1rwana, где
![image](https://user-images.githubusercontent.com/47507225/185806549-4d24ff76-10cf-40e5-a5c4-6212e44873a6.png)

**Comment by n1rwana** [comment]
https://github.com/openvk/openvk/pull/634 ¯\\_(ツ)\_/¯
