### ISSUE TITLE
Не ставятся лайки

### ISSUE THREAD

**Issue by kilyabin** [OpenVK/openvk#493]
Браузер: Waterfox
Не ставятся лайки
https://user-images.githubusercontent.com/65072190/155764039-8f143f11-f6dd-40ea-bf84-a2321ad9c851.mp4

**Comment by veselcraft** [comment]
@kilyabin Перепроверьте включенные расширения (вижу, у вас стоит небезопасный AdGuard, лучше используйте uBlock Origin), настройки приватности, в конце концов покажите консоль браузера при попытке нажатия на кнопку лайка

**Comment by hetrixq** [comment]
@kilyabin а на других темах, также?

**Comment by kilyabin** [comment]
спасибо за подсказку, позже попробую

пт, 25 февр. 2022 г., 22:00 Vladimir Barinov ***@***.***>:

**Comment by kilyabin** [comment]
> @kilyabin а на других темах, также?

попробовал другие темы, на них ставятся

**Comment by celestora** [comment]
Закрываем по причине out of scope?

**Comment by shizotoaster** [comment]
У меня та же проблема на Firefox 98.0.1
Стиль VK Night, на других работает

**Comment by celestora** [comment]
Таки закрываем по причине OOS, вопросы по темам к Эшу должны направляться непосредственно к Эшу.
