### ISSUE TITLE
Создаётся аккаунт Chandler (но не OVK) при указании невалидного имени

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#498]
Внезапно заметил это, когда помогал товарищу восстановить его аккаунт

## Как воспроизвести:
Создать аккаунт с неподходящим именем, например `E2r7hN07Fl47`.

## Что происходит:
Вылезает ошибка 500 (на основном инстансе), при этом в бд создаётся запись в таблице ChandleUsers, но не в таблице profiles. Все следующие попытки входа также ведут к ошибке 500.

## Что должно произойти:
Пользователю должна вывестись ошибка, что указано недействительное имя. Регистрация осуществлена не будет.

**Comment by themohooks** [comment]
Что за особенность в фреймворке, что ему обязательно нужны дополнительные аккаунты?
