### ISSUE TITLE
Тег <u> для заметок

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#499]
типа... серьёзно? у нас есть `<b>` для **жирного**, `<i>` для _курсива_, даже `<del>` для ~~зачёркнутого~~ но нету `<u>` для подчёркнутого текста?
было бы неплохо его иметь

**Comment by dsrev** [comment]
HTMLPurifier по какой-то причине больше не принимает тэг `<u>` (мб конфиг фиговый хд), но как альтернативу я сделал новый класс `underline` для подчёркнутых текстов. Данный класс можно использовать с `<span>` и `<p>`.

**Comment by rudzik8** [comment]
хуйня, класс не работает, переделывайте
