### ISSUE TITLE
Возможность запрета пользователям писать в техподдержку.

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#505]
Заблокированные (да и не только) пользователи часто спамят тикетами в саппорт с просьбой разбана, что бесит. Предлагаю добавить возможность агентам запрещать некоторым пользователям открывать новые тикеты в техподдержке.

**Comment by maksalees** [comment]
Забыл это указать в самих коммитах, но решено коммитами [6588734](https://github.com/openvk/openvk/commit/6588734caae0bbeecd583afa2870b320e19e1454) и [f1d923f](https://github.com/openvk/openvk/commit/f1d923f5806455b067d407c93e137b07d1c51def)
