### ISSUE TITLE
[WinNT] Завязанное на shell поведение ломается

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#506]
На винде нет баша, а заливка видео и так далее предполагает, что есть bash и он выбран как шелл по умолчанию.

- [X] Сделать Shell доступным на Windows
- [x] Портировать processVideo.sh

**Comment by SigmaTel71** [comment]
Пора тащить Cygwin в зависимости? 😆 
Вообще есть типа такая фигня, чтобы не грузить всю подсистему: https://sourceforge.net/projects/win-bash/files/shell-complete/latest/

**Comment by hetrixq** [comment]
@celestora !.Кто то на полном серьёзе будет хостить овк на винде?

**Comment by WerySkok** [comment]
Как ты дошёл до того, чтобы беспокоиться об этом?

**Comment by SigmaTel71** [comment]
> @celestora !.Кто то на полном серьёзе будет хостить овк на винде?

Считай меня сумасшедшим, но у меня, например, есть лицензия на Windows Server 2012 R2 Standard, на пять машин. Главное IIS не использовать, а так всё хорошо.

**Comment by celestora** [comment]
https://github.com/openvk/openvk/blob/f4d8908d8067f138421a166d3ebb774dd64e3d73/Web/Util/Shell/Shell.php#L22

https://github.com/openvk/openvk/blob/f4d8908d8067f138421a166d3ebb774dd64e3d73/Web/Util/Shell/Shell.php#L51

Похоже ещё овк опирается на GNU CoreUtils :D

**Comment by hetrixq** [comment]
@SigmaTel71 Капец

**Comment by celestora** [comment]
> Кто то на полном серьёзе будет хостить овк на винде?

Официальный инстанс так делал.

> Как ты дошёл до того, чтобы беспокоиться об этом?

Хочется овк на винде и разрабатывать я могу тока на винде к сожалению. А тут вот захотелось видео потеребить.

**Comment by celestora** [comment]
Алсо с `nohup` попа какая-то(
Не знаю, есть ли такое для pwsh

**Comment by celestora** [comment]
Думаю это уже решено

**Comment by ghost** [comment]
@celestora @celestora
