### ISSUE TITLE
Улучшение раздела "Об этой инстанции"

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#510]
Поправить html?

пример
![o](https://user-images.githubusercontent.com/22106304/159188664-e3bfb3e2-f663-431e-a671-246499e13c60.png)

**Comment by hetrixq** [comment]
Отличная идея, но предлагаю также сделать расширенный топ (а почему нет)
![пикча](https://user-images.githubusercontent.com/64357478/160251834-1a6967d3-bd1b-4307-a0ca-f3beda1c8be5.jpg)

**Comment by mbs0ft** [comment]
> предлагаю также сделать расширенный топ

Тоже можно рассмотреть такой вариант

**Comment by mbs0ft** [comment]
Либо так

![image](https://user-images.githubusercontent.com/22106304/160394496-1e11d8fb-a9ce-48de-abda-028a84b59b0e.png)

**Comment by hetrixq** [comment]
> Либо так
> 
> ![image](https://user-images.githubusercontent.com/22106304/160394496-1e11d8fb-a9ce-48de-abda-028a84b59b0e.png)

так даже лучше
