### ISSUE TITLE
Отсутствие перевода

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#52]
Страница https://github.com/openvk/openvk/blob/master/Web/Presenters/templates/@banned.xml не переведена, а также всё ещё неформально написана (хотя, конечно же, спасибо за моё упоминание).

Возможно есть ещё неадаптированные страницы, но об их существовании я сообщу в отдельной проблеме.

**Comment by wedytd** [comment]
Ржу ,она переведена

**Comment by ghost** [comment]
Файл смотри, там только русский текст

**Comment by veselcraft** [comment]
Вы были верискокнуты)

**Comment by veselcraft** [comment]
Issue устарел, копия #127
