### ISSUE TITLE
Кнопка "Завершить все сеансы"

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#521]
Недавно (Минут 10 назад) я слил свой пароль. В моём случае ничего страшного не случилось, но могут произойти казусы и посерьёзнее. Это натолкнуло меня на мысль, почему бы не выходить со всех устройств после изменения пароля? Да даже просто отдельная кнопка "Завершить все сеансы" в настройках была бы кстати.

**Comment by Artem13327** [comment]
Может уже закроете

**Comment by veselcraft** [comment]
ну впринципе да 👉👈
