### ISSUE TITLE
[Из техподдержки] Внезапное «500» в списке групп

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#522]
Задумано так или не задумано, но [openvk.su/adminer](https://openvk.su/adminer) вываливает сервер в Internal Server Error. Группа с такой ссылкой найдена на 29 странице каталога.
Это группа без названия и с фотоаппаратом на аватарке.

![image](https://user-images.githubusercontent.com/17989678/160669793-3da36a24-aa02-47fe-9c35-0fd62a837c76.png)

**Comment by celestora** [comment]
Закрыто по причине проблема основного инстанса и чуть-чуть движка. Related issue to track: #429
