### ISSUE TITLE
Ошибка 500 при попытке отправить изображение

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#524]
*репортнул @MatroCholo в чат оффтопа (странно, что не OpenVK)*

**Comment by celestora** [comment]
Я извиняюсь, а поподробнее? Или это на всех сообществах?

**Comment by ghost** [comment]
Так, нет, отправка изображений в принципе сломалась. Меняю название issue

**Comment by ghost** [comment]
> Так, нет, отправка изображений в принципе сломалась. Меняю название issue

Не полностью, кстати. Отправка изображения, например, в альбом работает блестяще
