### ISSUE TITLE
Неясная возможность становления агентом тех.поддержки на своём инстансе

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#53]
Это скорее проблема документации, но я так и не понял, какое поле надо поменять, чтобы стать агентом местной техподдержки. Увы, в чате мне так и не дали ответ, анализ кода тоже мало что дал, так что приходится спрашивать тут.

**Comment by wedytd** [comment]
группа тех.под в бд называется OVKSubteno но что делать дальше с ней я так и не понел , добавление пользователя в грурпу ничем не помогло

**Comment by celestora** [comment]
Таки надо добавить юзера в группу. Приведу в пример лакера.

ChandlerGroups:
![image](https://user-images.githubusercontent.com/34442450/104604791-6977d700-5686-11eb-8930-d82a6d79723d.png)

profiles (user):
![image](https://user-images.githubusercontent.com/34442450/104604950-9330fe00-5686-11eb-883c-e63d83aadeff.png)

ChandlerACLRelations:
![image](https://user-images.githubusercontent.com/34442450/104605101-c1164280-5686-11eb-8b08-d3e0a77e40f4.png)

**Comment by WerySkok** [comment]
@rem-pai, а ничего добавлять в `ChandlerACLGroupsPermissions` не надо? Я попробовал как тут, но это не слишком работает.

**Comment by WerySkok** [comment]
`ChandlerUsers`:
![изображение](https://user-images.githubusercontent.com/15957616/104631049-bec6df00-56ac-11eb-90aa-ae361641ca25.png)
`ChandlerGroups`:
![изображение](https://user-images.githubusercontent.com/15957616/104631117-d7cf9000-56ac-11eb-8fa5-887eccf36cb1.png)
`ChandlerACLRelations`:
![изображение](https://user-images.githubusercontent.com/15957616/104631179-f2096e00-56ac-11eb-8f83-b754cde4e0cc.png)
`ChandlerACLGroupsPermissions`:
![изображение](https://user-images.githubusercontent.com/15957616/104631236-08172e80-56ad-11eb-86f7-fabfbe9ae142.png)

Остальные таблицы на Chandler (кроме токенов) пусты. Мне ещё интересно, почему в `ChandlerACLUsersPermissions` поле `context` не может быть NULL и `permission` это число, а не строка, аналогично `ChandlerACLGroupsPermissions`.

**Comment by celestora** [comment]
А что если заменить TicketReply на `openvk\Web\Models\Entities\TicketReply`?

**Comment by WerySkok** [comment]
Эффекта не возымело. Наверное, потому что в исходниках бэкслеши не отражены?

**Comment by celestora** [comment]
Да должны быть отражены. А если context поставить в 0?

**Comment by WerySkok** [comment]
Ого, заработало.
![изображение](https://user-images.githubusercontent.com/15957616/104633152-cb006b80-56af-11eb-9980-b0a425a27ee7.png)
Ну тогда окончательно распишу последовательность действий, необходимых для включения пользователя в тех. поддержку:
1) Создать группу в таблице `ChandlerGroups`. Название (наверное) тут не особо важно, главное запомнить созданный UUID.
2) В таблице `ChandlerACLGroupsPermissions` создать запись, как показано выше, поменяв UUID на тот что из пункта 1.
3) Через таблицу `ChandlerACLRelations` добавить пользователя в созданную группу.

Надеюсь, админка будет допилена, чтобы в будущем не пришлось делать этого ручками.

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/104633381-b8823400-56a7-11eb-8e74-29a3a7bc6d14.png)

**Comment by celestora** [comment]
Осенью посмотрю что можно с этим сделать

**Comment by celestora** [comment]
Закрываю по причине того что исправлено обновлением дампов БД
