### ISSUE TITLE
Лайки, фото, альбомы

### ISSUE THREAD

**Issue by DxJxAxNxGxO** [openvk/openvk#530]
Окунаясь в ностальгию с головой, на нетбуке с windows xp и браузером firefox 52.9 esr наблюдаются проблемы с лайками - они не ставятся, также проблемы есть с фото - не могу добавить фото во вкладку с фото на странице, а также нет альбомов, точнее нет возможности их создания.

**Comment by veselcraft** [comment]
Для корректной работы лайков советуем использовать браузер Mypal, 52 ESR уже как бэ всё.

> не могу добавить фото во вкладку с фото на странице

Сформулируйте проблему корректнее, я не понимаю

> а также нет альбомов, точнее нет возможности их создания.

![image](https://user-images.githubusercontent.com/22993408/161397201-8ef2ea1e-6158-4cbd-8748-4e6668e6e1d4.png)

**Comment by SigmaTel71** [comment]
> а также нет альбомов, точнее нет возможности их создания.

В группах их нельзя создавать.
![image](https://user-images.githubusercontent.com/17989678/161397267-13ca4568-ea54-45e2-8988-b4ad5e7b02e7.png)

**Comment by veselcraft** [comment]
> В группах их нельзя создавать.

можно

![image](https://user-images.githubusercontent.com/22993408/161397322-b68bdc41-a369-4442-8625-b487a342bf91.png)

**Comment by SigmaTel71** [comment]
> можно

Нет, нельзя.
![image](https://user-images.githubusercontent.com/17989678/161397404-30e03399-4068-4a58-af1d-70e0b09ba8be.png)

**Comment by DxJxAxNxGxO** [comment]
Прошу прощения за неточную формулировку вопроса, я про альбомы и фото в группе (есть своя в опенвк тобишь). Заходя во вкладку "все" под графой альбомы - там нет никаких функций, просто баннер, мол нет никаких альбомов

**Comment by MuRaMiHa** [comment]
> Нет, нельзя. 

Полностью поддерживаю.
![image](https://user-images.githubusercontent.com/58396598/161397801-8d9e0e22-b8c5-4440-972c-fd60e0c5332c.png)

**Comment by SigmaTel71** [comment]
А вот насчёт broswer:old я бы подумал, потому что баг с альбомом от браузера не зависит. Vivaldi 5.1.2567.73, он же Chromium 98.0.4758.141.

**Comment by SigmaTel71** [comment]
В каком-то из коммитов исправили, похоже. Если кто-то из мейнтейнеров знает, какой именно, закрывайте.
![image](https://user-images.githubusercontent.com/17989678/162289705-83c38940-f367-4af2-b030-ab8d5fb0e664.png)

**Comment by celestora** [comment]
Скорее всего это 6c0d543d264f07367f1ac9427fea264ddbc004f9
