### ISSUE TITLE
Невозможность использования API на старых девайсах

### ISSUE THREAD

**Issue by E2r7hN07Fl47** [OpenVK/openvk#531]
Предлагаю сделать официальное HTTP зеркало API OpenVK, чтобы можно было его использовать на старых девайсах, где нет поддержки TLSv1 и/или нет новых сертификатов.

**Comment by curoviyxru** [comment]
Не проще ли просто разрешить HTTP на основном инстансе?

**Comment by veselcraft** [comment]
Закрываю, ибо это не относится напрямую к исходникам ОВК. Инстанс можно обсудить в "Обсуждениях" на гх
