### ISSUE TITLE
Дополнения и исправления для уведомлений

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#535]
- [x] Если окно неактивно, то уведомления должны остаться до возвращения пользователя на вкладку
- [x] Добавить в заголовок сайта счетчик пришедших уведомлений (Например: "(2) Vladimír Barinov - OpenVK")
- [x] Сменить звук. Его уже создал @dsrev

**Comment by ghost** [comment]
*создаю

До идеала процесс пока не дошёл

**Comment by celestora** [comment]
Говоря про первую фичу, мне тут во внимание попался интересный фрагментус:
![image](https://user-images.githubusercontent.com/34442450/163680813-006f97af-0626-422e-ae53-775f9531f1b3.png)

Думаю это не сильно рационально, лучше саму проверку реализовать тут:
![image](https://user-images.githubusercontent.com/34442450/163680830-483a260e-6f0a-4f17-8dbb-3e5e9bc4eedd.png)

Например, вставить это в начало
```js
if(document.visibilityState != "visible") return setTimeout(() => {__closeNotification()}, time);
```

Теперь убирание окошка будет откладываться каждый раз, когда страница не видна пользователю, а как только фокус будет возвращён, то ура нотиф закроется.

**Comment by celestora** [comment]
Протестить не могу (лень Kafka поднимать, а на проде тестить или мокать нет настроения), поэтому призываю @veselcraft или @dsrev как участников этого issue попробовать имплементировать данный прикол.

**Comment by ghost** [comment]
Хм, наверное прикольно подключать к этому чела, который просто сделал звук :trollface:

**Comment by SigmaTel71** [comment]
> лень Kafka поднимать

*сгорел на хер*

**Comment by celestora** [comment]
Вот держите патч: https://github.com/openvk/openvk/commit/0657e1c00ee421a6dc2c392b553e34a948fbfc7b.patch
