### ISSUE TITLE
Не работает видео

### ISSUE THREAD

**Issue by DxJxAxNxGxO** [openvk/openvk#536]
В openvk не работает видео, браузеры firefox 52.9 esr и пельмень, пишет "формат видео или тип MIME не поддерживается", ну и на английском, соответственно.

**Comment by veselcraft** [comment]
используйте последние версии браузеров

**Comment by DxJxAxNxGxO** [comment]
На Хрюше последние версии не попользуешь особо( Так-то пельмень (Mypal) последней версии вроде. Нет, а в чём собственно проблема? Раньше всё работало...
