### ISSUE TITLE
Не отображается капча при регистрации на старом браузере

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#538]
ОС: Windows 10
Браузер: Firefox 5
![image](https://user-images.githubusercontent.com/81331307/163025108-f9cae18b-7569-4aa8-91cf-00c37b650216.png)

**Comment by WerySkok** [comment]
> Firefox 5

Обновите браузер.

**Comment by themohooks** [comment]
> > Firefox 5
> > Обновите браузер.

так сайт же ориентируется и на старые браузеры, нет?

**Comment by veselcraft** [comment]
@themohooks ноуп

**Comment by themohooks** [comment]
> @themohooks ноуп

(((

**Comment by ghost** [comment]
@veselcraft а в чём тогда смысл овк? Раз его в основном пилили для старых устройств

**Comment by veselcraft** [comment]
@codifin это косплей закос под старый вк если че

**Comment by WerySkok** [comment]
Цель ОВК - имитировать стиль старого ВК. Остальная поддержка легаси приоритета не имеет.

**Comment by ghost** [comment]
@veselcraft а ты ж даже в своём ролике сказал что это соц сеть для винтажных пк))))))))))))))

**Comment by SigmaTel71** [comment]
> @veselcraft а ты ж даже в своём ролике сказал что это соц сеть для винтажных пк))))))))))))))

«Вы не так поняли». © Мединский.
