### ISSUE TITLE
Плашка о незаюзанных голосах

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#539]
![image](https://user-images.githubusercontent.com/34442450/163253077-60b6e21c-d9b9-4666-b8ce-0df2c197f140.png)

хочу

**Comment by hetrixq** [comment]
@celestora Тоже хочу

**Comment by itsv1eds** [comment]
а можно мне голоса

**Comment by itsreallyv1eds** [comment]
@itsreallyv1eds да
