### ISSUE TITLE
Кроп изображений

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#54]
Если открыть фото в полном размере, все ок:
![Screenshot 2021-01-14 at 22 11 29](https://user-images.githubusercontent.com/22106304/104643804-9becf880-56b5-11eb-99b3-0c57687c2c3d.png)

Если смотреть на пост (предпросмотр фото?), то изображение искажается:
![Screenshot 2021-01-14 at 22 11 42](https://user-images.githubusercontent.com/22106304/104643851-b0c98c00-56b5-11eb-8c64-b59532636a34.png)
![Screenshot 2021-01-14 at 22 13 20](https://user-images.githubusercontent.com/22106304/104643869-b8893080-56b5-11eb-8534-dfbe57897aad.png)

**Comment by veselcraft** [comment]
Искажение происходит из-за:
1. #17
2. Браузера, который не умеет сглаживать изображения при их сжатии

**Comment by WerySkok** [comment]
Не похоже ли это на артефакты браузера?
