### ISSUE TITLE
Добавить поддержку php8.0, php8.1

### ISSUE THREAD

**Issue by semyon492** [OpenVK/openvk#540]
Актуальная версия php 8.0 и выше

**Comment by WerySkok** [comment]
Дубликат #145

**Comment by Endedman** [comment]
@semyon492 Не требуется.

**Comment by SigmaTel71** [comment]
Обноводрочеры идут в VK Group.

**Comment by celestora** [comment]
@semyon492 У нас есть задачи поважнее.

**Comment by semyon492** [comment]
php8 открывает новые возможности + исправляются баги

**Comment by ghost** [comment]
Ладно.

**Comment by celestora** [comment]
Эти новые возможности действительно крутые, но OpenVK ещё слишком маленький, чтобы менять минимальную версию на PHP8. Более того, у нас нет ресурсов эти возможности внедрять.
В итоге мы всё равно будем вынуждены делать проект совместимым с PHP7.3 => будем без новых фич. О критических багах волноваться рано, у нас есть ещё 7 месяцев поддержки. А за эти 7 месяцев нам много чего делать надо помимо обновления всего, что отвалится.
Грустно, конечно, но такова жижнь, прийдётся задуматься о совместимости с новой версией чуть попозже. А учитывая атмосферу в проекте я даже не сомневаюсь что совместимости с восьмым пыхом у нас не будет и после EOL.

**Comment by celestora** [comment]
Начать стоит с поиска замены или переписывания пакетов без мейнтейнеров, которые 8 пых не поддерживают. Думаю сама кодовая база ОВК к 8 пхп готова, но зависимости -- не совсем. Хотя даже они могут быть готовы, да вот тока если мейнтейнер сдох/поехал на войну/исчез/нашёл проект получше, то хд у него в composer.json будет версия 7 и fug :ddd
