### ISSUE TITLE
Дополнения и исправления для RSS

### ISSUE THREAD

**Issue by grishiit** [OpenVK/openvk#553]
Список того, что облегчило бы использование RSS

- [x] Поменять название ленты с
 
```
<channel>
 <title>OpenVK</title>
```
    
На

```
<channel>
 <title>Группа/ФИО - OpenVK</title>
```
 
Или просто

```
<channel>
 <title>Группа/ФИО</title>
```
 
- [x] Поменять оглавление "статей" на первую строчку из поста
- [x] Сделать поддержку глобальной ленты новостей
- [x] Реализовать отображение изображений
- [x] Убрать/Изменить ограничение в 10 постов**

**Comment by ghost** [comment]
Добавлена поддержка rss в wall.get и newsfeed.getGlobal (нужно передать параметр &rss=1)
