### ISSUE TITLE
Добавить возможность закрывать профиль в овк.

### ISSUE THREAD

**Issue by vlapskii** [OpenVK/openvk#559]
В связи с последними событиями в мире, думаю что, возможность закрывать профиль в овк от всех, кроме друзей. Была бы очень полезной пользователям, которые хотят сказать свою точку зрения по поводу вторжения России в Украину, но боятся это делать, так как могут сдать ура-патриоты увидевшие пост в общей ленте, или может быть проиндексировано, т.д.

**Comment by hetrixq** [comment]
@vladimirlapskiy профиль овк можно закрыть
Если речь про скрытие постов ото всех, то ишшуй составлен, как всегда, некорректно

**Comment by vlapskii** [comment]
> @vladimirlapskiy профиль овк можно закрыть
> Если речь про скрытие постов ото всех, то ишшуй составлен, как всегда, некорректно

Я предлагаю сделать функцию как у ВК, чтобы одним кликом можно было оставить минимум инфы в публичном пространстве.
