### ISSUE TITLE
Уведомление о Cookie-файлах не скрывается окончательно

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#560]
![image](https://user-images.githubusercontent.com/81331307/170736362-acbd760f-d867-41e1-a7de-f055270ef849.png)
оно скрывается на ~сутки, потом снова появляется

**Comment by SuperErnD** [comment]
Возможно сделали срок годности куки который типо ```Согласен с куки``` на +- день, хоть и не точно, но меня лично это не бесит, может кого-то бесит, но это всего-лишь догадки, точно не знаю

**Comment by themohooks** [comment]
> Возможно сделали срок годности куки который типо `Согласен с куки` на +- день, хоть и не точно, но меня лично это не бесит, может кого-то бесит, но это всего-лишь догадки, точно не знаю

меня это раздражает, я уже дал согласие на обработку куки, не надо меня переспрашивать

**Comment by SuperErnD** [comment]
> > Возможно сделали срок годности куки который типо `Согласен с куки` на +- день, хоть и не точно, но меня лично это не бесит, может кого-то бесит, но это всего-лишь догадки, точно не знаю
> 
> меня это раздражает, я уже дал согласие на обработку куки, не надо меня переспрашивать

ну так получилось
что-же поделать

**Comment by SigmaTel71** [comment]
На официальном кластере (возможно) [не настроено](https://support.cloudflare.com/hc/en-us/articles/200170786) раскрытие IP-адреса при подключении через Cloudflare, по этой причине даже повторно появляется сообщение о cookie-файлах.

**Comment by celestora** [comment]
Как IP адрес связан с локальной кукой?😳
