### ISSUE TITLE
Некорректная работа показа последнего визита пользователя

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#561]
Пользователь вчера зарегистрировался в 23 часа, но заходил в 1 час ночи уже сегодняшнего дня, не вчерашнего.

![image](https://user-images.githubusercontent.com/60743585/170815769-3d081def-5101-4fe4-8adf-a3f92dff2257.png)

**Comment by SuperErnD** [comment]
> Пользователь вчера зарегистрировался в 23 часа, но заходил в 1 час ночи уже сегодняшнего дня, не вчерашнего.
> 
> ![image](https://user-images.githubusercontent.com/60743585/170815769-3d081def-5101-4fe4-8adf-a3f92dff2257.png)

о данилка, ку(знаю оффтоп)

**Comment by veselcraft** [comment]
@SuperErnD здороваться будете в лс

**Comment by SuperErnD** [comment]
> @SuperErnD здороваться будете в лс

исправляюсь

**Comment by veselcraft** [comment]
дубль #467
