### ISSUE TITLE
Макет процесса удаления аккаунта на сайте

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#562]
![image](https://user-images.githubusercontent.com/60743585/170816453-30008094-7ea7-405e-bd98-a39bd75375e4.png)

![image](https://user-images.githubusercontent.com/60743585/170816415-ce4888d8-d827-48bb-8b1d-7c36e7d73cd8.png)

![image](https://user-images.githubusercontent.com/60743585/170816424-2d511e3b-0478-4651-9e96-36cd3528ae3e.png)

**Comment by ghost** [comment]
Вторая страница уже выполнена в виде отдельного окошка на подобии "Поделиться", но могу сделать в виде страницы.

**Comment by veselcraft** [comment]
А вот и не надо отдельной страницой, раз уж и так готово
