### ISSUE TITLE
Добавление кнопки `Жалоба`

### ISSUE THREAD

**Issue by SuperErnD** [OpenVK/openvk#565]
иногда где-то в `Мои Новости` могут быть люди которые что-то нарушают или патриоты,(седня видел патриотов украинцев,вчера российских, ну точнее в чате дискорд сказали `когда заблокируют https://openvk.su/айдигруппы`), администраторы могут не сразу найти а так как сообщество овк +- большое то и людей нарушающие правила могут присутствовать а админы не могут сразу сразу отследить и иногда уже эти нарушители могут что то сделать а так как сообщество большое(как упоминал выше) могут найти этих нарушителей и подать жалобу, а админы в свою очередь могут просмотреть жалобу и либо подтвердить либо отклонить, если человек много фейк жалоб отправит то его могут лишить право кидать жалобы
P.S. простите если уже такое есть или это безсмыслено
Спасибо

**Comment by SuperErnD** [comment]
Поправка не найти а увидить случайно

**Comment by ghost** [comment]
Работа над жалобами ведётся, хоть и не так часто вводятся изменения в код функции. Пока могу предложить только создавать обращения в разделе "Помощь" внутри инстанции.

Дубликат #49.
