### ISSUE TITLE
Шатдаун инстанса на время технических работ

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#566]
Было бы неплохо с админки отключать инстанс на техработы (т.е повесив на сам сайт заглушку, что щас идут технические работы).
Закройте иссуй, если уже такое есть

**Comment by celestora** [comment]
touch $OVKROOT/update.pid

**Comment by veselcraft** [comment]
> touch $OVKROOT/update.pid

Да, только оно не так гламурненько выглядит( Юзер наоборот в штаны наложит, если эту надпись увидит
