### ISSUE TITLE
Функция "Читать далее"

### ISSUE THREAD

**Issue by rencornationers** [OpenVK/openvk#570]
![image](https://user-images.githubusercontent.com/47507225/170881956-7b700c3a-4a8d-4ca5-8000-b4e755ccf983.png)

Если пост слишком длинный, то его может быть довольно трудно читать. Он так-же может мешать обзору страницы пользователя. Функция "Читать далее" была-бы очень кстати.

Видел несколько раз на страницах у пользователей подобные длинные посты состоящие из пробелов и надписи в конце... выглядит ужасно.

**Comment by celestora** [comment]
_Читать подробности в источнике..._
