### ISSUE TITLE
В "Заметках" отсутствуют закругления

### ISSUE THREAD

**Issue by rencornationers** [OpenVK/openvk#573]
![image](https://user-images.githubusercontent.com/47507225/170882799-a041eec5-f125-4f17-9e78-bf9e129f5d69.png)
![image](https://user-images.githubusercontent.com/47507225/170882971-cd7b5135-8363-40b9-9a2c-b3ce149480a9.png)
![image](https://user-images.githubusercontent.com/47507225/170882815-507a3137-df4c-47fc-aea3-93d2b8bc0fe9.png)

Несмотря на то что отображение аватаров в настройках внешнего вида выставлено как "круглое", в "заметках" пользователей аватары отображаются без закруглений.

_+_ если перейти в какую-либо из заметок, то аватар и вовсе пропадает (Возможно, так и нужно, но тогда другой вопрос, зачем аватар тогда нужен в списке заметок? У нас-же ведь нету какой-нибудь "ленты заметок" в которой-бы складывались-бы все заметки пользователей и чтобы отличать авторов требовались-бы аватары)

**Comment by veselcraft** [comment]
> если перейти в какую-либо из заметок, то аватар и вовсе пропадает

Задумано дизайнерами прошлого контакта

> зачем аватар тогда нужен в списке заметок? 

Если (в будущем) автор не будет один
