### ISSUE TITLE
Заголовки страниц смещены

### ISSUE THREAD

**Issue by rencornationers** [OpenVK/openvk#574]
![image](https://user-images.githubusercontent.com/47507225/170883219-2d89e317-cd7e-4485-88ca-b19bc2ccd9b9.png)
![image](https://user-images.githubusercontent.com/47507225/170883307-7c1f6333-ca32-427a-83fa-fe9df0f04b9e.png)
![image](https://user-images.githubusercontent.com/47507225/170883525-b7ed9dc4-ade3-4209-ada5-ca372e1681ae.png)

Если присмотрется к заголовку любой страницы (Будь-то пользователь, настройки и т.д.) то можно заметить что он смещен на пиксель. Это работает в большинстве стилей кроме таких как "Природа" в котором такой проблемы не возникает, "Space Pink" и "Modern" в котором ситуация выглядит иначе (третий скриншот)

Так-же, на втором скриншоте можно заметить что линия заголовка и линяя выделяющая контент не сходятся (а в некоторых темах и вовсе отличаются или отображаются как-то по своему. В данном случае используется тема "2015"). Лучше всего это можно заметить сравнивая эти две страницы: https://openvk.su/note1316_1 и https://openvk.su/notes3

**Comment by celestora** [comment]
По поводу тем обращайтесь напрямую к авторам тем или на форум: https://forum.openvk.su/

**Comment by rencornationers** [comment]
> По поводу тем обращайтесь напрямую к авторам тем или на форум: https://forum.openvk.su/

Это проблема не дополнительных тем, а впринципе основного дизайна сайта.

В основной теме OpenVK которая у всех превоначально открывается, появился данный недочёт, а за них подтянулись и кастомные темы, ибо на основой теме они основываются

**Comment by rencornationers** [comment]
Что интересно, на разных страницах этот недочёт отображается по разному... Но суть одна, и дело не в том какую тему я использую.

**Comment by celestora** [comment]
Мне не удаётся воспроизвести этот недочёт на основной теме. Мб дело в том что у меня моник 720р.

**Comment by rencornationers** [comment]
Предполагаю что дело может быть в том, "тень" есть отдельно на заголовке страницы, и отдельно на линии выделяющей содержимое. По итогу получается так что когда в кастомных темах убирают тень с содержимого, тень с заголовка не убирается.
![image](https://user-images.githubusercontent.com/47507225/183146629-739aefb5-96c4-4cd5-b46c-0d6ab272c4d7.png)


Попробовал ещё раз посмотреть что там в основной теме сейчас - обнаружил что всё теперь выглядит как надо (вроде)
![image](https://user-images.githubusercontent.com/47507225/183146615-a7dc9de9-754b-47bf-8edb-8614accb94bf.png)

**Comment by rencornationers** [comment]
Странно всё это...
