### ISSUE TITLE
"Поиск" в некоторых стилях смещен

### ISSUE THREAD

**Issue by rencornationers** [OpenVK/openvk#575]
![image](https://user-images.githubusercontent.com/47507225/170883879-457ae5a9-dfc0-48c6-983d-969a506a3961.png)
Поле поиска в стилях размещающих поиск рядом с лого смещено немного вверх.

В стиле "2012" под поиском и вовсе какая-то линия:
![image](https://user-images.githubusercontent.com/47507225/170884031-83761641-5445-400f-91aa-51abe781373d.png)

Сам-же поиск немного неправильной высоты. Вот для сравнения скриншот из старого ВКонтакте 2015-го года:
![image](https://user-images.githubusercontent.com/47507225/170884164-a842520a-ed8b-438d-90b9-5ce09dd6d862.png)

В более ранней версии ВКонтакте, тоже, поиск был темного другой высоты:
![image](https://user-images.githubusercontent.com/47507225/170884190-62a3c33e-2b39-40a0-aa58-613fd1f0307e.png)

**Comment by veselcraft** [comment]
out of scope, обращайтесь к авторам тем
