### ISSUE TITLE
Смайлы 'Колобки'

### ISSUE THREAD

**Issue by saursvepur** [OpenVK/openvk#576]
Хотел бы вкладку смайлов 'Колобков' на стене (wall) и в сообщениях (Messanger)

**Comment by veselcraft** [comment]
да вы заебали с этими колобками

их не было в ориг вк и не будет!!!!!!!!!!!!

**Comment by saursvepur** [comment]
Ладно

**Comment by hetrixq** [comment]
@veselcraft в ориг вк много чего не было, а в овк есть. Почему бы не сделать как опцию?

**Comment by celestora** [comment]
Дубликат #249
