### ISSUE TITLE
Транслитерация имён на английском имеет символы расширенной латиницы.

### ISSUE THREAD

**Issue by ghost** [openvk/openvk#580]
Возможно не стоит в транслитерации имён на английский использовать расширенную латиницу, которая используется в основном в других языках, а в английском алфавите отсутствует вовсе.

Тут например почему то используется чешская Š вместо английской диграфы Sh. И чешская Č вместо английской диграфы Ch.

Убрать расширенную латиинцу в английском и оставить в языках где она используется.

![image](https://user-images.githubusercontent.com/55238545/171123060-9a327a10-9902-4b76-9955-1e53d84cae2f.png)

![image](https://user-images.githubusercontent.com/55238545/171123080-a22afe54-1dc8-451f-9432-a4d3f162a34d.png)

![image](https://user-images.githubusercontent.com/55238545/171123105-ea75deb0-6a8e-4a46-abd5-9ca68e62cdfa.png)

_Оригинал: https://codeberg.org/OpenVK/openvk/issues/11 от [@cd3y](https://codeberg.org/cd3y)_

**Comment by ghost** [comment]
Related to GH-549

**Comment by veselcraft** [comment]
~~ебать ты лингвист~~ предлагаю сделать это опцией, ибо это скорее скорее персональные приколы нежели глобальные

мне вот нравится чешская транслитерация, например

**Comment by celestora** [comment]
Мне тоже, но думаю она уместной является только в чешском языке. Позыркайте кто-нибудь, может `Any-Latin; Latin-Ascii` получше вариантом будет.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/55238545/171154690-673d6f03-cc94-47e7-bef7-9e5cf5421cdd.png)

Почти ничего не изменилось

**Comment by ghost** [comment]
Покопавшись по айдишникам Транслитератора я нашёл `Russian-Latin/BGN`, который подходит идеально

![image](https://user-images.githubusercontent.com/55238545/171159991-d1db9768-483d-447b-8d94-03c3c00eefd8.png)
