### ISSUE TITLE
Блокировка к разделу "Поддержка" НЕ блокирует возможность оставлять комментарии к тикетам

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#584]
жесть

**Comment by maksalees** [comment]
Я думаю что это нормальное поведение, так как перед блокировкой можно просто закрыть все обращения

**Comment by celestora** [comment]
Оно может быть и нормальное, но точно неочевидное. Может быть, стоит добавить уведомление об этом или опцию закрыть обращения автоматом, на случай если пользователь отборный серун?

**Comment by ghost** [comment]
Опция не помешала бы
