### ISSUE TITLE
Не меняется пароль от страницы

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#586]
Пишет аля "Старый пароль не совпадает", хотя блин я его точно помню, даже с автозаполнения данные брал и всё такая же хохма =))))))))))

**Comment by celestora** [comment]
Не удалось воспроизвести(

**Comment by Lumaeris** [comment]
Актуально?

**Comment by sdzkHelince** [comment]
Пару дней назад поменял несколько раз пароль, всё ворк, не актуально

**Comment by sdzkHelince** [comment]
либо даня рукожоп

**Comment by Lumaeris** [comment]
@myslivets ?

**Comment by myslivets** [comment]
> @myslivets ?

не актуально, фикш.........

**Comment by veselcraft** [comment]
антиактуально
