### ISSUE TITLE
Ошибка при отправке подарка c emoji в тексте сообщения

### ISSUE THREAD

**Issue by sleroq** [OpenVK/openvk#587]
<details>
    <summary>
      Демонстрация
    </summary>
    <img src="https://user-images.githubusercontent.com/52239427/172575818-a6227816-0b4b-4403-9256-a65d744bf383.png" alt="">
    <img src="https://user-images.githubusercontent.com/52239427/172575841-e7e6593a-ec71-4923-a315-efaf2c15a2e9.png" alt="">
  </details>

**Comment by Lumaeris** [comment]
![image](https://user-images.githubusercontent.com/10499845/175573436-01cf7848-c1ef-43db-b26a-049b8dd6ec87.png)

Исправлено. Достаточно было поменять кодировку в таблице 🤔
