### ISSUE TITLE
Дата обновления альбома показывает только дату создания

### ISSUE THREAD

**Issue by Nelyfa** [OpenVK/openvk#588]
При обновлении фотоальбома дата обновления почему-то берется с даты регистрации страницы а не как надо.

![image](https://user-images.githubusercontent.com/22993408/173196768-e76ce613-f38c-4f2d-8903-9536f79c41cf.png)

**Comment by veselcraft** [comment]
не обязательно было кидать пикчу через другой сервис

**Comment by Nelyfa** [comment]
> не обязательно было кидать пикчу через другой сервис

Ещеб знать как эти картинки на ваш гит заливать с телефона. Не нашел кнопки загрузки изображений.

Она мне при создании данного топика не показывалась.
