### ISSUE TITLE
"Отправить сообщение" должно быть с большой буквы

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#590]
да, опять микроишуй

![image](https://user-images.githubusercontent.com/87843378/173734545-4d45786f-94b0-44e3-a706-99d59b132df9.png)

**Comment by SigmaTel71** [comment]
Баг лежит [здесь](https://github.com/openvk/openvk/blob/master/Web/Presenters/templates/@listView.xml).

**Comment by SigmaTel71** [comment]
Тут скорее в другом вопрос — не является ли _заглавная_ буква багом, потому что в группах все опции со строчной.
![image](https://user-images.githubusercontent.com/17989678/175826622-98f6a668-802a-484b-a211-6a0459f45b13.png)
