### ISSUE TITLE
Невозможно зарегистрироваться со своим именем 

### ISSUE THREAD

**Issue by dailrus** [OpenVK/openvk#599]
Ошибка о нереальном имени при использовании фамилии "Офицеров"

**Comment by hetrixq** [comment]
@dailrus Используй другую фамилию, а затем смени на свою))

**Comment by n1rwana** [comment]
Не воспроизводится.
https://openvk.su/id9533

**Comment by veselcraft** [comment]
Вроде как древний issue, который давно исправили
