### ISSUE TITLE
Вкладка "Заявки" при просмотре друзей чужого пользователя

### ISSUE THREAD

**Issue by myslivets** [OpenVK/openvk#605]
щто

![image](https://user-images.githubusercontent.com/60743585/175155674-3b51d77f-59ba-4708-b6c2-e6dd6257ede6.png)

![image](https://user-images.githubusercontent.com/60743585/175156367-4ef7ef98-86f8-4f26-9e18-42afbbe1bea7.png)

**Comment by luneedev** [comment]
@myslivets мне кажется там надо назвать вкладку "Подписчики"

**Comment by celestora** [comment]
Это чтобы показать юзерам замечательную ошибку
