### ISSUE TITLE
Вызов API-функции НЕ пробуждает аккаунт в онлайн

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#606]

**Comment by celestora** [comment]
А мы и не ВК, чтобы вызов некоторых функций пробуждал аккаунт.

**Comment by themohooks** [comment]
> А мы и не ВК, чтобы вызов некоторых функций пробуждал аккаунт.

а как же альтернативные клиенты?
будет странно и нелогично

**Comment by veselcraft** [comment]
Да пусть у нас будет невидимка, че вы...

**Comment by NoPlagiarism** [comment]
> celestora: А мы и не ВК, чтобы вызов некоторых функций пробуждал аккаунт

Пофикшено в https://github.com/openvk/openvk/commit/2ffa4fd916f8c2904a81ec9ec5f7972a89783e8e

Вызов `Newsfeed.get` и `Messages.send` выводит акк в онлайн

Параметр `forGodSakePleaseDoNotReportAboutMyOnlineActivity` исправляет это
