### ISSUE TITLE
Почините тему вконтакте ночь 2015

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#608]
[user-images.githubusercontent.com/69803074/152197085-ad9deed0-2641-4f37-8dfa-77c81b32da74.png](https://user-images.githubusercontent.com/69803074/152197085-ad9deed0-2641-4f37-8dfa-77c81b32da74.png)
почему.....

**Comment by rudzik8** [comment]
потому что
это адресуется не сюда а в поддержку инстанса где была найдена проблема
тут размещается только сам OpenVK

**Comment by Lumaeris** [comment]
Обращайтесь к авторам темы. Это никак не относится к самому движку.

**Comment by bza69299** [comment]
> потому что это адресуется не сюда а в поддержку инстанса где была найдена проблема тут размещается только сам OpenVK

![image](https://user-images.githubusercontent.com/69803074/175474217-6601aa80-a307-4ef0-8784-b755a9e9b844.png)

**Comment by rudzik8** [comment]
> ![image](https://user-images.githubusercontent.com/69803074/175474217-6601aa80-a307-4ef0-8784-b755a9e9b844.png)

с работой сайта, а не темы
к тому же это блять от третьего февраля ответ ты совсем
