### ISSUE TITLE
Отдельная галочка для фан групп/сообществ

### ISSUE THREAD

**Issue by Nelyfa** [OpenVK/openvk#611]
Предалагаю сделать отдельную галочку для фан групп/сообществ которая выдавалась бы фан группам/сообществам если создатель группы/сообщества верефицирован на ovk.

**Comment by themohooks** [comment]
@TildaRu нахуя

**Comment by hetrixq** [comment]
@TildaRu Зачем

**Comment by Nelyfa** [comment]
> @TildaRu нахуя

Защита от особых деградов(осуждаю), которые бы требывали бан фан сообщества. Типа вроде что-то с причиной что мол сообщество/группа вводит своим контентом в заблуждение.

**Comment by hetrixq** [comment]
@TildaRu Автор анимепаблика знает толк в эпитетах

**Comment by EdwardChest** [comment]
@TildaRu тогда и модеров добавлять надо
