### ISSUE TITLE
Увеличить максимальную длину названия сообщества

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#612]
В ВК можно написать название сообщества до 48 символов, а в ОпенВК 32, по моему это мало

**Comment by Defenders08** [comment]
@ayaaop +

**Comment by hetrixq** [comment]
@ayaaop а зачем

**Comment by ayaaop** [comment]
Из за ограничения в опенВК нельзя создавать такого рода группы, а в вк можно (или можно было)
![изображение](https://user-images.githubusercontent.com/58212796/176463493-9f9600fc-d8ed-4547-ba43-d88ec076f030.png)

**Comment by myslivets** [comment]
Можно было, до 2012 года

**Comment by celestora** [comment]
В примере 255 символов, но никак не 48

**Comment by celestora** [comment]
Вообще вся соль в этой строчке:
https://github.com/openvk/openvk/blob/cb902b77684192c6efce99c7959ccd06b9467567/Web/Models/Entities/Club.php#L70

Так-то в овк поддерживаются продолговатые названия сообщества и на уровне БД и везде, только тут приколюха такая стоит. Я предполагаю сделано это было из-за того что из-за длинных названий леяут овк плыл, но с момента появления ugc-table и различных мер, данный костыль больше смысла не имеет. В идеале стоит его убрать из `Club::getName` и выборочно применять в шаблонах (например в админке и странице юзера, там надо, в остальных случаях уже неть).

**Comment by veselcraft** [comment]
фиксед?

**Comment by Lumaeris** [comment]
da
