### ISSUE TITLE
починить сообщения

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#616]
в полной версии сайта, когда ты отправляешь сообщения собеседник может их увидеть только при обновлении страницы
исправьте это

**Comment by SuperErnD** [comment]
> в полной версии сайта, когда ты отправляешь сообщения собеседник может их увидеть только при обновлении страницы исправьте это

это скорее не баг, и не ошибка, это просто не реализовано
может когда-то разрабы это сделают, кстати я думаю можно юзать для этого SSE, но я не знаю как это сделать в PHP
По этому ждем пока сделают

**Comment by celestora** [comment]
@SuperErnD Это уже сделано, просто на основном инстансе что-то отвалилось

**Comment by AlesAlte** [comment]
@celestora Фикс будет?

**Comment by SuperErnD** [comment]
> @SuperErnD Это уже сделано, просто на основном инстансе что-то отвалилось

Окей, я не знал, когда фикс?

**Comment by bza69299** [comment]
так почему в 2021 году это было торжественно сделано и показано ?
почему работать перестало?

**Comment by veselcraft** [comment]
@celestora сестра чини)

**Comment by SigmaTel71** [comment]
Дубликат #595.
