### ISSUE TITLE
Если при попытке сменить ссылку на группы написать с заглавной буквы то ссылка не сменится

### ISSUE THREAD

**Issue by Artem13327** [OpenVK/openvk#621]

**Comment by celestora** [comment]
Это не баг, а фича)
Vanity subdomains как в ВК, как и в ОВК к регистру не чувствительны (представьте какая жесть бы творилась если бы был aNime, Anime, animE, anime и это всё разные группы ржу).

**Comment by Artem13327** [comment]
@celestora 
Вы кажется не так всё поняли
Должно быть так
TeSt123 должен превратится в test123
А на деле то что ссылка просто не сохранится

**Comment by celestora** [comment]
Действительно, прикольное поведение

**Comment by Artem13327** [comment]
@celestora 
Можно ли добавить перевод верхнего регистра в нижний
Например Test в test

**Comment by celestora** [comment]
Можно но зач

**Comment by veselcraft** [comment]
@Artem13327 о номер ошибки 621 это же мой любимый вебсайт
