### ISSUE TITLE
Доп. аватарка 1:1 (или Ручное кадрирование аватарок)

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#624]
![изображение](https://user-images.githubusercontent.com/46892579/182024521-c9ce4845-b184-4191-92ec-b910b70a13e7.png)
OpenVK позволяет выкладывать фото с любым соотношением сторон, что может мешать нормальному отображению аватаров.
Перед выкладыванием аватарки сайт должен попросить кадрировать её, чтобы можно было оставить основную часть, а остальное будет видно только в профиле.
![изображение](https://user-images.githubusercontent.com/46892579/182024744-21a844cc-bf76-4d2c-b985-08be1ed3df34.png)
![изображение](https://user-images.githubusercontent.com/46892579/182025149-ed7c31d7-2a0c-468d-8987-de01c9ae44b0.png)
Также аватарки 1:1 позволяют искоренить неразбериху с размерами. Помещается больше других частей интерфейса.
![изображение](https://user-images.githubusercontent.com/46892579/182025003-22b7e32f-6bbb-4381-b98f-d01765840035.png)

Извините если плохо обьяснил, я это умею))

**Comment by Nediorg** [comment]
упс, одна фотка криво вставилась
![изображение](https://user-images.githubusercontent.com/46892579/182025149-ed7c31d7-2a0c-468d-8987-de01c9ae44b0.png)

**Comment by rudzik8** [comment]
стоит переименовать в ручное кадрирование аватарок

**Comment by Endedman** [comment]
@Nediorg тоже самое писал в Здесь постирония не запрещена

**Comment by Lumaeris** [comment]
Дубликат #106
