### ISSUE TITLE
Нет защиты от удаления аккаунта

### ISSUE THREAD

**Issue by Nediorg** [OpenVK/openvk#631]
![изображение](https://user-images.githubusercontent.com/46892579/183241192-44759cab-176e-4873-a16c-361eb7e14f69.png)

Недавнее нововведение, позволяющее удалить аккаунт имеет проблему. Вам не придётся подтверждать личность , что значит, что любой человек, взломавший аккаунт, может с лёгкостью удалить аккаунт.

![изображение](https://user-images.githubusercontent.com/46892579/183241782-9f945280-9c6e-421f-b73e-e5bb3a87b152.png)

Решение: перед удалением необходимо подтвердить действие паролем, 2FA кодом, кодом с электронной почты.

**Comment by Endedman** [comment]
@Nediorg а если почта взломана, что рикажешь делать? гораздо надежнее SMS

**Comment by Nediorg** [comment]
@Endedman 2FA код

**Comment by celestora** [comment]
Учитывая оборотность данного действия и околонулевые риски, я не думаю что данное сильно необходимо

**Comment by ghost** [comment]
@Nediorg Я вижу пункт "Выбрать другой способ" в образцах.
Что ты под этим подразумеваешь?

**Comment by Nediorg** [comment]
@AlesAlte Выбрать другой способ подтверждения
Например:
2FA
Код с почты

**Comment by rudzik8** [comment]
> @Nediorg а если почта взломана, что рикажешь делать? гораздо надежнее SMS

а ничего что у нас телефон нигде не вводится? это вообще другой ишуй получается

**Comment by ghost** [comment]
> 2FA

Она должна вводится после ввода пароля. Поэтому откидаем.

> Код с почты


Про ввод пароля с почты - спорно. Потому что это ещё нужно реализовать.

**Comment by celestora** [comment]
> @Nediorg а если почта взломана, что рикажешь делать? гораздо надежнее SMS

а если телефон украли и увезли в южную корею вместе с сим картой что прикажешь делать? гораздо надёжнее авторизация через отпечаток глаза

**Comment by ghost** [comment]
> отпечаток глаза

А если я вилку выбрал?

**Comment by vituz67** [comment]
@AlesAlte Ржач
