### ISSUE TITLE
Восстановление страницы работает похуже государственных институтов РФ

### ISSUE THREAD

**Issue by celestora** [OpenVK/openvk#632]
Чтобы страницу реактивировать надо нажать на кнопку, но не просто а n раз. Угадайте, сколько. Кирилл писал про 3 раза, но у меня не получилось и с 5го :DDD
Помог только спамклик по ссылке, с 6 запроса сработало вроде.

![image](https://user-images.githubusercontent.com/34442450/183409291-b97b7042-8fd0-4e0c-a15e-67b82e42a20e.png)

**Comment by themohooks** [comment]
получилось с 6 раза восстановить страницу xD

**Comment by celestora** [comment]
Как оказалось, страница действительно восстанавливается с первого раза, просто браузер кеширует страничку :D
Интересно связанно это с поведением браузера или с неправильной настройкой nginx?

**Comment by vituz67** [comment]
@celestora Как вариант, можно попробовать с другого браузера. Если проблема остаётся - значит nginx виноват или что-то ещё

**Comment by cheburashka777** [comment]
@vituz67 Как вариант, можно перестать копировать мои сообщения.

**Comment by vituz67** [comment]
@cheburashka777 Ну ты не смог отправить, поэтому как вариант я смог тебе помочь.

**Comment by cheburashka777** [comment]
@vituz67, а, ну тогда спасибо!

**Comment by Endedman** [comment]
@cheburashka777 че за хрень иссуй? закрыть

**Comment by Lumaeris** [comment]
> [...] или с неправильной настройкой nginx?

Это больше похоже на правду. Я прописал ещё один путь в конфиге, думаю больше не будет кешировать. Проверьте кто-нибудь

**Comment by ghost** [comment]
> Проверьте

Тот же эффект. Чтобы я смог перейти на главную, мне пришлось нажимать на "восстановить страницу" 6 раз.

**Comment by celestora** [comment]
Закрыто по причине конфигурация
