### ISSUE TITLE
HTTP 500 при открытии последней страницы новостей

### ISSUE THREAD

**Issue by m0stwan1ed** [OpenVK/openvk#633]
При переходе на последнюю страницу новостей выпадает в HTTP 500. Для меня это страница №19
https://openvk.su/feed?p=19
Страница пользователя - https://openvk.su/id8399

**Comment by celestora** [comment]
Если посмотреть в журнал, окажется, что там пост об удалении страницы, который запостили от имени группы, ржу.

**Comment by Lumaeris** [comment]
![norton-anti-virus-mac](https://user-images.githubusercontent.com/10499845/183451314-865557fa-6d95-46f4-8b5b-473e93ba6bdd.jpg)

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/183451356-8219a6d8-9aa7-4501-8ef7-67a49df0a152.png)

**Comment by veselcraft** [comment]
Не воспроизводится и не особо актуально, закрываю
