### ISSUE TITLE
Отправка подарков самому себе

### ISSUE THREAD

**Issue by Artem13327** [OpenVK/openvk#638]
Да я знаю этот прикол есть в оригинальном ВК
Но может его лучше исправить
Что-бы это сделать нужно перейти на https://openvk.su/gifts?act=pick&user=Свой ID

**Comment by ghost** [comment]
Не ясно, **ради чего** это исправлять?

**Comment by rudzik8** [comment]
> Не ясно, **ради чего** это исправлять?

ради того, чтобы фича осталась только в вепуровк посредством непринятия коммита, и все асоциальные люди желающие подарков перебежали туда :trollface:

**Comment by Lumaeris** [comment]
@rudzik8 🥴

**Comment by myslivets** [comment]
Смысл от исправления этого бага? 
А если у человека нигде нет друзей, но он хочет себя подарком порадовать или просто поиграться?

~не будет исправлено

**Comment by vituz67** [comment]
@myslivets согласен с даней.

**Comment by ghost** [comment]
@myslivets для таких и опенвк не нужен
