### ISSUE TITLE
Дополнение robots.txt

### ISSUE THREAD

**Issue by Artem13327** [openvk/openvk#639]
Предлагаю запретит к индексации некоторые страницы
1. Папку с ассетами (CSS, стандартные изображения, звуки)
2. albums/create 
3. videos/upload 
4. invite  
5. groups_create
6. notifications 
7. settings
8. edit (Без авторизации безполезны)
9. gifts (Без дополнительных параметров работать не будет)

**Comment by veselcraft** [comment]
Ну тут как бы и так есть этот файл...

https://openvk.su/robots.txt

**Comment by Lumaeris** [comment]
Таки да, но не помешало бы немного дополнить

**Comment by Artem13327** [comment]
@veselcraft 
Я не совсем правильно написал
Я предлагаю дополнить его
