### ISSUE TITLE
Некоторые функции связаные с отображением автарок

### ISSUE THREAD

**Issue by Artem13327** [OpenVK/openvk#642]
Предлагаю добавить вот такие функции:
1. Функцию скрытия аватарок
2. Функция замены аватарок на первуб букву имени

**Comment by ghost** [comment]
Зачем?

**Comment by Artem13327** [comment]
@AlesAlte 
Не всем нравится смотреть на чужие аватарки

**Comment by l3nal3t0va** [comment]
фичи ради фич какие-то

**Comment by Endedman** [comment]
@LeenzeryDev

**Comment by ghost** [comment]
> Не всем нравится смотреть на чужие аватарки

Вопрос второй: На какой стороне фича (сторона просматривающего или сторона обладателя)?

**Comment by Artem13327** [comment]
@AlesAlte 
На стороне просмоторщика
Просто возможность не видеть аватарки

**Comment by l3nal3t0va** [comment]
сделай себе тему без аватарок и всё)0)

**Comment by veselcraft** [comment]
Для таких людей есть Адблок, а ещё лучше - ф-ция отключения картинок в целом. Бредовая функция, проблему закрываю

**Comment by hetrixq** [comment]
@AlesAlte Так ты ушел из овк или нет?

**Comment by celestora** [comment]
> @AlesAlte Так ты ушел из овк или нет?

Он бы с радостью, да вот…

**Comment by ghost** [comment]
> ушел из овк или нет

![0000000000](https://user-images.githubusercontent.com/92401420/184251591-6fcb6a47-6326-4587-80cd-8cd5d3b8ff61.png)

**Comment by Endedman** [comment]
@AlesAlte Из тг крипово смотреть вложения
