### ISSUE TITLE
Ошибка при создании ticket тех. поддержке

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#644]
Опишу ситуацию: Удаленный аккаунт, пытается написать тех. поддержке по той и\или иной причине. Но после отправки, на стороне отправителя **Server Error**
![Menia_v_durku_uvoziat](https://user-images.githubusercontent.com/92401420/184338356-b5bda631-b181-4969-ad17-d5dcd6276b61.png)

**Comment by ghost** [comment]
Соответственно, после перезагрузки такого, форма отправилась ещё раз.

**Comment by n1rwana** [comment]
Не воспроизводится

![Снимок экрана от 2022-08-19 21-51-10](https://user-images.githubusercontent.com/93197434/185687400-ab574f54-7b2e-4d06-90f8-fbe46e262cb2.png)

**Comment by veselcraft** [comment]
Выяснили, что это был прикол с ТГ ботом. Точнее, с самим кодом отправки уведомления о новом тикете. Почему то на нашем сервере перестал резолвится api.telegram.org, поэтому и выпукивалась ошибка 500
