### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Artem13327** [OpenVK/openvk#645]
В некоторых группах если нажать на аватарку вылетит ошибка

**Comment by ghost** [comment]
Написано же: Not Found.

**Comment by celestora** [comment]
wontfix

**Comment by Endedman** [comment]
@celestora Скоро таких NotFound станет больше

**Comment by Artem13327** [comment]
Откройте!
Я нашёл объяснение
Если тот кто поставил аватарку на группу удалит страницу, то при нажатии на аватарку группы выдаст ошибку
Я так понял работает так

**Comment by Endedman** [comment]
@Artem13327 Да давно все заметили это
