### ISSUE TITLE
Список транзакций

### ISSUE THREAD

**Issue by rudzik8** [openvk/openvk#650]
в это входит и покупка голосов, и активация ваучеров, и переводы голосов другим людям, и покупка на них чего либо (подарков?)

сейчас отследить, кто и сколько украл с твоего счёта (в случае если тебя взломали) невозможно. максимум - увидишь что голосов стало заметно меньше
с ваучерами тоже было бы удобнее, так как не всем хочется запоминать что они вводили, а что нет. помню как все порвались когда кто-то начал форсить старые ваучеры в чате и кричали "НИРОБОТАИТ", так как забыли что давно это всё вводили в канале

реализация - либо через архив уведомлений (Вы передали 238423984020398 голосов Василию Пупкину в 24:61 32 марта undefined года), либо через отдельный список в разделе Настройки > Голоса, где-нибудь внизу

**Comment by WerySkok** [comment]
depends on https://github.com/openvk/openvk/issues/276

**Comment by maksalees** [comment]
Дубликат #399
