### ISSUE TITLE
ОВК умирает когда создаёшь группу с длинным названием

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#656]
я хотел создать группу о вымышленном блюде состоящем из сочетания рыбы и другого мяса под названием [λοπαδο­τεμαχο­σελαχο­γαλεο­κρανιο­λειψανο­δριμυ­ποτριμματο­σιλφιο­καραβο­μελιτο­κατακεχυμενο­κιχλε­πικοσσυφο­φαττο­περιστερα­λεκτρυο­νοπτο­κεφαλλιο­κιγκλο­πελειο­λαγῳο­σιραιο­βαφητραγανοπτερύγων](https://en.wikipedia.org/wiki/Lopado%C2%ADtemacho%C2%ADselacho%C2%ADgaleo%C2%ADkranio%C2%ADleipsano%C2%ADdrim%C2%ADhypo%C2%ADtrimmato%C2%ADsilphio%C2%ADkarabo%C2%ADmelito%C2%ADkatakechy%C2%ADmeno%C2%ADkichl%C2%ADepi%C2%ADkossypho%C2%ADphatto%C2%ADperister%C2%ADalektryon%C2%ADopte%C2%ADkephallio%C2%ADkigklo%C2%ADpeleio%C2%ADlagoio%C2%ADsiraio%C2%ADbaphe%C2%ADtragano%C2%ADpterygon) и вот что вышло:
![изображение](https://user-images.githubusercontent.com/58212796/184548979-14cfa9d2-5fc4-4e43-82b7-5fc036bebcc7.png)

**Comment by ayaaop** [comment]
на скриншоте я пытался поменять название группы "любители майнкрафта онлайн" на это название, но результат и так и так один и тот же

**Comment by celestora** [comment]
завтра разберусь

**Comment by Endedman** [comment]
@celestora Оставь как есть, это не бар а фича

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/185634551-278fda11-51cb-4452-840e-aae281169d38.png)

внезапно не могу воспроизвести

**Comment by ayaaop** [comment]
+, странно

**Comment by ayaaop** [comment]
ресолвед получается
