### ISSUE TITLE
Дискриминация беларусских и украинских (возможно) имён

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#658]
Кратко говоря, не ставится имя или фамилия с любой бел. буквой. Хотел по приколу себе поменять имя на Уладзiмiр Барынаў, но мне не дали((((

**Comment by SuperErnD** [comment]
база данных: я шутка что-ли?
(в том смысле что можно вручную поменять:D)

**Comment by Endedman** [comment]
@SuperErnD наверняка там стоит windows1251_general_ci вместо utf8_general_ci

**Comment by SuperErnD** [comment]
может, не знаю, не смотрел в схему

**Comment by veselcraft** [comment]
> @SuperErnD наверняка там стоит windows1251_general_ci вместо utf8_general_ci

нет, там ограничение конкретно в коде. если бы бд была в шиндовс1251, то бы ты у постов смайлики не видел

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/185634802-b5975d08-c6e5-455f-961c-ea41de2f73e0.png)

ржу это уже второй баг по счёту который я не могу воспроизвести :DD
наверное онигуруму в пхп81 обновили и там беларусская у краткая считается за букву

**Comment by veselcraft** [comment]
А лол, у меня теперь ставится фамилия
