### ISSUE TITLE
Цифровые хэштеги

### ISSUE THREAD

**Issue by Lumaeris** [OpenVK/openvk#663]
Сейчас OpenVK показывает что то вроде #.5939 как [#5939](https://openvk.su/feed/hashtag/5939) и кидает ошибку сервера ибо цифровых хештегов быть не должно. (#. вместо "экранирования" чтоб оно выглядело как простой текст)

В итоге это создаёт неправильный опыт использования.
Пользователь видит кликабельный хештег > кликает > ему дают ошибку.

Нужно перестать считать сочетание решётки и цифр за хештеги и писать его простым текстом, либо добавить поиск по цифровым хештегам. Первое предпочтительнее ибо довольно часто решёткой-цифрой указывают номер чего либо, из-за чего поиск на такого рода хештегов будет бессмысленен с точки зрения логики использования хештегов(поиск по какой то теме).

_Оригинал: [#14 на Codeberg](https://codeberg.org/OpenVK/openvk/issues/14)_

**Comment by ghost** [comment]
Хэштеги теперь ведут в поиск по постам, https://ovk.to/feed/hashtag/0 неактуален
