### ISSUE TITLE
Расширяемые окна ввода текста в личной информации/репосте

### ISSUE THREAD

**Issue by Lumaeris** [OpenVK/openvk#666]
Сейчас в личной информации и при репосте, окна ввода слишком маленькие, из-за чего писать что то длинное крайне неудобно. Стоит сделать что бы окна расширялись как у коментариев.

![](https://codeberg.org/OpenVK/openvk/attachments/f4e593a5-120d-4add-b4d1-ca7f8be8ee48)

![](https://codeberg.org/OpenVK/openvk/attachments/78ca3cd8-2bbf-4461-a2c2-75ea07b9a064)

![](https://codeberg.org/OpenVK/openvk/attachments/eb368c1b-af1c-4fe9-a045-05843d30a1ee)

_Оригинал: [#17 на Codeberg](https://codeberg.org/OpenVK/openvk/issues/17)_

**Comment by rudzik8** [comment]
сатана, перелогинься

**Comment by zavolo** [comment]
@dsrev сатана, перелогинься
