### ISSUE TITLE
Отправка постов и комментов по Ctrl+Enter

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#67]

**Comment by celestora** [comment]
Хорошая идея мне нравится

**Comment by veselcraft** [comment]
согл--Sent from Yandex.Mail for mobile18.01.2021, 00:36, "rem-pai" <notifications@github.com>:
Хорошая идея мне нравится

**Comment by celestora** [comment]
У вас почтовый клиент испортил коммент

**Comment by celestora** [comment]
@WerySkok можете сделать PR по этой фиче?

**Comment by WerySkok** [comment]
не

**Comment by veselcraft** [comment]
@celestora актуально? Если нет, то закрываю Issue
