### ISSUE TITLE
Create a qqx dummy language for debug

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#678]
Добавьте, пожалуйста, "язык", показывающий названия сообщений интерфейса. [Как в Медиавики, типа qqx](https://www.mediawiki.org/wiki/Manual:$wgDummyLanguageCodes?uselang=qqx)

**Comment by n1rwana** [comment]
https://github.com/openvk/openvk/commit/02ef39756150d790656bb857163c63bbb1c6b01a
