### ISSUE TITLE
Сделать уведомления более понятными

### ISSUE THREAD

**Issue by bza69299** [OpenVK/openvk#682]
![image](https://user-images.githubusercontent.com/69803074/185863043-7c9bd6bc-7966-4408-b684-e8365e9832eb.png)
Всегда почему то когда тебе отвечают или пишут комментарий под постом, в ответах появляется не как логично сам сокращенный текст сообщения, а : "[id441|Бог…".
Прошу починить

**Comment by SigmaTel71** [comment]
#464, дубликат.

**Comment by celestora** [comment]
дубликат
