### ISSUE TITLE
Не работают  подарки 

### ISSUE THREAD

**Issue by javagentoo** [OpenVK/openvk#684]
Firefox не работают отображение подарков
![image](https://user-images.githubusercontent.com/84329485/185864155-7a6d230d-77ac-452b-b68b-7e1794ced422.png)
Когда нажимаешь на "отправить подарок" падает ovk
![image](https://user-images.githubusercontent.com/84329485/185864263-e6ce4f81-c572-4c97-9210-54785b4f0112.png)

**Comment by bza69299** [comment]
так это ты мне опенвк падаешь!

**Comment by javagentoo** [comment]
> 
![sticker](https://user-images.githubusercontent.com/84329485/185865134-40b73653-0506-416c-8cfc-f0c6a3e9c020.png)

**Comment by myslivets** [comment]
Не смог повторить этот баг, к сожалению. 
Ради любопытства проверил на двух браузерах: Firefox и Chromium.

**Comment by javagentoo** [comment]
>Не смог повторить этот баг, к сожалению.
Это было на пхп 8

**Comment by zavolo** [comment]
@javagentoo Возможно он имеел ввиду что бесплатные наборы подарков кончились?

**Comment by NoPlagiarism** [comment]
Может закрыть?

**Comment by javagentoo** [comment]
может быть
