### ISSUE TITLE
[al_comments] 500 при публикации комментария на чужой стене

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#686]
После обновления PHP до версии 8.1 на основном кластере OpenVK наблюдается очень интересная неисправность.
Если на чужой стене (вероятно, в группе тоже) написать комментарий, то появляется ошибка 500, и если пройти на страницу назад и обновить её, то появится написанный комментарий.
Чем чревато? Ставим авторефреш страницы на относительно короткий промежуток времени на странице 500 и ваш сервер к хуям ложится в гроб.

**Comment by SigmaTel71** [comment]
~[irony]Ни разу не подсказка для StopLamers, а то они недавно проснулись и даже вынесли несколько чатиков Telegram вперёд ногами.[/irony]~

**Comment by myslivets** [comment]
Пока откатили сайт на 7.4, будем внутри тестировать сайт под 8.1
Спасибо за замечание!

**Comment by NoPlagiarism** [comment]
Может закрыть?

**Comment by SigmaTel71** [comment]
Да, можно закрывать. Проблема на текущий момент не наблюдается.
