### ISSUE TITLE
опенвк посылает

### ISSUE THREAD

**Issue by SuperErnD** [OpenVK/openvk#689]
я ставил опенвк на шинду все норм ишло но при попытке зайти/зарегистрироватся Table 'email_verifications' does not exist
иская в init-static-db.sql и init-event-db.sql я ничего не нашел такого, как жить??
я нашел в 
![image](https://user-images.githubusercontent.com/84639576/186644348-d0c162d1-2f11-4a26-adb2-0a6f18d282b7.png)
но мне что его импортировать??

**Comment by Lumaeris** [comment]
Необходимо импортировать не только `init-[xxxxx]-db.sql`, но и все файлы в папке `install/sqls`, без этого никуда.

После импорта также требуется удалить кэш базы данных, файлы находятся в `chandler/tmp/cache/database/`.

**Comment by Lumaeris** [comment]
![](https://user-images.githubusercontent.com/10499845/186645866-f609a2f9-5ccf-4d12-960e-590ab8b92cca.png)

Вообще, в будущем планируется упростить процесс установки OpenVK, но пока придётся повыёживаться с этим

**Comment by SuperErnD** [comment]
да, доки классные

**Comment by SuperErnD** [comment]
кстати переход с 8 пхп на 7 не помог, щас буду импортировать все файлы а также, нужно импортировать events в бд ивентов?

**Comment by Lumaeris** [comment]
Конечно, и это в принципе всё, что осталось сделать, если процедура установки выполнена полностью.

**Comment by SuperErnD** [comment]
да, ок понял

**Comment by SuperErnD** [comment]
если что-то пойдет не так, то я скажу сюда

**Comment by SuperErnD** [comment]
потом поставлю на свой хост,а пока тестовый инстанс на моем пк

**Comment by SuperErnD** [comment]
все ок, в админ панеле немного битые сыллки, думаю что это должно так быть
