### ISSUE TITLE
Ошибка при создании поста с изображением

### ISSUE THREAD

**Issue by m65v19** [OpenVK/openvk#69]
Здравствуйте. Столкнулся с тем, что каждый раз, когда создаю пост с прикриплённым изображением, получаю ошибку вида
![Screenshot_2021-01-21_04-05-29](https://user-images.githubusercontent.com/15930110/105319152-47320c00-5be6-11eb-89b5-767fc5ebd9b8.png)

**Comment by veselcraft** [comment]
Проблема на стороне инстанса
