### ISSUE TITLE
[al_notifs] Ложный сигнал уведомления

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#694]
Если RPC натыкается на ошибку 403, то почему-то браузер воспроизводит звук уведомления, когда самого уведомления нет.

![image](https://user-images.githubusercontent.com/17989678/187023723-f4bb26dd-2499-4f58-8f4b-d8c8acca5cf8.png)

После патча https://github.com/openvk/openvk/pull/760 код ошибки изменился на 405. Проблема **не** исправлена.

**Comment by SuperErnD** [comment]
наверное al_notify.js не детектит статус
ща чекну

**Comment by SuperErnD** [comment]
не нашел API.Notification, странно

**Comment by celestora** [comment]
> не нашел API.Notification, странно

API это макрос-объект. API.Notifications.fetch превращается в вызов метода notifications.fetch служебного апи. Исходники этих методов в папке ServiceAPI. \
А сам culprit ситуации вот здесь:
https://github.com/openvk/openvk/blob/4891030ed062a61687d266d8274306116b46ac8d/Web/static/js/al_notifs.js#L19

Нужно чтобы не доходила функция в этом случае до `playNotifSound`, можете поменять на `return`.

**Comment by SigmaTel71** [comment]
Вы таки будете смеяться, но ложное уведомление даже с continue сработало. Переоткрывайте.
![image](https://user-images.githubusercontent.com/17989678/198899921-43c217bd-e11b-4038-8979-fe0130d05c2d.png)

**Comment by SigmaTel71** [comment]
Переоткрывайте, изменился только код ошибки с 403 на 405.
https://openvk.su/wall6588_92
