### ISSUE TITLE
Overflow Fix

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#70]
Необходимо ввести лимит символов для описания видеозаписи иначе страницы с видео будут выглядеть не очень [к](https://openvk.su/video106_1)расив[о](https://openvk.su/videos106).

**Comment by veselcraft** [comment]
![изображение](https://user-images.githubusercontent.com/22993408/133152618-59732ab4-f9ea-444a-ae76-f4b9ebc57160.png)
В армянском переводе вообще капздец

**Comment by likhner** [comment]
троеточие выходит за рамки…

![image](https://user-images.githubusercontent.com/60031799/133908050-ed81d58c-c719-49d7-8ab4-74de79ab0d0a.png)
