### ISSUE TITLE
Продвинутая нумерация страниц

### ISSUE THREAD

**Issue by WerySkok** [OpenVK/openvk#71]
Хочется, чтобы можно было сразу перейти на крайние и соседние страницы, например `1, 2, 3, ... 26`

**Comment by veselcraft** [comment]
Пагинация, я понял

**Comment by veselcraft** [comment]
помоему я долбоёб и опять не закрыл древний issue 

клозед бай 7d94282ad45484c2e988f7c7523dbb887c2dce6e
