### ISSUE TITLE
Не работает кнопка удалить в support

### ISSUE THREAD

**Issue by vituz67** [OpenVK/openvk#722]
Здравствуйте! Я заметил ошибку. Не работает кнопка удалить при запросе в саппорт.

**Comment by vituz67** [comment]
![Uploading image.jpg…]()
Вот эта кнопка не работает

**Comment by n1rwana** [comment]
У вас картинка не загрузилась, отправьте еще раз.
![image](https://user-images.githubusercontent.com/93197434/189488535-ff14ec14-55af-40de-9bc2-7a381c3a0287.png)

**Comment by ghost** [comment]
> Здравствуйте! Я заметил ошибку. Не работает кнопка удалить при запросе в саппорт.

Как я понял, то выглядит это так:
1. Пользователь заходит в /support;
2. Пользователь нажимает на Список обращений;
3. Выбирает обращение; 
4. Нажимает "Удалить"
5. Повторяет 1 - 2 команды
6. Видит, что обращение обстаётся.

Задача: ~Сделать~ Исправить после команды "4" удаление обращения.
