### ISSUE TITLE
Ошибка 500 при загрузке фото

### ISSUE THREAD

**Issue by sdzkHelince** [OpenVK/openvk#725]
При загрузке изображения куда либо (альбом/стена) вылазит ошибка 500
Демонстрация проблемы: [тык](https://youtu.be/DItqopfWrDE)
Надеюсь в чём проблема понятно

**Comment by SuperErnD** [comment]
наверное veselcraft опять все сломал и не признается :D

**Comment by ghost** [comment]
Знакомый прикол. Я пробовал сменить аватарку на OpenVK, загрузил мемасик, ждал 20-30 секунд - 500 error.
Возможно, проблема заключается в размере файла - слишком большой для загрузки. Хотя... фиг его знает, это всего лишь мои догадки

**Comment by n1rwana** [comment]
Не воспроизводится.

<video src="https://user-images.githubusercontent.com/93197434/189973438-11e620d9-a2f7-4fba-8e47-6b1d2e27cd6a.MP4"></video>

**Comment by sdzkHelince** [comment]
![image](https://user-images.githubusercontent.com/42173438/189984265-1364a538-2ab5-4fa7-b665-a3a079c4164c.png)
Действительно, заработало
