### ISSUE TITLE
Очепятки / Typos

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#730]
Сюда можно выкладывать различные очепятки, которые пользователи нашли в OpenVK.

Я первый начинаю :)
Текст при смене аватарки - написано "изображние", а должно быть "изображение". Домен: openvk.su

![Новое изображние...](https://user-images.githubusercontent.com/80192956/191280547-c22fa565-d0f6-4964-a756-280c1470d5c3.png)

**Comment by maksalees** [comment]
Исправлено в [6eeb052](https://github.com/openvk/openvk/commit/6eeb05236e9634256f9bcdd4fc42db99c4e77070)

**Comment by ghost** [comment]
По состоянию 16.10.2022 г., опечаток больше нет.

**Comment by ghost** [comment]
Рекомендую тем, кто создает что-то связанное с локализациями использовать сервисы для проверки орфографии и граматики.
