### ISSUE TITLE
NSFW размазывание реализована криво.

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#731]
Имею претензии к замазыванию nsfw контента. А в частности:
1. Неудобно удерживать клавишу мыши, когда просматриваешь nsfw контент, а вторая рука занята🙂🙂
2. Есть шанс того, что фото откроется в просмотрщике (см. скриншот)
![image](https://user-images.githubusercontent.com/92401420/191601496-fbe2d1ef-d7c3-413f-aaa0-0ffe60e30e57.png)
3. Кроме того, если ты просматриваешь видео, он тоже закрывается баннером.

Решение: 
Сделать реализацию скрытия баннера при 2-х кратном нажатии клавиши мыши.

**Comment by veselcraft** [comment]
бля кто-то реально в овк фапает

**Comment by AlesAlte** [comment]
> бля кто-то реально в овк фапает

Смысле? Я просто хочу рассмотреть "Мону Лизу" Леонарда Да Винчи, никакой эротики 🙂🙂🙂

**Comment by tretdm** [comment]
И то, например, в API нет специального параметра, по которому клиент должен знать, помечен ли как NSFW-контент или нет.
