### ISSUE TITLE
Не воспроизводятся видео на мобильном устройстве (Android 9)

### ISSUE THREAD

**Issue by dogganovich68** [OpenVK/openvk#732]
Не воспроизводятся видеоролики на мобильном устройстве, при этом на ПК всё работает исправно. 

![RrAzuqMWAafuX8GkhrRZiPvN0KjUrYvWfcb24yieC3wkM0HzaFBqLuuz5XEvaJ6MhqUJ45LU2VyvHV29AunUKHiP](https://user-images.githubusercontent.com/70939274/191823546-81e32d87-9154-40da-9e30-80de743ae14b.jpg)

**Comment by celestora** [comment]
Дубликат #41

**Comment by programmister68** [comment]
> Дубликат #41 

Хорошо, а что куда нажимать-то, чтобы заработало?))))
