### ISSUE TITLE
Пакеты Composer поддерживают только PHP 8.0 и выше

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#738]
![image](https://user-images.githubusercontent.com/81331307/193655572-388829d6-6949-4847-8e51-90474ca853ae.png)
При попытке обновить пакеты composer, возникает ошибка, что требуется php 8.0, однако в документации написано иное, что поддерживается 7.4

**Comment by celestora** [comment]
Исправил

**Comment by themohooks** [comment]
> Исправил

Воспроизводится
![IMG_20221004_094343_381](https://user-images.githubusercontent.com/81331307/193751894-525d50f8-2389-4151-8e98-6988dc9ae0d8.jpg)

**Comment by Lumaeris** [comment]
Удали `composer.lock` и попробуй по новой

**Comment by themohooks** [comment]
> Удали `composer.lock` и попробуй по новой

Пока работает.
