### ISSUE TITLE
Невозможно пройти регистрацию без указывания пола

### ISSUE THREAD

**Issue by sdzkHelince** [OpenVK/openvk#748]
![image](https://user-images.githubusercontent.com/42173438/195385287-6a2430f3-66af-4307-87dc-6fc1110ae230.png)
Нашёл человека, который недоволен тем, что нужно обязательно выбирать пол. Пожалуйста, пофиксите.

**Comment by s4ntiksu** [comment]
Не устраивает - пусть не регается.

**Comment by hetrixq** [comment]
@SantikDeveloper Полностью поддерживаю

**Comment by ghost** [comment]
Нужно добавить небинар. пол.

P.S Кстати, а что мешает человеку указать свой пол?

**Comment by hetrixq** [comment]
@AlesAlte Наличие только двух полов?

**Comment by ghost** [comment]
> @AlesAlte Наличие только двух полов?

Ну вдруг кто стесняеться вагиталий или пенины

**Comment by veselcraft** [comment]
> > @AlesAlte Наличие только двух полов?
> 
> Ну вдруг кто стесняеться вагиталий или пенины

пенис душилин ахахахахаххахахахахахахахаха

**Comment by sdzkHelince** [comment]
@veselcraft Владимир, не нарушайте закон.

**Comment by celestora** [comment]
> @AlesAlte Наличие только двух полов?

а как же украиногендер?

**Comment by sdzkHelince** [comment]
@celestora Блин, согласен, надо добавить

**Comment by sdzkHelince** [comment]
@celestora

**Comment by myslivets** [comment]
Требую добавления гендера "вертолёт" и "гиперзвуковой прямоточный воздушно-реактивный двигатель"!

**Comment by celestora** [comment]
но вообще у нас опенвк слишком завязан на патриархально-архаически-гетеронормативных социальных институтах и это не поле гендера там, а биологического пола)
пофиксить такое стоит много времени (1 день), могу в качестве компромисса предложить костыль: в английской локали перевести эти строки как "Preferred pronouns" и "OpenVK will use he/him, if possible" и "OpenVK will use she/her, if possible". Но тогда очень просится they/them (pers/perse по rms)

**Comment by celestora** [comment]
а так вообще хотелось бы в овк pronouns, genders, sexual orientation etc

**Comment by ZAZiOs** [comment]
А можно просто добавить пункт "Скрыто"/"Не указывать" и по умолчанию обращаться в мужском роде?

**Comment by iamdelickkk** [comment]
Я ЛГБТ СЕКС ИНСТРУКТОР ИЗ НАТО

**Comment by celestora** [comment]
> А можно просто добавить пункт "Скрыто"/"Не указывать" и по умолчанию обращаться в мужском роде?

`<option value="male">Не указывать</option>`?)
Наёбка года

**Comment by ghost** [comment]
> > @AlesAlte Наличие только двух полов?
> 
> а как же украиногендер?

Я идентифицирую себя по гендеру как Украинский Автоматический Гранатомет 40мм, прошу учесть в релиз.

**Comment by ZAZiOs** [comment]
> Наёбка года

Именно 😎

**Comment by sdzkHelince** [comment]
@ZAZiOs кис кис небинарный сюрприз

**Comment by l3nal3t0va** [comment]
> > @AlesAlte Наличие только двух полов?
> 
> а как же украиногендер?

я трансукраинец

**Comment by veselcraft** [comment]
Было исправлено с введением пронаунсов. Человек, не желавший выбирать пол, может просто выбрать "они/их"

![image](https://github.com/user-attachments/assets/35c6e7c7-79a5-4fbd-a8a4-c3d832c90535)
