### ISSUE TITLE
Нет адаптивного увеличения постов при скролле

### ISSUE THREAD

**Issue by mbs0ft** [OpenVK/openvk#75]
Сравнение с OVK и VK 2015 

https://user-images.githubusercontent.com/22106304/110441340-57347b00-80c2-11eb-87fa-afde95336541.mp4

**Comment by ghost** [comment]
А почему иссуе открыт

**Comment by mbs0ft** [comment]
> А почему иссуе открыт

благодарю за реплай, закрываю
