### ISSUE TITLE
Polls work crookedly

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#753]
![image](https://user-images.githubusercontent.com/92401420/196058552-08bbd804-bb68-4c04-ae70-32be4490c27e.png)
This screenshot shows that the percentage of respondents goes beyond 100%

**Comment by WerySkok** [comment]
> багато вариантів

**Comment by sdzkHelince** [comment]
@AlesAlte

**Comment by AlesAlte** [comment]
> > багато вариантів

See PR #749
