### ISSUE TITLE
Ё

### ISSUE THREAD

**Issue by WhO2022** [OpenVK/openvk#754]
Если поставить язык где в интерфейсе есть Ё (напимер Советский), то это не Ё, а Е (Например МоЕ досье). Чё это?

**Comment by celestora** [comment]
> Чё это?

Зрада

**Comment by veselcraft** [comment]
*Употребление буквы ё обязательно в текстах с последовательно поставленными знаками ударения, в книгах для детей младшего возраста (в том числе учебниках для школьников младших классов), в учебниках для иностранцев. В обычных печатных текстах ё пишется в тех случаях, когда возможно неправильное прочтение слова, когда надо указать правильное произношение редкого слова или предупредить речевую ошибку. Букву ё следует также писать в собственных именах. В остальных случаях употребление ё факультативно, то есть необязательно.*

**Comment by celestora** [comment]
> _Употребление буквы ё обязательно в текстах с последовательно поставленными знаками ударения, в книгах для детей младшего возраста (в том числе учебниках для школьников младших классов), в учебниках для иностранцев. В обычных печатных текстах ё пишется в тех случаях, когда возможно неправильное прочтение слова, когда надо указать правильное произношение редкого слова или предупредить речевую ошибку. Букву ё следует также писать в собственных именах. В остальных случаях употребление ё факультативно, то есть необязательно._

А мне нравится буква ё. Давайте сделаем.

**Comment by ghost** [comment]
@celestora Вриска грамарнаци😢😢😢

**Comment by ghost** [comment]
> _В остальных случаях употребление ё факультативно, то есть необязательно._

Если у кого есть время на такое, то почему нет?

**Comment by curoviyxru** [comment]
![download](https://user-images.githubusercontent.com/61984636/196177279-e05e2189-267b-45b6-a3b5-a89c0aeccdbd.jpeg)

**Comment by sdzkHelince** [comment]
@curoviyxru капец ты лох

**Comment by hetrixq** [comment]
@sdzkHelince xd

**Comment by WhO2022** [comment]
@curoviyxru безграмотный пиздюк

**Comment by iamdelickkk** [comment]
@WhO2022 хаххахпахвхвпх

**Comment by saursvepur** [comment]
lol

**Comment by thejenja** [comment]
е-мое

**Comment by sdzkHelince** [comment]
@thejenja Уу сука
