### ISSUE TITLE
Удаление сообщений

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#758]
В OpenVK API есть [метод для удаления сообщений](https://github.com/openvk/docs/blob/master/docs/openvk_engine/api/description.md#delete--2), но это не реализованно в веб версии (что и требуется реализовать).

**Comment by celestora** [comment]
Теперь нету

**Comment by ghost** [comment]
> Теперь нету

![image](https://user-images.githubusercontent.com/92401420/197146378-8b93435d-7b05-4ebe-8ed3-bdc7bfe632bd.png)

**Comment by Lumaeris** [comment]
Дубликат #214, кстати

**Comment by sdzkHelince** [comment]
@dsrev
