### ISSUE TITLE
Список он-лайн

### ISSUE THREAD

**Issue by rencornationers** [OpenVK/openvk#768]
Было-бы неплохо иметь специальную страницу на которой-бы отображались пользователи которые находятся в онлайне. В статистике об инстанции можно посмотреть количество пользователей, но посмотреть какие именно - увы нельзя. Жаль. (Ну, по крайней мере можно посмотреть через друзей кто в онлайне, однако если требуется оценить масштабы всей сети а не только своих друзей, то пытаться добавлять всех пользователей в друзья так себе решение...)

В теории, позже можно подвязать к расширенному поиску людей и сортировке поисковых результатов (#662 и #57)

**Comment by ayaaop** [comment]
разработчики сделайте пж
