### ISSUE TITLE
В подвале сайта заменить ссылку "[выбрать язык]" на "[выбрать язык]/change language" или "change language"

### ISSUE THREAD

**Issue by Lumaeris** [OpenVK/openvk#769]
Я видел, что некоторые зарубежные сайты приписывали "Language"/"Change language"/etc, чтобы не запугивать иностранцев и дать им возможность выбрать родной язык самим, если по какой-либо причине автоопределение языка не сработало.

**Comment by WerySkok** [comment]
Проблема в том, что автоопределение языка не работает

**Comment by Endedman** [comment]
@WerySkok Надо бы сделать двойную ссылку во всех языках...

**Comment by WerySkok** [comment]
@Endedman ты хоть понял, что предложил?

**Comment by celestora** [comment]
@WerySkok Надо бы просто добавить иконку Aあ типо

**Comment by ghost** [comment]
@celestora Зачем делать третье колесо в велосипеде? Почините второе.
