### ISSUE TITLE
Кривая локализация на беларуский язык

### ISSUE THREAD

**Issue by cfchnz** [OpenVK/openvk#783]
Взял в пример главную страницу, и как вы можете увидеть, тут полно орфографических ошибок и недочетов. ![Без названия156_20221112150313.png](https://user-images.githubusercontent.com/109415540/201473129-eabf2782-8b1c-4314-b9c8-52be1332121b.png)

**Comment by cfchnz** [comment]
Тут я вообще молчу...![Screenshot_20221112_151410.png](https://user-images.githubusercontent.com/109415540/201473390-0751aa15-14a8-45ed-8908-6d36da510b0e.png)![Screenshot_20221112_151348.png](https://user-images.githubusercontent.com/109415540/201473392-35f3d239-6fae-4392-8722-fc2472d6df97.png)

**Comment by cfchnz** [comment]
Я могу помочь с локализацией, если что

**Comment by ghost** [comment]
лять чел, это не ошибки а русский язык. За основу бел локали взята ру локаль. В связи с тем что бел локаль обновляется раз в 100 лет, половина бел локали в русском языке

**Comment by ghost** [comment]
![выява](https://user-images.githubusercontent.com/105191100/201474353-933abff8-9348-4c5a-871f-4c3373274d94.png)
Я так понимаю тут была О, чел какой к чёрту фАтаздымак, во первых коренное слово "фота", во вторых О всегда в беларуском под ударением, если оно не под ударением то оно заменяется на А. Либо ты ударение поставил фиг пойми куда, либо ты не знаешь элементарных правил, которые проходят в начальной школе.

**Comment by Lumaeris** [comment]
Добавлю, что файлы Markdown (второй коммент) переведены в основном только на английский, армянский и украинский.

По факту надо было показывать переводы .md с теми кодами, которые были указаны в `include` локализационных файлов. Без понятия почему подобное не было реализовано.

**Comment by AlesAlte** [comment]
Ув, @cfchnz.

То, что вы видите русский язык - это следствие использования #include <ru>, которое заменяет непереведенные строки на русские слова.

То, что вы видите в "Служба Поддержки", "Правилах" английский текст - следствие непереведенных на беларуский язык некоторых файлов.


Имеете желание помочь с локализацией? Замечательно.
Сделайте форк, зайдите в директорию /openvk/openvk/blob/master/locales/by.strings, и начните добавлять ключи из русского\английского. А так как, в беларуской локализации много чего не переведено, то я вам рекомендую наново перевести локализацию, беря за основу русскую или украинскую локализацию.

С уважением, @AlesAlte

**Comment by cfchnz** [comment]
> ![выява](https://user-images.githubusercontent.com/105191100/201474353-933abff8-9348-4c5a-871f-4c3373274d94.png)
> Я так понимаю тут была О, чел какой к чёрту фАтаздымак, во первых коренное слово "фота", во вторых О всегда в беларуском под ударением, если оно не под ударением то оно заменяется на А. Либо ты ударение поставил фиг пойми куда, либо ты не знаешь элементарных правил, которые проходят в начальной школе.

в беларуском языке не все слова имеют одинаковый корень
фатаграфія (фатаздымак), фатаграфаваць

**Comment by Lumaeris** [comment]
![image](https://user-images.githubusercontent.com/10499845/201475415-01945794-f8c5-4b00-8fd7-e0e9f1cd1820.png)

Мне кажется это вы что-то путаете

**Comment by ghost** [comment]
боже сударь иди учи язык прежде чем мне что-то доказывать. В слове "фатаграфаваць" первое О не под ударением, а значит она уступает своё место А. С "фатаграфія" та же история.

**Comment by ayaaop** [comment]
@ptushskaya сударица

**Comment by celestora** [comment]
@ptushskaya Вы понимаете, что если бы РФ была более настойчива в своей политике колонизации Беларуси, то мы бы не видели таких сочных срачей о белорусском?

**Comment by ghost** [comment]
@celestora Как раз таки благодаря оккупации Беларуси безусловно многоуважаемый человек выше допустил настолько дегенератские ошибки в словах

**Comment by ayaaop** [comment]
@celestora

**Comment by cfchnz** [comment]
> @celestora Как раз таки благодаря оккупации Беларуси безусловно многоуважаемый человек выше допустил настолько дегенератские ошибки в словах

окей, я лоханулся в одном слове, но с каких сука пор беларусь это россия?

**Comment by cfchnz** [comment]
и почему уже весь мой перевод это хуйня из-за одной нелепости?

**Comment by cfchnz** [comment]
хорошо, тогда беларусь это 100% россия, ибо беларуский язык очень схож с русским

**Comment by cfchnz** [comment]
давайте сразу присоединим беларусь к россии

**Comment by l3nal3t0va** [comment]
> и почему уже весь мой перевод это хуйня из-за одной нелепости?

тому що Птушка завжди має рацію

**Comment by ghost** [comment]
@cfchnz я тебе щас па халере дам за такие слова

**Comment by cfchnz** [comment]
> @cfchnz я тебе щас па халере дам за такие слова

ок

**Comment by ghost** [comment]
>Вы понимаете, что если бы РФ была более настойчива в своей политике колонизации Беларуси, то мы бы не видели таких сочных срачей о белорусском?

Ви розумієте, що якби люди не сралися, а дружньо перекладали ці рядки, то ми отримали б кращий результат???

**Comment by Lumaeris** [comment]
Никто так и не перевёл ОВК добротно на беларуский, кстати. Появилась возможность переводить на Weblate, что будет в разы легче, чем до этого. https://hosted.weblate.org/projects/openvk/openvk/

@ptushskaya ?

**Comment by l3nal3t0va** [comment]
> >Вы понимаете, что если бы РФ была более настойчива в своей политике колонизации Беларуси, то мы бы не видели таких сочных срачей о белорусском?
> 
> Ви розумієте, що якби люди не сралися, а дружньо перекладали ці рядки, то ми отримали б кращий результат???

срачи веселей, зачем заморачиваться над переводом

**Comment by ghost** [comment]
> > > Вы понимаете, что если бы РФ была более настойчива в своей политике колонизации Беларуси, то мы бы не видели таких сочных срачей о белорусском?
> > 
> > 
> > Ви розумієте, що якби люди не сралися, а дружньо перекладали ці рядки, то ми отримали б кращий результат???
> 
> срачи веселей, зачем заморачиваться над переводом

Справедливо. Але правда в тім, що Білоруська тарашкевиця — дуже погано розвивається. Вона посягає 1 місце в антирекорді. 

І з цим треба щось робити. Хоча б щонайменше 20 рядків перекладеного тексту — це вже добре.

**Comment by ghost** [comment]
> > > > Вы понимаете, что если бы РФ была более настойчива в своей политике колонизации Беларуси, то мы бы не видели таких сочных срачей о белорусском?
> > > 
> > > 
> > > Ви розумієте, що якби люди не сралися, а дружньо перекладали ці рядки, то ми отримали б кращий результат???
> > 
> > 
> > срачи веселей, зачем заморачиваться над переводом
> 
> Справедливо. Але правда в тім, що Білоруська тарашкевиця — дуже погано розвивається. Вона посягає 1 місце в антирекорді по неперекладенності тексту.
> 
> І з цим треба щось робити. Хоча б щонайменше 20 рядків перекладеного тексту — це вже добре.

**Comment by l3nal3t0va** [comment]
> Никто так и не перевёл ОВК добротно на беларуский, кстати. Появилась возможность переводить на Weblate, что будет в разы легче, чем до этого. https://hosted.weblate.org/projects/openvk/openvk/
> 
> @ptushskaya ?

я уже предлагал ей
![IMG_20221206_141936.jpg](https://user-images.githubusercontent.com/63073463/205871187-7b27df11-5304-41a1-bf93-cd01c6abbef0.jpg)
