### ISSUE TITLE
Длинное имя файла при загрузке аватара слегка ломает верстку

### ISSUE THREAD

**Issue by l3nal3t0va** [OpenVK/openvk#789]
![изображение](https://user-images.githubusercontent.com/63073463/203614929-8b01fa37-9e46-4459-b443-8dbd6a363c85.png)
не очень красиво выглядит, как по мне стоит отображать имя файла не полностью

**Comment by celestora** [comment]
Ору

**Comment by l3nal3t0va** [comment]
> Ору

не ори пж

**Comment by LeenzeryDev** [comment]
![изображение](https://user-images.githubusercontent.com/63073463/203617356-55e24bb5-228a-4aa5-b178-9f3ad1f3bfd7.png)
а вообще размутьте пж у меня ломка

**Comment by tretdm** [comment]
Уже можно закрывать, так как [вчерашний редизайн кнопки "Обзор"](https://github.com/openvk/openvk/pull/870) полностью исправил этот недочет.
