### ISSUE TITLE
Не работают ссылки у комментариев

### ISSUE THREAD

**Issue by likhner** [OpenVK/openvk#79]
Не работают ссылки у комментариев (ссылку можете получить нажав на дату комментария)

**Comment by veselcraft** [comment]
Подробнее

**Comment by likhner** [comment]
При нажатии на дату комментария у нас открывается ссылка на комментарий (https://openvk.su/comment3101).
![](https://user-images.githubusercontent.com/60031799/136916597-5dbe0b4f-6b0b-4d5a-9acf-e76b414620b8.png)

Но она не работает.
![](https://user-images.githubusercontent.com/60031799/136916604-5a63fe87-f373-4e98-9461-ab94b33196f1.png)

**Comment by veselcraft** [comment]
Теперь ссылки на комментарии работают так:

https://user-images.githubusercontent.com/22993408/136982732-bec3047b-b836-48ad-9466-344f347cc60e.mp4
