### ISSUE TITLE
OpenVK совместим с infinityfree?

### ISSUE THREAD

**Issue by Remzloi** [OpenVK/openvk#792]
Я захотел сделать свою истанцию OpenVK, но я хз какой халявный хостинг брать, но OpenVK будет совместим с infinityfree?

**Comment by TAB-q** [comment]
Господи, ну все же зависимости Чандлера прописаны, сравни с теми какие на говнохостинге просто

**Comment by TAB-q** [comment]
А лучше купи впс наконец уже

**Comment by celestora** [comment]
> Я захотел сделать свою истанцию OpenVK, но я хз какой халявный хостинг брать, но OpenVK будет совместим с infinityfree?

Скорее всего, нет. Но есть гайд по установке на 000webhost.

**Comment by celestora** [comment]
Основным bottleneck'ом будут индексные дескрипторы, бесплатные хостинги любят повешивать квоту на 5-10к файлов, что, конечно же, пиздец. ОВК в стандартной комплектации будет иметь под 250-400к файлов, емнип. Готовые сборки до 10 может быть влезут, можно вручную оптимизировать ещё сильнее.
В [этом](https://github.com/openvk/openvk/files/10122965/openvk-000webhost.pdf) гайдике дооптимизировались до 7к и даже запустилось, однако в овк много чего поменялось, мб дополнительные действия нужно будет предпринять, для чего желательно иметь руки из плеч.

**Comment by Remzloi** [comment]
спасибо за ссылку на гайд

**Comment by celestora** [comment]
> > 
> 
> у меня нет денег на впс

![image](https://user-images.githubusercontent.com/34442450/204793053-d05557f9-9dfa-460e-9eef-9648fbe4a0f1.png)

**Comment by milesprow3r05** [comment]
@kosharigproekt кошариг ты гений

**Comment by zavolo** [comment]
@celestora хули нытье блять, покажите того кто это написал

**Comment by Remzloi** [comment]
000webhost не работает

**Comment by Remzloi** [comment]
> @kosharigproekt кошариг ты гений

я не кошариг

**Comment by TAB-q** [comment]
ДА НАПИШИ ТЫ В ТГ ЧАТ УЖЕ БЛЯТЬ

**Comment by Remzloi** [comment]
> ДА НАПИШИ ТЫ В ТГ ЧАТ УЖЕ БЛЯТЬ

ладно

**Comment by NoPlagiarism** [comment]
> 000webhost

1. Это отдельная проблема. Либо создавать новую issue, либо переименовать эту
2.  ***ЗАПОМНИТЕ!***
## Не под всё нужно создавать issue
Обратите внимание на 
- [Дискуссии ](https://github.com/openvk/openvk/discussions)
- [ТГ Чат](https://t.me/openvkenglish)

**Comment by NoPlagiarism** [comment]
@kotmobile а теперь можно уже закрыть?

**Comment by Remzloi** [comment]
> @kotmobile а теперь можно уже закрыть?

да

**Comment by themohooks** [comment]
у меня этих дедиков жопой жуй, дам за небольшую плату либо за рекламу тг @mohooks
