### ISSUE TITLE
Concept: Оновлена головна сторінка OpenVK 

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#794]
![concept](https://user-images.githubusercontent.com/119857758/205808215-86431eb3-2408-4ae8-8c97-2856df15ff7a.png)

Хеадер:
1. Прибрано вхід\реєстрація (вони вже є на сторінці, нащо їм спамити?)
2. Прибрано "Допомога" (вона не працює, якщо не увійти)

Page_Content
1. Прибрано вхід\реєстрація (див Хедер, 1.)

Футер:
1. Видалено допомога (див. Хедер 2.)
2. Видалена інформація про сервер (її, якщо треба. можна переглянути в "про інстанцію")
3. Видалені незначущі\неактивні соц.мережі.
4. Видалена лого Debian (значущість?)

**Comment by A1esA1te** [comment]
![concept](https://user-images.githubusercontent.com/119857758/205807289-9506f1f0-56c1-4bfe-b535-aa36dc7e2f3d.png)

**Comment by NoPlagiarism** [comment]
`незначущі\неактивні`

Ни до конца уверен, стоит ли удалять Discord. Не у всех есть телега, да и в дс есть канал с github updates. Ну это, как по мне

Mastodon - для любителей нон-проприетарщины. Не вижу смысла удалять его тоже. Вкусовщина возможно

**Comment by ghost** [comment]
> `незначущі\неактивні`
> 
> Ни до конца уверен, стоит ли удалять Discord. Не у всех есть телега, да и в дс есть канал с github updates. Ну это, как по мне
> 
> Mastodon - для любителей нон-проприетарщины. Не вижу смысла удалять его тоже. Вкусовщина возможно

Ну добре, хай буде.

**Comment by veselcraft** [comment]
Лого дебиана, ссылки и текст это прикол основного инстанса, да и кнопка "помощь" на деле не работает с неавторизированными юзерами. ~~Но вот нахуя было менять флаги вопрос интересный~~

**Comment by celestora** [comment]
> Лого дебиана, ссылки и текст это прикол основного инстанса, да и кнопка "помощь" на деле не работает с неавторизированными юзерами. ~Но вот нахуя было менять флаги вопрос интересный~

У нас кстати некоторые магазины украинские русский язык оставили, но флаг сменили на бгб. У тех кто беларуский поддерживает бчб отрос, но это ещё с 2020, кек.

**Comment by veselcraft** [comment]
> > Лого дебиана, ссылки и текст это прикол основного инстанса, да и кнопка "помощь" на деле не работает с неавторизированными юзерами. ~Но вот нахуя было менять флаги вопрос интересный~
> 
> У нас кстати некоторые магазины украинские русский язык оставили, но флаг сменили на бгб. У тех кто беларуский поддерживает бчб отрос, но это ещё с 2020, кек.

Оппозиция одобряет, +10 евро от евросоюза :trollface:

**Comment by ghost** [comment]
> Лого дебиана, ссылки и текст это прикол основного инстанса, да и кнопка "помощь" на деле не работает с неавторизированными юзерами. ~Но вот нахуя было менять флаги вопрос интересный~

"Пасхальне яйце". Цього я, звичайно, реалізовувати не прошу. Але тут за бажанням)))

**Comment by ghost** [comment]
>да и кнопка "помощь" на деле не работает с неавторизированными юзерами.

Мені здається, це заслуговує окремого пулл реквесту. Бо користувачам, які втратили доступ до акаунту, треба якось зв'язатися з підтримкою.

>У нас кстати некоторые магазины украинские русский язык оставили, но флаг сменили на бгб.

![image](https://user-images.githubusercontent.com/119857758/206095855-d7a1cc7e-04a0-4daa-a5c8-bd1816b66c5c.png)
Є таке.

**Comment by TAB-q** [comment]
Пикча с дебианом по фану только на основном инстансе, инфу в футере я бы оставил включаемой/отключаемой, остальное чистая вкусовщина и не идет по канонам вк

**Comment by TAB-q** [comment]
@TAB-q Только там же да?

**Comment by ghost** [comment]
Про пікчу з дебіан\іншої ОС:
Я пропоную білий фон зробити прозорим, бо в умовній темній темі біле не фарбується.

> инфу в футере я бы оставил включаемой/отключаемой

Я нарахував 3 клавіші Входу чи Реєстрації. Мені знається, це забагато.

**Comment by celestora** [comment]
@A1esA1te "Язык"

**Comment by ghost** [comment]
@celestora ?

**Comment by celestora** [comment]
@A1esA1te Гитхаб бот не умеет цитировать сообщения, там просто на скрине русский язык назвали просто языком, смешно звучит. Стало быть беларуский это теперь "белый язык", смешное.

**Comment by NoPlagiarism** [comment]
> Стало быть беларуский это теперь "белый язык", смешное.

Не, это "мова"
Так и запишем. `Українська`, `Язык` и `Мова`

> инфу в футере я бы оставил включаемой/отключаемой

Кстати, реально было бы удобно. (Ну или лучше настраиваемой)

Тогда всё подробное стоит перенести куда-то, например в "Об инстанции"

**Comment by ayaaop** [comment]
украинский это тоже мова так то
так что надо сделать так: Мова 1, Язык, Мова 2

**Comment by NoPlagiarism** [comment]
> украинский это тоже мова

Знаю, но как теперь отличить-то? Верно, так что тут либо украинским жертвовать, либо белорусским

**Comment by myslivets** [comment]
> > украинский это тоже мова
> 
> Знаю, но как теперь отличить-то? Верно, так что тут либо украинским жертвовать, либо белорусским

легко
Белорусский - be_BY
Украинский - uk_UA

**Comment by NoPlagiarism** [comment]
@myslivets не, мы тут над другим ржём. Там сверху скриншот

**Comment by myslivets** [comment]
> @myslivets не, мы тут над другим ржём. Там сверху скриншот

**капеееец, оказывается я многое тут прозевал**
![hyper-anime](https://user-images.githubusercontent.com/60743585/206407426-66e96847-1b9f-4fd8-ba54-eb77ffb43d7e.gif)

**Comment by NoPlagiarism** [comment]
## Итог (с моей колокольни)

- Header
   - Вход/Регистрация неавторизованным пользователям там ненужны, но если я не ошибаюсь такой прикол был в вк (сейчас там в хидере только регистрация)
   - Кнопка помощи у неавторизованных пользователей не работает. Зачем она там?
- Page Content
   - прямых ссылок вроде тоже не надо (уже есть). так что согласен
- Footer
   - Кнопка помощи всё ещё не работает
   - Если удалять информацию про сервер их футера, то её нужно полностью перенести на страницу "об инстанции"
   - Соц. сети пусть там остаются
   - Дебиан... Ну.... Ещё скажу, что эта картинка ужасно смотрится на тёмных темах. Она тупо с белым фоном

**Comment by NoPlagiarism** [comment]
> Она тупо с белым фоном

![Debian on OpenVK Midnight](https://user-images.githubusercontent.com/37241775/206412077-3871e9cc-fd94-4d90-a8de-f7016e58413a.png)

**Comment by ghost** [comment]
>Итог (с моей колокольни)

Справедливо.
