### ISSUE TITLE
Прикрепление видео с YouTube к стене пользователя

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#799]
~~1. Youtube має щось типу "режим підвищеної конфіденційності". На знімку з екрана показано, що воно означає.
Але різниця в тім, що вона посилається на "https://www.youtube-nocookie.com/embed/", аніж на "https://www.youtube.com/embed/ZzZ1qmXZBuY"
![image](https://user-images.githubusercontent.com/119857758/206572798-f2b2a6b2-e071-4493-93cc-94df7f7f380d.png)
Передбачаю запитання: Ярославе, ти до чого?
Відповім: Я пропоную звичайний emdedded на запропонований~~

2. Було б зручно додавати відео з ютубу до посту. Бо у /videos/upload/ можна додавати відео з ютуб, а до посту — ні. Додаю знімок екрана, щоб було більше зрозуміло, про що я.
![image](https://user-images.githubusercontent.com/119857758/206575060-b80f1205-eec4-41cb-9378-ab1ad05964d1.png)

**Comment by celestora** [comment]
не думаю что это как-то поможет но ладно

**Comment by ghost** [comment]
> не думаю что это как-то поможет но ладно

Типу фіча для анонімусів і для тих, хто вважає, що влада за усіма стежить 💀💀💀

**Comment by celestora** [comment]
> > не думаю что это как-то поможет но ладно
> 
> Типу фіча для анонімусів і для тих, хто вважає, що влада за усіма стежить 💀💀💀

ох уж эта владислава.......

**Comment by NoPlagiarism** [comment]
@A1esA1te закрывай issue

@celestora почему после pull на мейне нельзя закрыть issue?

**Comment by ghost** [comment]
> @A1esA1te закрывай issue

Читай другий пункт.

**Comment by NoPlagiarism** [comment]
> Читай другий пункт.

Окей. Без вопросов

**Comment by NoPlagiarism** [comment]
Могу понять, что остальные issue приняли колёса

Но с этим что не так? Прикрепление видео с других ресурсов в пост - вещь всё ещё нужная.
