### ISSUE TITLE
Двойные уведомления об упоминании/ответе

### ISSUE THREAD

**Issue by SigmaTel71** [OpenVK/openvk#803]
Возможно, связано с #464. После появления уведомлений об упоминании/ответе на чужой стене, стали проявляться [интересные](https://openvk.su/wall6588_96) глюки.

**Comment by NoPlagiarism** [comment]
![img](https://ru-spb.openvk.uk/hentai/24/24f8480da8de69771477e06bea2ad0e6bb9822aaa970e4ebad323f7f2178a80d7861e28593de26fc72bfc75ce0aa33faf4a30d4080a8c06abbd1947198f7a800_cropped/large.gif)
![img](https://ru-spb.openvk.uk/hentai/3e/3e87084386ec90c6d4c1731ccba96043e06ae2f2fe34fde55dec8b81a0b77f0f550a9d6e288a495c1277a71139cfdcbfa7bf1448f256c3b623dcdd8c48013bd8_cropped/normal.jpeg)

**Comment by celestora** [comment]
Пофикшено i guess
