### ISSUE TITLE
Параметр start_from в api методе Newsfeed.get работает некорректно

### ISSUE THREAD

**Issue by l3nal3t0va** [OpenVK/openvk#808]
Если указывать больше нуля, то не возвращает ни одного поста
![изображение](https://user-images.githubusercontent.com/63073463/207932539-26c0b840-70d4-4798-aa88-9bff0ef79ad7.png)

![изображение](https://user-images.githubusercontent.com/63073463/207932773-01eb3007-e38f-4d4f-9571-2983f1129449.png)

**Comment by NoPlagiarism** [comment]
```"id < (?)", empty($start_from) ? PHP_INT_MAX : $start_from```
Как можно увидеть здесь...... Мне кажется, что start_from не называется так как нужно...

Я вообще не уверен, так ли это должно работать. Лучше уж через timestamp подобное делать наверное, не?

**Comment by l3nal3t0va** [comment]
> `"id < (?)", empty($start_from) ? PHP_INT_MAX : $start_from` Как можно увидеть здесь...... Мне кажется, что start_from не называется так как нужно...
> 
> Я вообще не уверен, так ли это должно работать. Лучше уж через timestamp подобное делать наверное, не?

нихуя не понял, если честно, что ты хотел донести

**Comment by veselcraft** [comment]
# Нормальный ответ

Нужно понимать, для чего нужен `start_from`. Как описывают его в самом ВК:
> Идентификатор, необходимый для получения следующей страницы результатов. Значение, необходимое для передачи в этом параметре, возвращается в поле ответа next_from.

# токсичный

ну блять естественно если ты туда высреш единицу оно работать не будет, ты вообще смотрел как его юзать?

**Comment by NoPlagiarism** [comment]
> нихуя не понял

Проблема в том, что `start_from`  работает с помощью внутреннего id в таблице базы данных. 
Вводя `start_from=1`, он начинает искать все посты с id меньше одного. Следовательно, хуй что он выдаст

**Comment by l3nal3t0va** [comment]
ладно я тупой простите

**Comment by veselcraft** [comment]
Так вам надо в `start_from` прописывать значение из `next_from`, чтобы следующая страница была. Вопрос максимально тупой

**Comment by NoPlagiarism** [comment]
Всё же, думаю `start_time` и `end_time` не помешали бы

**Comment by NoPlagiarism** [comment]
> ну блять естественно ... ты вообще смотрел как его юзать?

Каждый раз, чтоб узнать что как работает, лезем в source code и доки VK, вместо OpenVK (ведь в них нихуя нету). Пон
