### ISSUE TITLE
[API] Wall.getComment if no comment => return error

### ISSUE THREAD

**Issue by NoPlagiarism** [OpenVK/openvk#810]
Нет обработки ошибки, возвращает 500 Server Error

**Comment by tretdm** [comment]
![Screenshot_20221221-153356](https://user-images.githubusercontent.com/76806170/208857919-c51b65b0-1a11-463e-9bb2-87d9d079210e.png)
![Screenshot_20221221-153414](https://user-images.githubusercontent.com/76806170/208857947-b8c0718c-1da0-450a-b2ad-4bbdbe324373.png)

Да чет не видать, что сервер отправляет ошибку, когда нет комментариев. Это, кстати, логи из приложения OpenVK Legacy, там же идет подключение к инстанции https://openvk.uk.

**Comment by NoPlagiarism** [comment]
> Да чет не видать, что сервер отправляет ошибку, когда нет комментариев. 

Это речь о `Wall.getComments`. Я же говорю о `Wall.getComment`

Просто попробуйте сравнить:
[`Wall.getComment?owner_id=0&comment_id=12312&access_token=vash-token-jill`](https://openvk.su/method/Wall.getComment?owner_id=0&comment_id=12312&access_token=vash-token-jill)

[`Wall.getComment?owner_id=0&comment_id=55555&access_token=vash-token-jill`](https://openvk.su/method/Wall.getComment?owner_id=0&comment_id=55555&access_token=vash-token-jill)

**Comment by NoPlagiarism** [comment]
Ну, и ещё вдобавок оставлю строку с кодом здесь
https://github.com/openvk/openvk/blob/08499cd3b4dd3ff575e6819fd8931d20f6647f7a/VKAPI/Handlers/Wall.php#L637
Без всяких try и catch

**Comment by NoPlagiarism** [comment]
Fixed in https://github.com/openvk/openvk/commit/63702d44d1587d85049cb334bb8564c81e1b9b70
