### ISSUE TITLE
Редактирование постов и комментариев

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#812]
Предлагаю добавить эту фичу для быстрого редактирования, чтобы не переделывать и не отправлять пост заново. То же самое, касается и комментариев, и записей в обсуждениях.

**Comment by tretdm** [comment]
(да, ну вы поняли, что я здесь отрдачил 😊)

**Comment by tretdm** [comment]
https://github.com/openvk/openvk/pull/696
я кстати видел pr, но в коммитах чет доделали. мда

**Comment by NoPlagiarism** [comment]
> в коммитах чет доделали

Чёт не доделали? Или не то сделали?

Или это ещё один PR от n1rwana (и не только его), который так и не могут проверить?

**Comment by tretdm** [comment]
думаю, что первое

**Comment by tretdm** [comment]
ибо видно, что changes requested

**Comment by NoPlagiarism** [comment]
> ибо видно, что changes requested

Да уже как несколько месяцев, PR успел состариться и ждёт разрешения конфликтов
