### ISSUE TITLE
Кривая вёрстка ошибки на странице входа

### ISSUE THREAD

**Issue by iamdelickkk** [OpenVK/openvk#820]
Кароч разрабы пофиксите эту фигню на странице входа, это легко же ведь...
![image](https://user-images.githubusercontent.com/91693467/210328404-e654d0b3-130d-41b1-abf6-83a7c21054f7.jpeg)

**Comment by NoPlagiarism** [comment]
https://github.com/openvk/openvk/blob/462d667e53bb2bb9eac89be7ab594e35d0ffdf9b/Web/static/css/style.css#L948

Если исправить `margin-bottom` хотя бы на `12pt`, то получится это

![Example](https://user-images.githubusercontent.com/37241775/210332378-f39b5a0e-d3d8-464d-a265-72910c4595b9.png)
