### ISSUE TITLE
Japanese names and surnames are translated into Chinese

### ISSUE THREAD

**Issue by vlapskii** [OpenVK/openvk#834]
Japanese names and surnames are translated into Chinese language although the database are stored japanese text.

<img width="225" alt="Screenshot 2023-01-24 at 00 06 32" src="https://user-images.githubusercontent.com/94683384/214127552-7d8db183-ce25-416a-a75a-5bdfa9a85833.png">
<img width="355" alt="Screenshot 2023-01-24 at 00 06 47" src="https://user-images.githubusercontent.com/94683384/214127595-2ee15c0d-64ad-4373-9c73-98a2e8d15035.png">
<img width="1312" alt="Screenshot 2023-01-24 at 00 07 34" src="https://user-images.githubusercontent.com/94683384/214127763-489567c9-3e6e-4b8e-b848-2ec0d81dfe14.png">

**Comment by celestora** [comment]
Китайские иероглифы ничем не отличаются от японский. Это связано с тем, что японских иероглифов не существует, они все китайские. Или большинство. Они всегда будут транслитерироваться правилом "Any-Latin" по китайскому чтению, потому что транслитератор не видит страничку юзера чтобы понять манга там или маньхуа у него на аве.\
Конечно гугл тут предполагает, что это имя и исходя из этого переводит с японского. Можно было бы перед Any-Latin въебать перевод с японского чтобы был приоритет, но тогда китайские имена пойдут по пизде.\
Интересно то, что ВКонтакте не переводит именно китайские иероглифы. Может быть нам тоже не переводить их, поменяв правило на `[:^script=Han:] Any-Latin`?

**Comment by veselcraft** [comment]
@celestora да
