### ISSUE TITLE
OpenVK API: Добавление поддержки видео в стенах и лентах новостей через API

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#835]
![изображение](https://user-images.githubusercontent.com/76806170/214359088-5b182643-4690-45e8-9851-f80c59c52c80.png)

Слева в массиве `attachments` должна быть информация о вложенном видеоролике (!), когда OpenVK API показывает только информацию о вложенной фотографии.

**Comment by celestora** [comment]
ой

**Comment by NoPlagiarism** [comment]
Fixed in https://github.com/openvk/openvk/commit/43e18a9173169812ad7e67dca60d1940e9239b33
