### ISSUE TITLE
OpenVK API: Добавление поддержки вложенных фотографий в комментариях

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#836]
![Screenshot_20230125-001639](https://user-images.githubusercontent.com/76806170/214362238-16f6c597-e578-4ff2-8ed6-86ddbea497b7.png)

На этот раз нет массива `attachments` для показа вложений в методе `Wall.getComments`. Вот параметры к нему: `owner_id=2287&post_id=26&extended=1&count=50`

Веб-версия для сравнения: https://openvk.uk/wall2287_26#comments

**Comment by NoPlagiarism** [comment]
Fixed in https://github.com/openvk/openvk/commit/06b77ebad81589ed7c7f61b40be7611aab8dfc69
