### ISSUE TITLE
новый плеер

### ISSUE THREAD

**Issue by WhO2022** [OpenVK/openvk#845]
дайте видео скачать, новый ваш плеер нихера не даёт

**Comment by iamdelickkk** [comment]
тебе лишь бы овк обосрать

**Comment by saursvepur** [comment]
Воспользуйся для этого просмотром кода элемента

**Comment by saursvepur** [comment]
![image](https://user-images.githubusercontent.com/55963296/216714337-a912bff4-67b4-4bd9-bc18-c223b163c270.png)

чё ждан, словил неждан?

**Comment by WhO2022** [comment]
![поололо](https://user-images.githubusercontent.com/115972850/216754934-7d89b0cd-b85e-4e5c-801f-6cdd207f3dd3.png)

**Comment by WhO2022** [comment]
хотя бы в vepurovk есть

**Comment by iamdelickkk** [comment]
кококоококококо основной инстанс опенвк говно кокоокококококококоокококок вепуровк лучши кокоокококок

**Comment by WhO2022** [comment]
> кококоококококо основной инстанс опенвк говно кокоокококококококоокококок вепуровк лучши кокоокококок

внатуре, зачем падающий openvk

**Comment by WhO2022** [comment]
> кококоококококо основной инстанс опенвк говно кокоокококококококоокококок вепуровк лучши кокоокококок
внатуре, зачем падающий openvk

**Comment by Lumaeris** [comment]
не понял только зачем надо было закрывать issue

**Comment by myslivets** [comment]
> хотя бы в vepurovk есть

вот предлагаю тебе своё нытье перенести туда, хорошего дня!

**Comment by celestora** [comment]
не понял только зачем надо было закрывать issue

**Comment by veselcraft** [comment]
и переоткрывать его тоже

**Comment by iamdelickkk** [comment]
не понял только зачем надо было закрывать issue

**Comment by tretdm** [comment]
а я только за вами наблюдал и заржал :rofl:
