### ISSUE TITLE
Я могу написать заблокированному пользователю в ЛС

### ISSUE THREAD

**Issue by themohooks** [OpenVK/openvk#846]
![image](https://user-images.githubusercontent.com/81331307/218050775-bbd48714-9b92-4487-8259-ea292bf0140e.png)
![image](https://user-images.githubusercontent.com/81331307/218050812-226ece9a-6894-4dd6-b787-5de5e002ccdb.png)

**Comment by veselcraft** [comment]
Такое и в ВК *раньше* было, wontfixНадіслано з iPhone10 лют. 2023 р. о 12:10 themohooks ***@***.***> пише:﻿
