### ISSUE TITLE
Сломанная верхняя панель в мобильной версии под Opera Mobile 12.18

### ISSUE THREAD

**Issue by w01te** [OpenVK/openvk#847]
Имеется проблема с мобильной версией сайта в Opera Mobile 12.18 - глючит верхняя панель и не открывается главное меню, из-за чего невозможно ни серфить по сайту, ни перейти на десктопную версию сайта.

Проявляется в версии браузера и под Symbian OS, и под Android.

![shot_093_2023_02_12_024824](https://user-images.githubusercontent.com/108619723/218286413-62aea4fc-3280-40d2-a1c9-6ca0a4cfd757.png)
![IMG_20230212_030708](https://user-images.githubusercontent.com/108619723/218286425-1bf0be64-c0d7-448c-9920-746c8b99e04f.jpg)

**Comment by ghost** [comment]
Wont fix, не касается самого OpenVK. Вам в /openvk/mobile_ovk
