### ISSUE TITLE
Ссылка на видео по контекстому меню плеера не копируется в буфер обмена

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#848]

**Comment by tretdm** [comment]
Только щас показал почему это фича не работает.
https://github.com/openvk/openvk/assets/76806170/81ddf3f5-7bfc-46a0-9b28-ea2d26b8864c

**Comment by ghost** [comment]
А почему иссуе открыт

**Comment by ghost** [comment]
Ну, по этой кнопке копируется ссылка на видеофайл, а не на страницу с видео, но будем считать что исправлено.
