### ISSUE TITLE
В семейном положении нельзя указать человека

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#853]
<table><tr><td>OpenVK</td><td>VK</td></tr><tr><td><img src="https://user-images.githubusercontent.com/69392185/220893355-c9ea19fa-fddc-4df8-bef7-d2c477dd7a4a.png"></td><td><img src="https://user-images.githubusercontent.com/69392185/220893113-2c83edbd-873b-473b-a741-b0aeac8e4fc0.png"></td></tr></table>

**Comment by NoPlagiarism** [comment]
Ждём всякие профили вроде "Себь Любимый", но в OpenVK?

**Comment by m1chigunprog** [comment]
То есть что бы можно было добавить пользователя OpenVK с кем у тебя отношения?

**Comment by NoPlagiarism** [comment]
@m1chigunprog да
Идея неплохая, но хз

**Comment by Lumaeris** [comment]
Так это же круто, пусть подобное будет загадкой. :trollface:
