### ISSUE TITLE
Возможность нарисовать граффити в комментах

### ISSUE THREAD

**Issue by ayaaop** [OpenVK/openvk#854]
![Screenshot 2023-02-23 at 17-55-00 Запись - OpenVK](https://user-images.githubusercontent.com/58212796/220898935-91c1052e-f3ce-4ba2-8af7-67c78411f9fb.png)
где???? _я хотел нарисовать туда мужской половой орган_

**Comment by m1chigunprog** [comment]
Возможно граффити можно рисовать только на стену.

**Comment by m1chigunprog** [comment]
Типо логично что стена это стена на ней можно рисовать граффити

**Comment by m1chigunprog** [comment]
А коментарии это палотно на нём нельзя

**Comment by ayaaop** [comment]
а почему в вк в сообщениях еще можно нарисовать граффити тогда

**Comment by ayaaop** [comment]
это же не стена?1?1?1??1??1????1?

**Comment by m1chigunprog** [comment]
У них соц сеть не логичная

**Comment by Lumaeris** [comment]
> У них соц сеть не логичная

Как и у нас. И что изменилось? 🤔

**Comment by n1rwana** [comment]
> [quirks.yml](https://github.com/openvk/openvk/blob/master/quirks.yml)

`comments.allow-graffiti: 1`

![image](https://github.com/openvk/openvk/assets/93197434/edb0cf7b-473e-4e3a-9a42-409d49774485)

**Comment by ayaaop** [comment]
базару нет
