### ISSUE TITLE
Нет аватарок, страница грузится постоянно

### ISSUE THREAD

**Issue by nlasted** [OpenVK/openvk#866]
![image](https://user-images.githubusercontent.com/129321161/233845666-bf6ebd4e-2313-44f4-85ed-d5a6528d1994.png)
openvk.uk / openvk.su работают
openvk.co не открывается, я думаю причина в том то что картинки идут с этого домена

**Comment by celestora** [comment]
Но картинки не идут с openvk.co, они идут с ru-spb.openvk.uk

**Comment by Lumaeris** [comment]
![image](https://user-images.githubusercontent.com/10499845/233845857-496c2301-d2c4-4b67-800c-b94c3d6aac2f.png)
Не могу подтвердить.

<details>
<summary>.</summary>

*works on my machine.*

</details>

**Comment by nlasted** [comment]
Странно, у меня почему-то не работает

**Comment by WerySkok** [comment]
Не проблема движка
