### ISSUE TITLE
Счетчик онлайна

### ISSUE THREAD

**Issue by Alexxxxand** [OpenVK/openvk#878]
Сделайте счетчик онлайна на сайте

**Comment by myslivets** [comment]
Наверное такое можно сделать с введением новой системы поиска по сайту)

**Comment by saursvepur** [comment]
Он же и так есть в разделе "об инстанции" разве не?

**Comment by NoPlagiarism** [comment]
Относительно дубликат #768, если думать об этом, как о фиче в поиске

А так да, есть в "Об инстанции"

https://openvk.su/about
