### ISSUE TITLE
Возможность пользователю закрыть тикет

### ISSUE THREAD

**Issue by Artem13327** [OpenVK/openvk#879]

**Comment by tretdm** [comment]
Попробую сейчас разъяснить. 

Во ВКонтакте каждый тикет в поддержку имеет нижнюю плашку для выполнения действия (можно либо закрыть тикет, либо продолжать обсуждение с агентами), только в данном случае я уже закрыл.
![изображение](https://github.com/openvk/openvk/assets/76806170/d1fa177e-e3cc-40e1-b942-e2938d76bc11)
