### ISSUE TITLE
VKAPI: Заглушка забаненного аккаунта

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#881]
<img src="https://github.com/openvk/openvk/assets/76806170/e486cd15-19a3-4498-96fd-ab9e1cb03cc5" height="240"></img>  <img src="https://github.com/openvk/openvk/assets/76806170/6150a4f7-ef83-400d-8d01-e5f50398a8d6" height="241"></img>
(слева - забаненный, справа - удалённый)

**Comment by tretdm** [comment]
Еще один пример, только уже с полями `photo_100` и `status`. А заглушки явно не хватает для забаненных юзеров (в веб-версии она уже есть)

![firefox_sSJlHecUk4](https://github.com/openvk/openvk/assets/76806170/f2622dde-fc3f-4ea2-87be-836fd38fbef3)
![vpQbEbTsTt](https://github.com/openvk/openvk/assets/76806170/df346568-dbfe-4baa-8ef6-21a9ad7bc4e7)

**Comment by NoPlagiarism** [comment]
В вк блок выглядит так же, как и удалённый, как я понял

![image](https://github.com/openvk/openvk/assets/37241775/b28a7bcc-c62a-4d63-bf09-4b6c49d24e4d)

**Comment by tretdm** [comment]
Но логичнее обозначить значением `banned`, чтобы API-клиент понимал, что она заблокирована, но не удалена.

**Comment by tretdm** [comment]
И при желании можно добавить строку `reason` с указанием на причину бана.

**Comment by NoPlagiarism** [comment]
> Но логичнее обозначить значением banned, 

Да, это я немного берега попутала.

**Comment by veselcraft** [comment]
> Но логичнее обозначить значением `banned`, чтобы API-клиент понимал, что она заблокирована, но не удалена.

Ну так там это и обозначено как раз

**Comment by NoPlagiarism** [comment]
> Ну так там это и обозначено как раз

Коммент обновлён, там была ошибка у меня

**Comment by tretdm** [comment]
Я и забыл, что issue #622 уже висит закрытым, но чет реально не досмотрели. Закрываю как дубликат.
