### ISSUE TITLE
Предложения: товары, штатные репорты, стикеры, эмодзи и спонсорские подписки

### ISSUE THREAD

**Issue by necoarc126** [openvk/openvk#887]
# **я надеюсь это не будет выглядить кринжом хз я никогда не пишу с большой буквы**

## **Насчет товаров**
**Как должно это работать?**
Товары в группах должны выглядеть как в оригинальном ВК, однако там не должно быть чего-либо из реальной жизни (игрушки, сувениры), а например ключи к играм. Покупаться они должны за голоса. 
**Кому они будут доступны?**
Товары можно получить написав в поддержку, конкретнее, эту функцию можно будет получить, если выполнена одна из критерий:
1. Группе есть больше 45 дней;
2. Создатель группы верифицирован и не имел никаких наказаний ранее;
3. Создатель имеет хорошую репутацию в сообществе;
4. У создателя группы есть хотя бы одна соц. сеть с 150+ подписчиками (для сервисов с короткими видео 1500+).

## Штатные репорты
Просто удобная кнопка для репортов на группы или пользователей. Тут все понятно.

## Короткие ссылки
**Зачем?**
Бывает, что у человека есть нужда сократить ссылку на пост с мемчиком в ОпенВК, либо у человека ссылка на профиль это - *"openvk.uk/theprogamerermakovcool2011"*.
**Как будет выглядеть ссылка?**
Как у всех сервисов по сокращению ссылок, например  - *"openvk.uk/stuJj1"*

## Стикеры
**Как это должно работать?**
Как стикеры в любом мессенджере, но еще и на стене.
**Как они должны выглядеть?**
Размер стикера - *500х500*, расширение - *PNG*. [Их пример на форуме Аризоны РП](https://forum.arizona-rp.com/threads/6420383/).

## Эмодзи
**Как это должно работать и выглядеть?**
Как типичные эмодзи на старых форумах. Размер эмодзи - *15х15*, расширение - *PNG/GIF*. [Их пример на форуме Онлайнера](https://forum.onliner.by/viewtopic.php?t=835381).

## Спонсорские подписки
**Что?**
Подписки должны быть как аналог бусти в ОпенВК, но с голосами вместо реальной валюты
**Как это должно работать?**
Человек находит любимую группу своего кумира Ермакова, и если на этой группе есть спонсорские подписки, то человек оформляет ее за пару голосов (кол-во от 1 голоса до 1000) в день (срок от дня до недели).
**Кому они будут доступны?**
Подписки можно получить написав в поддержку, конкретнее, эту функцию можно будет получить, если выполнена одна из критерий:
1. Группе есть 30 дней;
2. Создатель группы верифицирован;
3. Создатель имеет хорошую репутацию в сообществе;
4. У создателя группы есть хотя бы одна соц. сеть с 100+ подписчиками (для сервисов с короткими видео 1000+).

# Надеюсь на то, что первое или последнее предложение будут выполнены, остальные придумал от скуки.

**Comment by necoarc126** [comment]
надеюсь я куда нужно написал

**Comment by celestora** [comment]
> надеюсь я куда нужно написал

Пожелания по основному инстансу это не то, что нужно лулить в issues движка, так как имеет к нему весьма косвенное отношение. Связанный с упомянутыми вами фичами функционал даже, скорее всего, уже был оформлен как issue и где-то в глубине ~~родильных ям гоблинов~~ этого баг-трекера отслеживается.
