### ISSUE TITLE
Убрать принудительную конвертацию видео в формат 4:3

### ISSUE THREAD

**Issue by iamdelickkk** [OpenVK/openvk#890]
С введением нового HTML5 плеера отпала необходимость конвертировать видео в 4:3, ибо сам плеер и так зафиксирован на одном необходимом формате.

Предлагается в скриптах подменить
`scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2 ` 
на 
`scale=480:-1, pad=480:-1:(ow-iw)/2:(oh-ih)/2`

**Comment by aqukie** [comment]
Долбоёб не матерись блядь, нас дети смотрят, ебись они конём

**Comment by iamdelickkk** [comment]
zа победу
СВОим не бросаем

> Долбоёб не матерись блядь, нас дети смотрят, ебись они конём

**Comment by aqukie** [comment]
> zа победу
> СВОим не бросаем

Ты че, уебан?

**Comment by iamdelickkk** [comment]
> > zа победу
> > СВОим не бросаем
> 
> Ты че, уебан?

сила V правде

**Comment by aqukie** [comment]
> > > zа победу
> > > СВОим не бросаем
> > 
> > 
> > Ты че, уебан?
> 
> сила V правде

Что еще скажешь?

**Comment by iamdelickkk** [comment]
> > > > zа победу
> > > > СВОим не бросаем
> > > 
> > > 
> > > Ты че, уебан?
> > 
> > 
> > сила V правде
> 
> Что еще скажешь?

вова путин молодец

**Comment by aqukie** [comment]
> > > > > zа победу
> > > > > СВОим не бросаем
> > > > 
> > > > 
> > > > Ты че, уебан?
> > > 
> > > 
> > > сила V правде
> > 
> > 
> > Что еще скажешь?
> 
> вова путин молодец

Молодец, ахуенный юмор, прямо пиздатый, а теперь пиздуй нахуй, уебище залупоглазое

**Comment by iamdelickkk** [comment]
> > > > > > zа победу
> > > > > > СВОим не бросаем
> > > > > 
> > > > > 
> > > > > Ты че, уебан?
> > > > 
> > > > 
> > > > сила V правде
> > > 
> > > 
> > > Что еще скажешь?
> > 
> > 
> > вова путин молодец
> 
> Молодец, ахуенный юмор, прямо пиздатый, а теперь пиздуй нахуй уебище залупоглазое

я подожду пока кто то из разрабов мне answer

**Comment by zavolo** [comment]
дети закройте уши и глаза

**Comment by saursvepur** [comment]
Ребята, приключений час! Ждут давно чужие земли нас

**Comment by aqukie** [comment]
> > > > > > > zа победу
> > > > > > > СВОим не бросаем
> > > > > > 
> > > > > > 
> > > > > > Ты че, уебан?
> > > > > 
> > > > > 
> > > > > сила V правде
> > > > 
> > > > 
> > > > Что еще скажешь?
> > > 
> > > 
> > > вова путин молодец
> > 
> > 
> > Молодец, ахуенный юмор, прямо пиздатый, а теперь пиздуй нахуй уебище залупоглазое
> 
> я подожду пока кто то из разрабов мне answer

Не жди, просто убейся.

**Comment by NoPlagiarism** [comment]
блять.

**Comment by prow3r05** [comment]
блять да где  груши в залог вриски купить

**Comment by Lumaeris** [comment]
https://github.com/openvk/openvk/assets/10499845/3477a65f-a5cc-418a-9928-06ee83c3ba65

**Comment by ayaaop** [comment]
что здесь было

**Comment by iamdelickkk** [comment]
сделайте что нибудь пожалуйста🇷🇺🇷🇺🇷🇺🇺🇦🇺🇦🇺🇦

**Comment by celestora** [comment]
> вы серьёзно? какие 4:3???? вы можете заменить вместо `scale=640:480:force_original_aspect_ratio=decrease,pad=640:480:(ow-iw)/2:(oh-ih)/2 ` на `scale=480:-1, pad=480:-1:(ow-iw)/2:(oh-ih)/2`???? или я что то не понимаю и я тупой???

если честно я ничего не понял

**Comment by tretdm** [comment]
> или я что то не понимаю и я тупой???

а я бы сделал ещё попроще, при этом оставив 480p и пропорцию кадров
`scale=-1:480`

_было бы круто, если откликнутся на issue #877, но увы, финансы_

**Comment by veselcraft** [comment]
Исправлено коммитом https://github.com/OpenVK/openvk/commit/2aedc3e86195c01c4faf3e0baaa5d4bbc9cb78b5

**Comment by ghost** [comment]
> Исправлено коммитом [2aedc3e](https://github.com/OpenVK/openvk/commit/2aedc3e86195c01c4faf3e0baaa5d4bbc9cb78b5)

Ай тигр💪💪
