### ISSUE TITLE
Не полный перевод English

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#90]
Не полный перевод в английском языке (HelpDesk)
![image](https://user-images.githubusercontent.com/90477403/132982915-09c72489-505e-4760-b641-a5aa4978ff38.png)
а так же в разделе помощь
![image](https://user-images.githubusercontent.com/90477403/132982931-64e3ca93-91b3-4143-8a1f-bb2806d1042a.png)

**Comment by veselcraft** [comment]
Клон #127
