### ISSUE TITLE
Прикреплять чужие медиа к посту

### ISSUE THREAD

**Issue by IgordosDev** [OpenVK/openvk#902]
Не так давно в апи завезли прикрепление уже существующих медиа, но вот незадача, нельзя прикреплять к посту не свой файл
![image](https://github.com/openvk/openvk/assets/69392185/2b06d04f-476c-4c4f-8c1c-f81577754114)
Это литералли репост, почему нет?

**Comment by celestora** [comment]
> почему нет?

чтобы не спиздили

**Comment by IgordosDev** [comment]
> чтобы не спиздили

так в плеере всё равно пишется кто залил, или на странице с самим видео
если это шуточный коммент, я буду душнить всё равно
