### ISSUE TITLE
Через API можно получить удалённый пост

### ISSUE THREAD

**Issue by ghost** [OpenVK/openvk#909]
К примеру: https://openvk.uk/method/wall.getById?access_token=[вставьте_сюда_ваш_токен]&posts=-1_33.

Это можно легко пофиксить, просто добавив тут https://github.com/openvk/openvk/blob/3d90eb89ec93f9cf56a5c2d950d1a5dc6f476604/VKAPI/Handlers/Wall.php#L218C20-L218C20 `&& !$post->isDeleted()`

Пользуйтесь пока есть возможность

**Comment by ghost** [comment]
Затупил, надо не `|| !$post->isDeleted()` а `&& !$post->isDeleted()`

**Comment by Lumaeris** [comment]
![image](https://github.com/openvk/openvk/assets/10499845/1b0c251c-c294-4cd9-9ed6-fcf56564bfa0)
