### ISSUE TITLE
Не работает предпросмотр заметки

### ISSUE THREAD

**Issue by tretdm** [OpenVK/openvk#912]
https://github.com/openvk/openvk/assets/76806170/16abd8b3-bd44-471d-b5d0-1d1184909a29

**Comment by thejenja** [comment]
Сейчас проверил, предпросмотр в Mozila действительно вылетает, а вот в Chrome такого прикола нет.

bruh

**Comment by celestora** [comment]
Баг подтверждён, на 102 не воркает

**Comment by iamdelickkk** [comment]
почему бы не сделать попап с предпросмотром? xD

**Comment by celestora** [comment]
Вроде решено в https://github.com/openvk/openvk/commit/ef7b4b6c3e03a23f504b390c264ec814ca299416

**Comment by tretdm** [comment]
> Вроде решено в [ef7b4b6](https://github.com/openvk/openvk/commit/ef7b4b6c3e03a23f504b390c264ec814ca299416)

@celestora брух
![изображение](https://github.com/openvk/openvk/assets/76806170/38979fc8-1fe6-452f-8d06-b2d0458a2218)

**Comment by tretdm** [comment]
И еще у меня один вопрос, связанный с картинками внутри заметок. Вроде бы вне OpenVK картинки запрещены, но есть хитрость, и ею некоторые юзеры воспользовались этим. Например, чтобы разместить баннер с вашим айпишником из другого сайта.

![SCR_20230711_113549_firefox](https://github.com/openvk/openvk/assets/76806170/b0f8d09a-3af2-4c48-981f-0db8a548d75a)
![изображение](https://github.com/openvk/openvk/assets/76806170/5074705b-7142-4837-8d7e-5e7247f57a50)

**Comment by celestora** [comment]
> > Вроде решено в [ef7b4b6](https://github.com/openvk/openvk/commit/ef7b4b6c3e03a23f504b390c264ec814ca299416)
> 
> @celestora брух ![изображение](https://user-images.githubusercontent.com/76806170/252551140-38979fc8-1fe6-452f-8d06-b2d0458a2218.png)

Title пустой

**Comment by tretdm** [comment]
а, ладно
