### ISSUE TITLE
После закрытия заметки вместо страницы появляется [object Object]

### ISSUE THREAD

**Issue by veselcraft** [OpenVK/openvk#913]
https://github.com/openvk/openvk/assets/22993408/e646cbb2-02ef-46b0-9ac8-63743933c7e2

**Comment by myslivets** [comment]
Подтверждаю проблему

**Comment by iamdelickkk** [comment]
я наверное тупой, но наверное в #articleCloseButton нужно изменить атрибут href вместо `javascript:u('body').removeClass('article');` на` javascript:document.querySelector('body').classList.remove('article');`

**Comment by iamdelickkk** [comment]
или же использовать `onclick="u('body').removeClass('article');"` в #articleCloseButton но атрибут href будет изменен на # или javascript:void();

**Comment by cithis** [comment]
да, надо в `void` обернуц

**Comment by celestora** [comment]
Fixed in https://github.com/openvk/openvk/commit/a4454ab7a056c042d5de3c4ea950de3e568c2cc9
