### ISSUE TITLE
Баги с темами "ВК 2015 Тёмная тема" и "VK Night"

### ISSUE THREAD

**Issue by xh360** [OpenVK/openvk#917]
а ещё думаю, что стоит исправить белый фон у выпадающего меню и флажка-галочки.

https://github.com/openvk/openvk/assets/53079378/97d6f675-d57a-41f5-9b35-2f0346d9bc84

**Comment by xh360** [comment]
ой, не то видео видимо выложил.ща разберусь

**Comment by xh360** [comment]
пришлось экстренно архивировать "проблему" и вернуть обратно, поскольку я по ошибке не то видео приложил

**Comment by tretdm** [comment]
Можете, пожалуйста, адресовать этот issue авторам проблемных тем, так как это не относится к самому движку?

**Comment by celestora** [comment]
> Можете, пожалуйста, адресовать этот issue авторам проблемных тем, так как это не относится к самому движку?

а разве vknight не стоковая тема овк?

**Comment by tretdm** [comment]
> а разве vknight не стоковая тема овк?

есть же openvk midnight наряду с openvk modern и обычной стоковой вместо vknight

**Comment by tretdm** [comment]
vknight и вк2015 в репозиторий сюда не входит, так что все правильно, и этот issue по поводу нестоковых тем нецелесообразно сюда кидать

**Comment by xh360** [comment]
> vknight и вк2015 в репозиторий сюда не входит, так что все правильно, и этот issue по поводу нестоковых тем нецелесообразно сюда кидать

класс, я хз, куда кидать

**Comment by xh360** [comment]
> класс, я хз, куда кидать

теперь узнал
