### ISSUE TITLE
Не полный фикс админ-панели

### ISSUE THREAD

**Issue by zavolo** [OpenVK/openvk#92]
Зайти в админ-панель и попробовать что нибудь сохранить в поле у юзеров , выйдет ошибка (не офф инстанс)
![image](https://user-images.githubusercontent.com/90477403/133114751-198bd04a-5339-4902-b276-1cbc42541ba7.png)

**Comment by veselcraft** [comment]
Вроде должно быть исправлено в https://github.com/openvk/openvk/commit/c35f06e9e7ec027d2a2d6de9f2eceef5f17e9879, чи не?

**Comment by VladimirLapskiy** [comment]
Обновись.

**Comment by VladimirLapskiy-zz** [comment]
Чекнул версию твоей инстации (1:29 GMT +5), этой проблемы не должно быть.

**Comment by WerySkok** [comment]
У тебя есть роль админа?
