### ISSUE TITLE
Создание групп и альбомов с пустым именем и с пустым описанием

### ISSUE THREAD

**Issue by iamdelickkk** [OpenVK/openvk#924]
Все просто! Просто вставляете пробел в полях для ввода и готово!
![image](https://github.com/openvk/openvk/assets/91693467/a4a1ab1b-8c71-4fc5-9135-abe9e0fd1f45)

**Comment by iamdelickkk** [comment]
![image](https://github.com/openvk/openvk/assets/91693467/fd9fd98c-65de-4077-9218-4ce8041df898)

**Comment by iamdelickkk** [comment]
Issue закройте пж

**Comment by ghost** [comment]
> Issue закройте пж

Он после мержа закроется

**Comment by iamdelickkk** [comment]
А ок
