### ISSUE TITLE
В разных темах сломан поиск

### ISSUE THREAD

**Issue by nbt1248** [OpenVK/openvk#948]
В темах Втлену, vriska.ru, ВКонтакте 2015 тёмная тема, ВКонтакте 2015, ВКонтакте 2012, VK и VK Night сломаны подсказки при поиске
![image](https://github.com/openvk/openvk/assets/67861312/2f1e98c6-e757-478e-b8d4-25079ecd9021)
![image](https://github.com/openvk/openvk/assets/67861312/8e54464e-798d-42be-8607-608e61911dff)
![image](https://github.com/openvk/openvk/assets/67861312/52ba1e9b-6f8f-4538-bb19-c6917bf55e4b)
![image](https://github.com/openvk/openvk/assets/67861312/0369eb3b-7743-4255-aa94-9d68d37fbc93)
![image](https://github.com/openvk/openvk/assets/67861312/bb6d7cbc-e867-4f2f-8fe6-9509034c3311)
![image](https://github.com/openvk/openvk/assets/67861312/ab706340-16ea-4e6c-a6df-5bee1bc80ee7)
![image](https://github.com/openvk/openvk/assets/67861312/9410bd49-5641-48e3-b555-59bd964a3f12)

В теме The Facebook 2005 поиск напрочь сломан
![image](https://github.com/openvk/openvk/assets/67861312/400a902d-55ee-42b8-ac15-7934ab443a73)

В теме Вконтакте 2006 Бета поиск тоже сломан, но по-другому
![image](https://github.com/openvk/openvk/assets/67861312/5353f628-1448-46a3-b3c4-e9f6420fa4c8)

И в теме Windows XP с фоном (тоже по-другому)
![image](https://github.com/openvk/openvk/assets/67861312/02e1ee1c-d462-4011-9e3c-aa404b0b3bab)

**Comment by ayaaop** [comment]
надо обращаться к темоделам самим а не сюда

**Comment by veselcraft** [comment]
> Убедительная просьба НЕ присылать нам issue тем оформления и несвязные с движком проблемы, по типу блокировки группы на определённом веб-сайте
