### ISSUE TITLE
Error 500 при регистрации пользователя 

### ISSUE THREAD

**Issue by saursvepur** [OpenVK/openvk#963]
После нажатия кнопки "Регистрация" вылетает **ошибка 500** а именно **Call to a member function getId() on null**

![image](https://github.com/openvk/openvk/assets/55963296/bc392190-9331-49cd-8ca5-264ce4308d35)
![image](https://github.com/openvk/openvk/assets/55963296/c361abb6-7fc5-4145-9334-743233548949)

**По факту новый пользователь регистрируется и после обновления страницы ошибка пропадает**

**Comment by veselcraft** [comment]
стоит откатить обнову с логированнием #940, он ломает ВСЁ. апи уж точно(

**Comment by veselcraft** [comment]
Пофиксил все связанные с логированием ошибки тут: https://github.com/openvk/chandler/commit/fc531f4d16f6b8cbc716ccf1ad9a90476bff1876

**Comment by saursvepur** [comment]
trouble решён, закрываем нахуй!
